#!/usr/bin/env python3
"""Fixture-based tests for scripts/harbor-research/check_figure_blockers.py.

stdlib-only (unittest, tempfile, subprocess, json). Each fixture test writes
a small blockers.json under a tempdir and runs the real script against it
with --repo-root (and --as-of, to make expiry deterministic). One test runs
the same checker with no --repo-root override against this repository's own
committed blockers.json.

Run:
    python3 -m unittest discover -s tests/harbor-research
    python3 tests/harbor-research/test_check_figure_blockers.py
"""
from __future__ import annotations

import json
import subprocess
import sys
import unittest
from pathlib import Path
from tempfile import TemporaryDirectory

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "harbor-research" / "check_figure_blockers.py"
BLOCKERS_REL = Path("docs/harbor-research/exposition/figures/blockers.json")


def entry(id_: str, checks_failed: list[str], waiver: dict | None) -> dict:
    return {
        "id": id_,
        "fragment": f"whitepaper/figures/{id_}.tex",
        "chapter": 1,
        "checks_failed": checks_failed,
        "first_seen": "2026-09-07",
        "waiver": waiver,
    }


def write_blockers(root: Path, blockers: list[dict]) -> None:
    path = root / BLOCKERS_REL
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(blockers, indent=2), encoding="utf-8")


def run(root: Path, *extra: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        [sys.executable, str(SCRIPT), "--repo-root", str(root), "--as-of", "2026-09-07", *extra],
        capture_output=True, text=True,
    )


class TestCheckFigureBlockers(unittest.TestCase):
    def test_committed_blockers_json_is_fully_waived_by_its_triage(self) -> None:
        """This repo's real blockers.json is EXPECTED to fail today -- that
        is the whole point of turning figcheck into a release blocker (see
        this directory's README.md, "Waivers" section). This test pins the current,
        known count so a change in it is a deliberate, reviewed act (a new
        waiver seeded, or a figure actually fixed), not silent drift.

        Every one of the 61 is waived today, and by which rule matters: 23 are
        figures the triage is deleting or turning into tables, so their defects
        will never be fixed and must not block; 38 are figures the triage
        condemned and scheduled, so their defects are a dated backlog. The
        negative controls for both live in the tests below, on fixtures --
        this one only records what the real register says. All 61 expire on
        one date, so the whole backlog comes up for review together."""
        result = subprocess.run(
            [sys.executable, str(SCRIPT), "--verbose"],
            capture_output=True, text=True, cwd=REPO_ROOT,
        )
        self.assertEqual(result.returncode, 0, msg=result.stdout + result.stderr)
        # The pin stays a pin. Deriving the expected count from blockers.json
        # would make this assertion tautological -- check_figure_blockers.py
        # reads that same file, so the two can never disagree -- and the drift
        # this test exists to catch would stop being catchable. What the pin
        # needs is a message that tells you what the reviewed act IS, because a
        # bare count mismatch does not: blockers.json is GENERATED, and the
        # obvious repair (hand-edit the register, or run --write to make the
        # staleness check happy) is wrong in one direction and destructive in
        # the other.
        drift = (
            f"blockers.json's waived count moved off the pinned 61.\n"
            f"  got: {result.stdout.strip().splitlines()[-1] if result.stdout.strip() else '(no output)'}\n"
            f"blockers.json is GENERATED by scripts/harbor-research/render_figure_audit.py\n"
            f"from the figcheck/*.json records plus FIGURE-TRIAGE.md's dispositions. Do not\n"
            f"hand-edit it: the next `render_figure_audit.py --write` erases anything added\n"
            f"by hand, and an entry only exists at all for a fragment whose committed\n"
            f"figcheck record shows a T1-T5 failure.\n"
            f"To change the register, change what it is generated FROM:\n"
            f"  1. re-run figcheck and commit the fragment's record, if the record is stale;\n"
            f"  2. set the fragment's disposition in FIGURE-TRIAGE.md -- `delete`/`table`\n"
            f"     seed the retired waiver, `redraw`/`restyle`/`keep+note` the backlog one,\n"
            f"     and `keep` seeds NOTHING on purpose (a figure the triage passed and the\n"
            f"     machine fails is a contradiction somebody should look at, not wave through);\n"
            f"  3. run `python3 scripts/harbor-research/render_figure_audit.py --write`;\n"
            f"  4. move this pin, and say in the PR which figures moved and why."
        )
        self.assertIn("61 waived", result.stdout, msg=drift)
        self.assertIn("0 failure(s)", result.stdout, msg=drift)

    def test_all_waived_and_unexpired_passes(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            write_blockers(root, [
                entry("fig-a", ["T1"], {"reason": "retired by triage", "expires": "2026-10-31"}),
                entry("fig-b", ["T4"], {"reason": "retired by triage", "expires": "2026-09-07"}),  # expires == as_of: still valid
            ])
            result = run(root)
            self.assertEqual(result.returncode, 0, msg=result.stdout)

    def test_unwaived_entry_fails(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            write_blockers(root, [entry("fig-a", ["T1"], None)])
            result = run(root)
            self.assertEqual(result.returncode, 1)
            self.assertIn("carries no waiver", result.stdout)

    def test_expired_waiver_fails(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            write_blockers(root, [
                entry("fig-a", ["T1"], {"reason": "retired by triage", "expires": "2026-01-01"}),
            ])
            result = run(root)
            self.assertEqual(result.returncode, 1)
            self.assertIn("waiver expired", result.stdout)

    def test_malformed_expiry_date_fails(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            write_blockers(root, [
                entry("fig-a", ["T1"], {"reason": "oops", "expires": "not-a-date"}),
            ])
            result = run(root)
            self.assertEqual(result.returncode, 1)
            self.assertIn("not YYYY-MM-DD", result.stdout)

    def test_duplicate_id_fails(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            write_blockers(root, [
                entry("fig-a", ["T1"], {"reason": "x", "expires": "2026-10-31"}),
                entry("fig-a", ["T4"], {"reason": "x", "expires": "2026-10-31"}),
            ])
            result = run(root)
            self.assertEqual(result.returncode, 1)
            self.assertIn("duplicate blocker id", result.stdout)

    def test_missing_blockers_file_is_fatal(self) -> None:
        with TemporaryDirectory() as tmp:
            result = run(Path(tmp))
            self.assertEqual(result.returncode, 1)
            self.assertIn("does not exist", result.stderr)

    def test_empty_list_passes(self) -> None:
        with TemporaryDirectory() as tmp:
            root = Path(tmp)
            write_blockers(root, [])
            result = run(root)
            self.assertEqual(result.returncode, 0, msg=result.stdout)


if __name__ == "__main__":
    unittest.main()
