//! Port Daddy TUI surfaces — shared infrastructure.
//!
//! `tokens` is generated by `design/build.mjs` from `design/tokens/*.json`.
//! Do not edit it directly. Re-run the build script to refresh.

pub mod logo;
pub mod tokens;

use ratatui::style::Color;

/// Resolve the active theme from the `PD_THEME` environment variable.
/// Defaults to dark. Returns a trait object so callers can hold either
/// theme behind the same interface.
pub fn active_theme() -> &'static dyn tokens::Theme {
    match std::env::var("PD_THEME").as_deref() {
        Ok("light") => &tokens::light::THEME,
        _ => &tokens::dark::THEME,
    }
}

/// The four ICS signal flags rendered as 16x16 sub-cell pixel grids,
/// paintable via `Canvas + Marker::HalfBlock` at x_bounds [0..16],
/// y_bounds [0..16]. Each function returns rectangles to paint.
///
/// This is the maritime DNA crossing into the TUI — the same flag that
/// the web preview renders as inline SVG now lives in coordinate-space
/// inside the terminal.
pub mod flags {
    use ratatui::style::Color;

    /// One filled rectangle to paint on the Canvas.
    pub struct FlagRect {
        pub x: f64,
        pub y: f64,
        pub w: f64,
        pub h: f64,
        pub color: Color,
    }

    /// ICS Mike — vessel stopped, making no way. Blue field with a white X.
    /// At 16x16 we render the field, then two crossing diagonals as thick rects.
    pub fn mike() -> Vec<FlagRect> {
        let blue = Color::Rgb(30, 58, 138);
        let white = Color::Rgb(250, 250, 245);
        let mut rects = vec![
            // Field
            FlagRect { x: 0.0, y: 0.0, w: 16.0, h: 16.0, color: blue },
        ];
        // White diagonals — 4 thick steps each direction
        for i in 0..16 {
            let xs = i as f64;
            let ys_down = i as f64;
            let ys_up = (15 - i) as f64;
            for dx in 0..2 {
                rects.push(FlagRect {
                    x: xs + dx as f64 * 0.5 - 0.25,
                    y: ys_down,
                    w: 1.0,
                    h: 1.0,
                    color: white,
                });
                rects.push(FlagRect {
                    x: xs + dx as f64 * 0.5 - 0.25,
                    y: ys_up,
                    w: 1.0,
                    h: 1.0,
                    color: white,
                });
            }
        }
        rects
    }

    /// ICS Kilo — I wish to communicate. Yellow left half, blue right half.
    pub fn kilo() -> Vec<FlagRect> {
        let yellow = Color::Rgb(237, 197, 49);
        let blue = Color::Rgb(30, 58, 138);
        vec![
            FlagRect { x: 0.0, y: 0.0, w: 8.0, h: 16.0, color: yellow },
            FlagRect { x: 8.0, y: 0.0, w: 8.0, h: 16.0, color: blue },
        ]
    }

    /// ICS Bravo — dangerous cargo / burning resource. Solid red.
    pub fn bravo() -> Vec<FlagRect> {
        let red = Color::Rgb(191, 47, 47);
        vec![FlagRect { x: 0.0, y: 0.0, w: 16.0, h: 16.0, color: red }]
    }
}

#[allow(dead_code)]
pub(crate) fn _unused_imports() {
    let _: Color = Color::Reset;
}
