"""Turns a pinned commit range (corpora.json) into an ordered task list.

A task is one non-merge, non-binary-touching, <=2000-changed-line commit's
diff, in first-parent chronological order. Building the list requires the
corpus's git history; the result is cached to disk (.cache/tasks/<name>.json)
so repeated `run.py` invocations across many cells do not re-walk history.
"""
from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, asdict

from . import gitutil

MAX_CHANGED_LINES = 2000


@dataclass
class Task:
    task_id: int          # 0-based index into the kept (post-drop) sequence
    sha: str
    parent_sha: str
    files: list           # paths touched
    lines_changed: int    # added + deleted, text files only
    patch: str            # unified diff, parent_sha -> sha, usable with `git apply`
    file_ranges: dict      # path -> list of [start,end] new-file line ranges touched


@dataclass
class CorpusDropCounts:
    considered: int = 0
    merges: int = 0
    binary: int = 0
    oversize: int = 0
    kept: int = 0


def repo_cache_dir(base_dir: str) -> str:
    d = os.path.join(base_dir, ".cache", "repos")
    os.makedirs(d, exist_ok=True)
    return d


def task_cache_dir(base_dir: str) -> str:
    d = os.path.join(base_dir, ".cache", "tasks")
    os.makedirs(d, exist_ok=True)
    return d


def load_corpora(base_dir: str) -> dict:
    with open(os.path.join(base_dir, "corpora.json"), "r", encoding="utf-8") as f:
        return json.load(f)["corpora"]


def ensure_bare_clone(base_dir: str, name: str, repo_url: str, changelog_note) -> str:
    """Return path to a bare mirror clone of repo_url, cloning if absent.

    Fallback ladder (per the ground rules): plain bare clone; then a shallow
    blob-filtered clone; then (only if both fail) the caller is told to fall
    back to a corpus generated from this repository's own history, and that
    fallback is recorded via changelog_note(str).
    """
    dest = os.path.join(repo_cache_dir(base_dir), f"{name}.git")
    if os.path.isdir(dest):
        return dest
    tmp = dest + ".partial"
    if os.path.isdir(tmp):
        _rmtree(tmp)
    try:
        gitutil.run(base_dir, ["clone", "--bare", repo_url, tmp], timeout=900)
        os.rename(tmp, dest)
        return dest
    except gitutil.GitError as e1:
        changelog_note(f"plain bare clone of {repo_url} failed ({e1.returncode}); "
                        f"retrying with --filter=blob:none --depth 700")
        if os.path.isdir(tmp):
            _rmtree(tmp)
        try:
            gitutil.run(base_dir, ["clone", "--filter=blob:none", "--depth", "700",
                                    "--bare", repo_url, tmp], timeout=900)
            os.rename(tmp, dest)
            return dest
        except gitutil.GitError as e2:
            changelog_note(f"shallow blob-filtered clone of {repo_url} also failed "
                            f"({e2.returncode}); a self-history fallback corpus is required "
                            f"and must be generated by the caller.")
            raise


def _rmtree(path: str) -> None:
    import shutil
    shutil.rmtree(path, ignore_errors=True)


_HUNK_RE = re.compile(r"^@@ -(\d+)(?:,(\d+))? \+(\d+)(?:,(\d+))? @@")


def _parse_new_side_ranges(patch_text: str) -> dict:
    """path -> list of [start,end] inclusive line ranges on the *new* side."""
    ranges: dict[str, list] = {}
    current_path = None
    for line in patch_text.splitlines():
        if line.startswith("+++ "):
            p = line[4:].strip()
            if p.startswith("b/"):
                p = p[2:]
            current_path = None if p == "/dev/null" else p
        elif line.startswith("@@ ") and current_path is not None:
            m = _HUNK_RE.match(line)
            if m:
                start = int(m.group(3))
                count = int(m.group(4)) if m.group(4) is not None else 1
                end = start + max(count - 1, 0)
                ranges.setdefault(current_path, []).append([start, end])
    return ranges


def build_tasks(base_dir: str, name: str, corpus_def: dict, changelog_note) -> tuple:
    """Build (or load cached) task list. Returns (list[Task], CorpusDropCounts)."""
    cache_file = os.path.join(task_cache_dir(base_dir), f"{name}.json")
    if os.path.isfile(cache_file):
        with open(cache_file, "r", encoding="utf-8") as f:
            blob = json.load(f)
        tasks = [Task(**t) for t in blob["tasks"]]
        counts = CorpusDropCounts(**blob["drop_counts"])
        return tasks, counts

    repo = ensure_bare_clone(base_dir, name, corpus_def["repo_url"], changelog_note)
    start_sha = corpus_def["start_sha"]
    end_sha = corpus_def["end_sha"]

    shas = gitutil.run(
        repo, ["rev-list", "--first-parent", "--reverse", f"{start_sha}^..{end_sha}"]
    ).stdout.split()

    counts = CorpusDropCounts()
    tasks: list[Task] = []
    # `chain_base_sha` is the tree a kept task's patch is computed against.
    # It starts at the window's true base (start_sha^) and advances to each
    # kept task's own sha as tasks are kept. A dropped commit (merge,
    # binary, oversize) does NOT advance it: PROTOCOL.md drops that commit
    # from the task sequence, but the *next kept* task's real git parent is
    # still that dropped commit (or further back, through a run of drops) —
    # a simulated tree that only ever lands kept tasks never receives the
    # dropped commit's changes. Computing each kept task's patch against the
    # commit's own git parent would then require content our tree never
    # has, which is not concurrent-agent tearing but a corpus-preparation
    # artifact, and it was caught exactly that way: every substrate
    # including the enforced rail (C) started failing to land tasks whose
    # real parent had been dropped. Bridging — diffing straight from the
    # last KEPT sha (or the window base) to this kept sha — folds any
    # dropped commits' changes into the next kept task's patch, so the
    # simulated tree is always self-consistent. The keep/drop decision
    # itself still uses each commit's own diff against its own real parent,
    # matching PROTOCOL.md S2.1's literal per-commit criteria; only what a
    # *kept* task's recorded patch/files/lines_changed represent changes.
    chain_base_sha = gitutil.run(repo, ["rev-parse", f"{corpus_def['start_sha']}^"]).stdout.strip()

    for sha in shas:
        counts.considered += 1
        parents = gitutil.run(repo, ["rev-list", "--parents", "-1", sha]).stdout.split()
        # parents[0] is sha itself; anything after index 1 means a merge.
        if len(parents) > 2:
            counts.merges += 1
            continue
        own_parent_sha = parents[1] if len(parents) > 1 else ""
        if not own_parent_sha:
            # root commit (should not occur inside a 600-commit window, but be safe)
            counts.merges += 1
            continue

        own_numstat = gitutil.run(repo, ["diff", "--numstat", own_parent_sha, sha]).stdout
        own_is_binary = any(
            line.split("\t")[0] in ("-",) for line in own_numstat.splitlines() if line.strip()
        )
        own_lines_changed = 0
        if not own_is_binary:
            for line in own_numstat.splitlines():
                if not line.strip():
                    continue
                parts = line.split("\t")
                if len(parts) < 3:
                    continue
                own_lines_changed += int(parts[0]) + int(parts[1])

        if own_is_binary:
            counts.binary += 1
            continue
        if own_lines_changed > MAX_CHANGED_LINES:
            counts.oversize += 1
            continue
        if own_lines_changed == 0:
            # nothing text-visible changed (e.g. mode-only change); drop as a
            # binary/no-op edge case rather than invent a metric for it.
            counts.binary += 1
            continue

        # Kept: compute the recorded task from the bridging diff, not the
        # commit's own diff, so the simulated tree stays self-consistent.
        patch = gitutil.run(repo, ["diff", chain_base_sha, sha], timeout=60).stdout
        numstat = gitutil.run(repo, ["diff", "--numstat", chain_base_sha, sha]).stdout
        files = []
        lines_changed = 0
        for line in numstat.splitlines():
            if not line.strip():
                continue
            parts = line.split("\t")
            if len(parts) < 3:
                continue
            added, deleted, path = parts[0], parts[1], parts[2]
            files.append(path)
            if added != "-" and deleted != "-":
                lines_changed += int(added) + int(deleted)
        if not files:
            # the bridging diff collapsed to nothing (e.g. a revert of a
            # dropped commit); nothing to land, so don't record a task.
            chain_base_sha = sha
            continue

        file_ranges = _parse_new_side_ranges(patch)

        tasks.append(Task(
            task_id=len(tasks),
            sha=sha,
            parent_sha=chain_base_sha,
            files=files,
            lines_changed=lines_changed,
            patch=patch,
            file_ranges=file_ranges,
        ))
        chain_base_sha = sha
    counts.kept = len(tasks)

    with open(cache_file, "w", encoding="utf-8") as f:
        json.dump({"tasks": [asdict(t) for t in tasks],
                   "drop_counts": asdict(counts)}, f)
    return tasks, counts
