import XCTest
import Foundation
@testable import PortDaddyKit

/// The HITL inbox's honesty rules, and the one boundary that is easy to cross
/// by accident: this app reads asks, it does not close them.
///
/// Plus the shape gate. interruptions.fixture.json is GENERATED by
/// scripts/generate-pd-ios-fixtures.ts from `publicShape()` in
/// apps/relay/src/interruptions.ts and the operator_interruptions column types,
/// and it carries a `shape` block saying what JSON type each field is and
/// whether it may be null. The tests under "The shape gate" assert this Swift
/// port models exactly those keys at exactly those types.
///
/// That gate exists because the hand-authored fixture it replaced hid a live
/// bug: it wrote `"installationId": "inst_7710"` while `installation_id` is an
/// INTEGER the relay passes straight through, so every installation-scoped ask
/// threw DecodingError.typeMismatch, aborted the whole array decode, and
/// rendered the operator's inbox as "unknown" — while this suite stayed green
/// because it was reading the fixture's claim rather than the relay's.
final class InterruptionsInboxTests: XCTestCase {

    private func inbox() throws -> InterruptionListResponse {
        try PortDaddyFixtures.interruptions()
    }

    func testDecodesTheRelayPublicShape() throws {
        let response = try inbox()
        XCTAssertEqual(response.code, "OK")
        XCTAssertNil(response.error)
        XCTAssertEqual(response.openCount, 2)

        let critical = try XCTUnwrap(response.interruptions.first { $0.urgency == .critical })
        XCTAssertEqual(critical.state, .open)
        XCTAssertEqual(critical.nagCount, 2)
        XCTAssertNil(critical.answer)

        let answered = try XCTUnwrap(response.interruptions.first { $0.state == .answered })
        XCTAssertNotNil(answered.answer)
        XCTAssertNotNil(answered.closedAt)
    }

    /// An urgency this build does not know decodes as normal rather than
    /// dropping the ask; a STATE it does not know decodes as OPEN, because the
    /// safe direction is "still needs you", never "already handled".
    func testUnknownEnumsDecodeInTheSafeDirection() throws {
        let json = """
        {
          "id": "oi_future",
          "sourceAgent": "pd-unknown",
          "title": "An ask from a newer relay",
          "urgency": "apocalyptic",
          "state": "quarantined",
          "createdAt": 1755820000
        }
        """
        let ask = try JSONDecoder().decode(OperatorInterruption.self, from: Data(json.utf8))
        XCTAssertEqual(ask.urgency, .normal)
        XCTAssertEqual(ask.state, .open, "an unrecognised state must not read as closed")
        XCTAssertEqual(ask.body, "")
        XCTAssertEqual(ask.nagCount, 0)
    }

    func testContractOrderIsUrgencyThenOldestFirst() throws {
        let ordered = InterruptionInbox.inContractOrder(try inbox().interruptions)
        XCTAssertEqual(ordered.map(\.urgency), [.critical, .high, .normal, .low])
        let ranks = ordered.map(\.urgency.rank)
        XCTAssertEqual(ranks, ranks.sorted())
    }

    func testBlockingCriticalIsFoundAndOnlyWhenOpen() throws {
        let items = try inbox().interruptions
        let blocking = try XCTUnwrap(InterruptionInbox.blockingCritical(items))
        XCTAssertEqual(blocking.urgency, .critical)
        XCTAssertEqual(blocking.state, .open)

        let closedOnly = items.filter { $0.state.isClosed }
        XCTAssertNil(
            InterruptionInbox.blockingCritical(closedOnly),
            "a closed critical ask must not keep dependent work blocked forever"
        )
    }

    // MARK: - The shape gate

    private struct FieldShape: Decodable {
        let column: String
        let sqlType: String
        let jsonType: String
        let nullable: Bool
    }

    private struct ShapeFixture: Decodable {
        let shape: [String: FieldShape]
        let urgencies: [String]
        let states: [String]
    }

    private func shape() throws -> ShapeFixture {
        try PortDaddyFixtures.decode(ShapeFixture.self, from: .interruptions)
    }

    /// The regression. `installation_id` is INTEGER; `publicShape` returns the
    /// column unchanged; therefore the wire value is a JSON NUMBER. This
    /// property was `String?` and threw on every ask that had one.
    func testInstallationScopeDecodesFromTheRelaysJsonNumber() throws {
        let declared = try XCTUnwrap(shape().shape["installationId"])
        XCTAssertEqual(declared.column, "installation_id")
        XCTAssertEqual(declared.sqlType, "INTEGER")
        XCTAssertEqual(declared.jsonType, "number", "the relay sends a number; the Swift property must be an Int")
        XCTAssertTrue(declared.nullable)

        let json = """
        {
          "id": "oi_scoped",
          "installationId": 77103928,
          "sourceAgent": "pd-relay-deploy",
          "title": "An ask carrying a GitHub App installation scope",
          "urgency": "critical",
          "state": "open",
          "createdAt": 1755820380
        }
        """
        let ask = try JSONDecoder().decode(OperatorInterruption.self, from: Data(json.utf8))
        XCTAssertEqual(ask.installationId, 77103928)
    }

    /// Why the type mattered so much: `interruptions` is a non-optional array,
    /// so ONE ask that throws costs the operator every other ask in the
    /// response — including the critical one they were being paged about.
    func testOneInstallationScopedAskDoesNotBlankTheWholeInbox() throws {
        let json = """
        {
          "code": "OK",
          "error": null,
          "openCount": 2,
          "interruptions": [
            { "id": "oi_scoped", "installationId": 77103928, "sourceAgent": "a",
              "title": "Deploy the relay worker or stop the wave?", "urgency": "critical",
              "state": "open", "createdAt": 1755820380 },
            { "id": "oi_unscoped", "installationId": null, "sourceAgent": "b",
              "title": "An ask with no installation scope", "urgency": "normal",
              "state": "open", "createdAt": 1755820400 }
          ]
        }
        """
        let response = try JSONDecoder().decode(InterruptionListResponse.self, from: Data(json.utf8))
        XCTAssertEqual(response.interruptions.count, 2, "an installation-scoped ask must not abort the array decode")
        XCTAssertEqual(response.interruptions.first?.installationId, 77103928)
        XCTAssertNil(response.interruptions.last?.installationId)
    }

    /// The scope is a label on an ask, not the ask. No shape it can arrive in
    /// is worth dropping the operator's inbox over.
    func testInstallationScopeIsNeverWorthThrowingOver() throws {
        let cases: [(fragment: String, expected: Int?)] = [
            ("", nil),                                      // absent
            ("\"installationId\": null,", nil),              // explicit null
            ("\"installationId\": 77103928,", 77103928),     // today's relay
            ("\"installationId\": \"77103928\",", 77103928), // a stringifying proxy
            ("\"installationId\": \"inst_7710\",", nil),    // junk, and still not fatal
        ]
        for (fragment, expected) in cases {
            let json = """
            {
              \(fragment)
              "id": "oi_tolerant",
              "sourceAgent": "pd-relay-deploy",
              "title": "An ask that must survive its own metadata",
              "urgency": "critical",
              "state": "open",
              "createdAt": 1755820380
            }
            """
            let ask = try JSONDecoder().decode(OperatorInterruption.self, from: Data(json.utf8))
            XCTAssertEqual(ask.installationId, expected, "installationId fragment <\(fragment)>")
            XCTAssertEqual(ask.urgency, .critical, "the ask itself must survive fragment <\(fragment)>")
        }
    }

    /// The systemic gate: the Swift type models exactly `publicShape`'s keys.
    /// A relay that adds a field goes red here instead of being silently
    /// dropped on the way to the phone.
    func testOperatorInterruptionModelsExactlyThePublicShapeKeys() throws {
        let declared = Set(try shape().shape.keys)
        let modelled = Set(OperatorInterruption.CodingKeys.allCases.map(\.stringValue))
        XCTAssertEqual(
            declared,
            modelled,
            "publicShape() and OperatorInterruption disagree about which fields exist: "
                + "relay-only \(declared.subtracting(modelled).sorted()), "
                + "swift-only \(modelled.subtracting(declared).sorted())"
        )
    }

    /// Every value in the fixture carries the JSON type its column implies —
    /// so the fixture can no longer disagree with the relay the way the
    /// hand-authored one did.
    func testFixtureCarriesEveryFieldAtTheRelaysDeclaredJsonType() throws {
        let declared = try shape().shape
        let object = try PortDaddyFixtures.object(.interruptions)
        let entries = try XCTUnwrap(object["interruptions"] as? [[String: Any]])
        XCTAssertFalse(entries.isEmpty)

        for entry in entries {
            let id = (entry["id"] as? String) ?? "<no id>"
            XCTAssertEqual(Set(entry.keys), Set(declared.keys), "\(id) does not carry publicShape's key set")

            for (key, field) in declared {
                let value = try XCTUnwrap(entry[key], "\(id).\(key) is missing")
                if value is NSNull {
                    XCTAssertTrue(field.nullable, "\(id).\(key) is null but \(field.column) is NOT NULL")
                } else if value is String {
                    XCTAssertEqual(field.jsonType, "string", "\(id).\(key) is a string but \(field.column) is \(field.sqlType)")
                } else if value is NSNumber {
                    XCTAssertEqual(field.jsonType, "number", "\(id).\(key) is a number but \(field.column) is \(field.sqlType)")
                } else {
                    XCTFail("\(id).\(key) is neither string, number, nor null")
                }
            }
        }

        // At least one ask carries a scope and at least one does not, so both
        // branches of the optional are actually exercised above.
        let scopes = entries.compactMap { $0["installationId"] }
        XCTAssertTrue(scopes.contains { $0 is NSNumber }, "no ask in the fixture carries an installation scope")
        XCTAssertTrue(scopes.contains { $0 is NSNull }, "no ask in the fixture omits its installation scope")
    }

    /// The enums are the columns' CHECK lists, read out of the migration —
    /// not a remembered list that drifted.
    func testUrgencyAndStateMatchTheColumnsCheckConstraints() throws {
        let fixture = try shape()
        XCTAssertEqual(
            Set(fixture.urgencies),
            Set(InterruptionUrgency.allCases.map(\.rawValue)),
            "urgency CHECK constraint and InterruptionUrgency disagree"
        )
        XCTAssertEqual(
            Set(fixture.states),
            Set(InterruptionState.allCases.map(\.rawValue)),
            "state CHECK constraint and InterruptionState disagree"
        )
    }

    // MARK: - Never fabricate

    /// The rule: unknown is not zero. A badge of 0 asserts that nothing is
    /// waiting; an inbox that failed to load has not earned that assertion.
    func testUnknownInboxHasNoBadgeCount() {
        let unknown = InterruptionInboxStatus.unknown(reason: "offline")
        XCTAssertTrue(unknown.isUnknown)
        XCTAssertNil(unknown.badgeCount)

        let empty = InterruptionInboxStatus.loaded(openCount: 0)
        XCTAssertFalse(empty.isUnknown)
        XCTAssertEqual(empty.badgeCount, 0, "a successful read of zero IS zero")
    }

    func testLoadableKeepsUnknownAndEmptyApart() {
        let unknown: Loadable<[OperatorInterruption]> = .unknown(reason: "request timed out")
        XCTAssertTrue(unknown.isUnknown)
        XCTAssertNil(unknown.value)
        XCTAssertEqual(unknown.unknownReason, "request timed out")

        let empty: Loadable<[OperatorInterruption]> = .loaded([], provenance: .live(source: "relay"))
        XCTAssertFalse(empty.isUnknown)
        XCTAssertEqual(empty.value?.count, 0)
    }

    // MARK: - Polling

    /// Full jitter means a uniform draw over the whole window, not a fixed
    /// base with a wiggle. A fleet of phones on a fixed timer is a
    /// synchronised herd against the relay.
    func testPollDelayIsFullJitterWithinTheCap() {
        XCTAssertEqual(InterruptionInbox.pollCapSeconds, 30)

        // The randomizer is injected so the bounds are asserted, not sampled.
        var seen: [ClosedRange<Double>] = []
        _ = InterruptionInbox.nextPollDelay(randomizer: { range in
            seen.append(range)
            return range.lowerBound
        })
        XCTAssertEqual(seen.count, 1)
        let range = try? XCTUnwrap(seen.first)
        XCTAssertEqual(range?.upperBound, 30, "the draw must span the whole window")
        XCTAssertLessThan(range?.lowerBound ?? 1, 1, "the draw must start near zero, not at a fixed base")

        for _ in 0..<200 {
            let delay = InterruptionInbox.nextPollDelay()
            XCTAssertGreaterThan(delay, 0)
            XCTAssertLessThanOrEqual(delay, 30)
        }
    }

    // MARK: - The answer boundary

    /// The relay's closeInterruption requires a signed-in session AND a
    /// same-origin check, so a device bearer token cannot close an ask. The
    /// app hands off to the web surface instead. If this test ever needs
    /// changing, the relay's auth model changed — check that first.
    func testAnswerIsAHandoffToTheSessionGatedWebSurface() throws {
        let base = try XCTUnwrap(URL(string: "https://relay.portdaddy.dev"))
        let handoff = InterruptionHandoff.webAnswerSurface(relayBaseURL: base, interruptionID: "oi_4f1c8a02")
        XCTAssertEqual(handoff.url.path, "/account/interruptions")
        XCTAssertEqual(handoff.url.fragment, "oi_4f1c8a02")
        XCTAssertEqual(handoff.url.scheme, "https")
        XCTAssertFalse(handoff.explanation.isEmpty, "the operator is told why they are leaving the app")
    }

    func testHandoffWithoutAnIdStillLandsOnTheInboxPage() throws {
        let base = try XCTUnwrap(URL(string: "https://relay.portdaddy.dev"))
        let handoff = InterruptionHandoff.webAnswerSurface(relayBaseURL: base)
        XCTAssertEqual(handoff.url.path, "/account/interruptions")
        XCTAssertNil(handoff.url.fragment)
    }
}
