import React, { useEffect, useRef, useCallback } from 'react'
import mermaid from 'mermaid'
import { Surface } from './Surface'

interface MermaidProps {
  chart: string
}

export const Mermaid: React.FC<MermaidProps> = ({ chart }) => {
  const ref = useRef<HTMLDivElement>(null)

  const renderChart = useCallback(() => {
    const root = document.documentElement
    const style = getComputedStyle(root)
    const isDark = root.getAttribute('data-theme') === 'dark'

    const primary = style.getPropertyValue('--brand-secondary').trim() || '#4A9D9E'
    const surface = style.getPropertyValue('--surface-base').trim() || '#F5F1E9'   // p-stone-50
    const raised = style.getPropertyValue('--surface-raised').trim() || '#EBE5D6'  // p-stone-100
    const border = style.getPropertyValue('--border-strong').trim() || '#C0B193'   // p-stone-400
    const text = style.getPropertyValue('--text-primary').trim() || '#1E1B18'

    // High-contrast colors for labels/arrows in both themes (all from Harbor Heritage palette)
    const signalText = isDark ? '#E8E0D4' : '#1E1B18'   // p-ebony-50 / p-ebony-700
    const signalLine = isDark ? '#A8DBDC' : '#3A8182'    // p-teal-200 / p-teal-600
    const actorLine = isDark ? '#7A7468' : '#A89D87'     // p-ebony-200 / p-stone-500

    mermaid.initialize({
      startOnLoad: false,
      theme: 'base',
      securityLevel: 'loose',
      themeVariables: {
        primaryColor: primary,
        primaryTextColor: '#F5F1E9',  // p-stone-50 (light text on teal bg)
        primaryBorderColor: primary,
        lineColor: signalLine,
        secondaryColor: primary,
        tertiaryColor: surface,
        mainBkg: raised,
        nodeBorder: primary,
        clusterBkg: surface,
        clusterBorder: border,
        defaultLinkColor: signalLine,
        titleColor: text,
        edgeLabelBackground: 'transparent',
        nodeTextColor: text,
        // Sequence diagram specific
        signalColor: signalLine,
        signalTextColor: signalText,
        actorTextColor: text,
        actorLineColor: actorLine,
        activationBorderColor: primary,
        sequenceNumberColor: '#F5F1E9',  // p-stone-50
        labelTextColor: signalText,
        loopTextColor: signalText,
        noteBkgColor: raised,
        noteTextColor: text,
        noteBorderColor: border,
      }
    })

    if (ref.current && chart) {
      // mermaid.render produces trusted SVG from our own chart definitions
      ref.current.textContent = ''
      const id = `mermaid-${Math.random().toString(36).substr(2, 9)}`
      mermaid.render(id, chart).then((result) => {
        if (ref.current) {
          // SVG is generated by mermaid from our own chart prop, not user input
          const wrapper = document.createElement('div')
          wrapper.innerHTML = result.svg // eslint-disable-line no-unsanitized/property
          const svg = wrapper.querySelector('svg')
          if (svg && ref.current) {
            ref.current.textContent = ''
            ref.current.appendChild(svg)
          }
        }
      })
    }
  }, [chart])

  useEffect(() => {
    renderChart()

    // Re-render when theme changes
    const observer = new MutationObserver((mutations) => {
      for (const m of mutations) {
        if (m.attributeName === 'data-theme') {
          renderChart()
          break
        }
      }
    })
    observer.observe(document.documentElement, { attributes: true })
    return () => observer.disconnect()
  }, [renderChart])

  return (
    <Surface
      depth="inset"
      radius="3xl"
      padding="xl"
      className="my-12 flex justify-center"
      ref={ref}
    />
  )
}
