import Foundation

// MARK: - Bundled fixtures
//
// Every fixture in PortDaddy/Resources is checked in, decoded through the same
// Codable types the network path uses, and labelled ON SCREEN wherever it
// drives a view. That last part is the rule that matters: a fixture rendered
// without a label is a mock presented as truth, and the whole point of this
// surface is that it does not do that.
//
// Three of them are different in kind. maritime-signals.fixture.json,
// control-contract.fixture.json and interruptions.fixture.json are GENERATED by
// scripts/generate-pd-ios-fixtures.ts from lib/maritime-signals.ts,
// skills/agent-control-command-contract/examples/sample-input.json, and
// `publicShape()` in apps/relay/src/interruptions.ts plus the
// operator_interruptions column types. They exist to fail CI when the Swift
// ports drift from their canonical sources. Do not hand-edit any of them.
//
// interruptions.fixture.json joined that list after the hand-authored version
// hid a live bug — it claimed `"installationId": "inst_7710"` for an INTEGER
// column, so the Swift test asserted the fixture's claim while the real relay
// response threw and blanked the operator's inbox. A fixture with no generator
// behind it is a second source of truth, and it will eventually be the wrong
// one. It now carries a `shape` block (JSON type + nullability per field, read
// out of the migration) that InterruptionsInboxTests asserts the Codable
// against.

public enum PortDaddyFixture: String, CaseIterable, Sendable {
    case roadmapProjection = "roadmap-projection.fixture"
    case harbors = "harbors.fixture"
    case interruptions = "interruptions.fixture"
    case maritimeSignals = "maritime-signals.fixture"
    case controlContract = "control-contract.fixture"
}

public enum FixtureError: Error, CustomStringConvertible {
    case missing(String)
    case unreadable(String, String)

    public var description: String {
        switch self {
        case .missing(let name):
            return "fixture \(name).json is not in the resource bundle"
        case .unreadable(let name, let reason):
            return "fixture \(name).json could not be decoded: \(reason)"
        }
    }
}

public enum PortDaddyFixtures {

    public static func data(_ fixture: PortDaddyFixture) throws -> Data {
        guard let url = Bundle.module.url(forResource: fixture.rawValue, withExtension: "json") else {
            throw FixtureError.missing(fixture.rawValue)
        }
        return try Data(contentsOf: url)
    }

    public static func decode<T: Decodable>(_ type: T.Type, from fixture: PortDaddyFixture) throws -> T {
        let raw = try data(fixture)
        do {
            return try JSONDecoder().decode(type, from: raw)
        } catch {
            throw FixtureError.unreadable(fixture.rawValue, String(describing: error))
        }
    }

    /// A JSON object, for the parity test, which compares against the raw
    /// TypeScript output rather than through a Swift type.
    public static func object(_ fixture: PortDaddyFixture) throws -> [String: Any] {
        let raw = try data(fixture)
        guard let object = try JSONSerialization.jsonObject(with: raw) as? [String: Any] else {
            throw FixtureError.unreadable(fixture.rawValue, "top level is not an object")
        }
        return object
    }

    // MARK: - Typed accessors used by previews

    public static func roadmapProjection() throws -> RoadmapProjection {
        try decode(RoadmapProjection.self, from: .roadmapProjection)
    }

    public static func harbors() throws -> HarborFixture {
        try decode(HarborFixture.self, from: .harbors)
    }

    public static func interruptions() throws -> InterruptionListResponse {
        try decode(InterruptionListResponse.self, from: .interruptions)
    }
}

/// The harbors fixture: a harbor, its membership, and a presence snapshot —
/// or no snapshot at all, which is the `unknown` verdict's input and the case
/// most worth having in a fixture.
public struct HarborFixtureEntry: Codable, Sendable {
    public let harbor: Harbor
    public let members: [HarborMember]
    public let presence: PresenceSnapshot?

    public var daemonMemberCount: Int { members.filter(\.isDaemon).count }

    public var reachability: ReachabilityReading {
        Reachability.derive(totalDaemonMembers: daemonMemberCount, presence: presence)
    }
}

public struct HarborFixture: Codable, Sendable {
    public let note: String?
    public let entries: [HarborFixtureEntry]
}
