/**
 * pd hooks install — Per-project, daemon-gated coordination hooks for agent CLIs
 *
 * Wires the Giant Squid Harness tentacles into the INTERACTIVE sessions of the
 * agent CLIs on this machine (Claude Code, Codex, Gemini, Antigravity/agy). The
 * hook SHAPES come from one shared source of truth — lib/squid/hook-shape.ts —
 * which the squid headless adapter uses too, so the interactive and headless
 * injectors can never drift.
 *
 * Two guarantees the user asked for:
 *   1. PER PROJECT. Claude/Gemini get project-level config written into the repo
 *      (`<repo>/.claude/settings.json`, `<repo>/.gemini/settings.json`). Codex
 *      (repo-local hooks don't fire interactively — openai/codex#17532) and agy
 *      (home-scoped `~/.gemini/hooks.json`) must be user-level, so they are
 *      constrained at RUNTIME by the gate below.
 *   2. INERT UNTIL PORT DADDY IS READY. Every hook command points at a gate
 *      wrapper, not the tentacle directly. The wrapper no-ops (allow / no
 *      context) unless (a) the pd daemon's ready lease matches its live PID,
 *      (b) its heartbeat is fresh, AND (c) the cwd is inside an explicitly
 *      armed pd project. Hooks therefore never pile onto a daemon that is down
 *      or still behind its database-integrity boot gate.
 *
 * Layout under ~/.port-daddy/bin/:
 *   squid/pd-hook-{prompt,pre-tool,post-tool}   <- the real tentacles (copied)
 *   pd-hook-{prompt,pre-tool,post-tool}         <- generated gate wrappers
 * Hook configs point at the gate wrappers.
 *
 * Usage:
 *   pd hooks install            # wire detected CLIs for THIS project (+gated user cfg)
 *   pd hooks install --user     # also write user-level config for claude/gemini
 *   pd hooks list               # detection + wiring status
 *   pd hooks uninstall          # remove Port Daddy hooks from every surface
 */

import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  copyFileSync,
  chmodSync,
  realpathSync,
  renameSync,
  rmSync,
} from 'node:fs';
import { basename, join, dirname, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import * as ui from '../utils/ui.js';
import { PD_HOME } from '../../shared/paths.js';
import {
  TENTACLES,
  type TentacleName,
  type TentacleResolver,
  PD_HOOK_MARKER,
  CODEX_PD_MARKER,
  SQUID_HOOK_DEADLINE_MS,
  buildJsonHookMap,
  codexHooksTomlBlock,
  upsertJsonHookMap,
  removeJsonHooks,
  stripCodexHooksTomlBlock,
} from '../../lib/squid/hook-shape.js';
import {
  SQUID_HOOK_BREAKER_COOLDOWN_MS,
  SQUID_HOOK_BREAKER_FAILURE_THRESHOLD,
  SQUID_HOOK_BREAKER_PROBE_CLOCK_SKEW_SECONDS,
  SQUID_HOOK_BREAKER_PROBE_STALE_SECONDS,
  SQUID_HOOK_BREAKER_SLOW_MS,
  SQUID_HOOK_DEBUG_MAX_BYTES,
  SQUID_HOOK_DEBUG_TRIM_BYTES,
  resetSquidHookHealth,
} from '../../lib/squid/debug.js';
import { resolveSquidAsset } from '../../lib/squid/assets.js';

const DEFAULT_HOME = process.env.HOME || process.env.USERPROFILE || '';
const SQUID_DAEMON_HEARTBEAT_STALE_SECONDS = 30;

/** ~/.port-daddy/bin — staged gate wrappers (what hook configs point at). */
export function tentacleBinDir(): string {
  return join(PD_HOME, 'bin');
}
/** ~/.port-daddy/bin/squid — the real tentacles the wrappers delegate to. */
function realTentacleDir(): string {
  return join(PD_HOME, 'bin', 'squid');
}
/** The gate-wrapper path a hook config invokes for a given tentacle. */
function gatePath(name: TentacleName): string {
  return join(tentacleBinDir(), name);
}

// ─── Gate wrapper (pd-ready + per-project) ───────────────────────────────────

/**
 * The shell gate. It runs on every tool call, so it is filesystem-only and
 * spawns no `pd` process. It allows/no-ops (exit 0) unless the ready generation
 * matches the daemon PID, the heartbeat is fresh, and the cwd is inside an
 * explicitly armed pd project, then execs the real tentacle with stdin/argv
 * intact.
 *
 * Do not use `kill -0` or `ps` here. Codex's macOS Seatbelt profile denies both
 * against the Homebrew daemon even though it is owned by the same user, which
 * made every Codex hook silently fail open. The Bosun heartbeat is specifically
 * designed as the filesystem-only liveness contract for sandboxed observers.
 */
function gateWrapperScript(): string {
  return [
    '#!/bin/sh',
    '# Port Daddy hook gate — GENERATED by `pd hooks install`. Do not edit.',
    '# Makes coordination hooks per-project and inert until the daemon is ready.',
    'PD_HOME="${PD_HOME:-$HOME/.port-daddy}"',
    '',
    '# Opt-in, sanitized timing trace. The event format has no field for stdin,',
    '# argv, environment snapshots, prompt text, tool input/result, stdout, or stderr.',
    'pd_debug=0',
    'pd_debug_dir="$PD_HOME/squid"',
    'pd_debug_log="$pd_debug_dir/hook-events.log"',
    'pd_debug_lock="$pd_debug_dir/debug-write.lock"',
    'pd_hook="${0##*/}"',
    '# Interactive PostToolUse was retired. A running provider may retain its old',
    '# command until restart, so keep the stable shim as a zero-work tombstone.',
    '[ "$pd_hook" = "pd-hook-post-tool" ] && exit 0',
    'case "$pd_hook" in',
    '  pd-hook-prompt) pd_phase=turn ;;',
    '  pd-hook-pre-tool) pd_phase=edit ;;',
    '  pd-hook-post-tool) pd_phase=trace ;;',
    '  pd-hook-stop) pd_phase=close ;;',
    '  *) pd_phase=turn ;;',
    'esac',
    'pd_provider="${PD_HOOK_PROVIDER:-unknown}"',
    'case "$pd_provider" in claude|codex|gemini|agy) ;; *) pd_provider=unknown ;; esac',
    `pd_deadline_ms="${'${PD_HOOK_DEADLINE_MS:-'}${SQUID_HOOK_DEADLINE_MS}}"`,
    `case "$pd_deadline_ms" in ""|*[!0-9]*) pd_deadline_ms=${SQUID_HOOK_DEADLINE_MS} ;; esac`,
    `if [ "$pd_deadline_ms" -le 0 ] 2>/dev/null || [ "$pd_deadline_ms" -gt ${SQUID_HOOK_DEADLINE_MS} ] 2>/dev/null; then pd_deadline_ms=${SQUID_HOOK_DEADLINE_MS}; fi`,
    `pd_failure_threshold="${'${PD_HOOK_FAILURE_THRESHOLD:-'}${SQUID_HOOK_BREAKER_FAILURE_THRESHOLD}}"`,
    `case "$pd_failure_threshold" in ""|*[!0-9]*) pd_failure_threshold=${SQUID_HOOK_BREAKER_FAILURE_THRESHOLD} ;; esac`,
    `pd_slow_ms="${'${PD_HOOK_SLOW_MS:-'}${SQUID_HOOK_BREAKER_SLOW_MS}}"`,
    `case "$pd_slow_ms" in ""|*[!0-9]*) pd_slow_ms=${SQUID_HOOK_BREAKER_SLOW_MS} ;; esac`,
    `pd_cooldown_ms="${'${PD_HOOK_BREAKER_COOLDOWN_MS:-'}${SQUID_HOOK_BREAKER_COOLDOWN_MS}}"`,
    `case "$pd_cooldown_ms" in ""|*[!0-9]*) pd_cooldown_ms=${SQUID_HOOK_BREAKER_COOLDOWN_MS} ;; esac`,
    `[ "$pd_failure_threshold" -gt 0 ] 2>/dev/null || pd_failure_threshold=${SQUID_HOOK_BREAKER_FAILURE_THRESHOLD}`,
    `[ "$pd_slow_ms" -gt 0 ] 2>/dev/null || pd_slow_ms=${SQUID_HOOK_BREAKER_SLOW_MS}`,
    `[ "$pd_cooldown_ms" -gt 0 ] 2>/dev/null || pd_cooldown_ms=${SQUID_HOOK_BREAKER_COOLDOWN_MS}`,
    '# Hard byte budget on the debug-mode session-id probe (review finding 1,',
    '# 2026-08-24): debug mode used to capture the ENTIRE hook stdin into a shell',
    '# variable just to label the sanitized timing event with a session id, then',
    '# piped that whole captured copy into the real tentacle — which itself',
    '# captures it AGAIN. That is multiple full unbounded in-memory copies of a',
    '# payload that can carry a huge final-assistant-message. Only a BOUNDED',
    '# prefix is ever captured now; the remainder streams straight through to the',
    '# real hook via `cat`, never buffered here. 256 KiB comfortably contains any',
    '# realistic session/thread id (vendors emit it near the top of the JSON',
    '# object) — a payload larger than that simply falls back to $PPID for the',
    '# debug label (same fallback already used when the id field is absent or',
    '# unparsable), never to a second unbounded capture.',
    `pd_debug_probe_bytes="${'${PD_HOOK_DEBUG_INPUT_BUDGET_BYTES:-'}262144}"`,
    'case "$pd_debug_probe_bytes" in ""|*[!0-9]*) pd_debug_probe_bytes=262144 ;; esac',
    '',
    'pd_debug_now_ms() {',
    '  if [ -x /usr/bin/perl ]; then',
    '    /usr/bin/perl -MTime::HiRes=time -e \'printf "%.0f", time * 1000\'',
    '  else',
    '    printf "%s000" "$(date +%s)"',
    '  fi',
    '}',
    'pd_epoch_ms() {',
    '  printf "%s000" "$(date +%s)"',
    '}',
    'pd_debug_lock_acquire() {',
    '  pd_attempt=0',
    '  while ! mkdir "$pd_debug_lock" 2>/dev/null; do',
    '    pd_attempt=$((pd_attempt + 1))',
    '    pd_lock_now=$(date +%s 2>/dev/null || printf 0)',
    '    pd_lock_modified=$(stat -f %m "$pd_debug_lock" 2>/dev/null || true)',
    '    case "$pd_lock_modified" in ""|*[!0-9]*) pd_lock_modified=$(stat -c %Y "$pd_debug_lock" 2>/dev/null || true) ;; esac',
    '    case "$pd_lock_now:$pd_lock_modified" in *[!0-9:]*) ;; *) [ $((pd_lock_now - pd_lock_modified)) -gt 5 ] 2>/dev/null && rmdir "$pd_debug_lock" 2>/dev/null ;; esac',
    '    [ "$pd_attempt" -lt 20 ] || return 1',
    '    sleep 0.01',
    '  done',
    '}',
    'pd_debug_append() {',
    '  [ "$pd_debug" -eq 1 ] || return 0',
    '  umask 077',
    '  mkdir -p "$pd_debug_dir" 2>/dev/null || return 0',
    '  pd_debug_lock_acquire || return 0',
    '  printf "v1\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n" "$1" "$pd_run_id" "$pd_session_id" "$pd_provider" "$pd_phase" "$pd_hook" "$2" "$pd_deadline_ms" "$3" "$4" "$pd_workspace_b64" >> "$pd_debug_log" 2>/dev/null || true',
    '  pd_size=$(wc -c < "$pd_debug_log" 2>/dev/null | tr -d "[:space:]" || printf 0)',
    `  case "$pd_size" in ""|*[!0-9]*) ;; *) [ "$pd_size" -le ${SQUID_HOOK_DEBUG_MAX_BYTES} ] || tail -c ${SQUID_HOOK_DEBUG_TRIM_BYTES} "$pd_debug_log" 2>/dev/null | sed "1d" > "$pd_debug_log.trim" 2>/dev/null ;; esac`,
    '  [ -f "$pd_debug_log.trim" ] && chmod 600 "$pd_debug_log.trim" 2>/dev/null && mv "$pd_debug_log.trim" "$pd_debug_log" 2>/dev/null',
    '  rm -f "$pd_debug_log.trim" 2>/dev/null || true',
    '  rmdir "$pd_debug_lock" 2>/dev/null || true',
    '}',
    'pd_debug_finish() {',
    '  [ "$pd_debug" -eq 1 ] || return 0',
    '  pd_finished_ms=$(pd_debug_now_ms 2>/dev/null) || return 0',
    '  pd_debug_append finish "$pd_finished_ms" "$1" "$2"',
    '}',
    'pd_debug_skip() {',
    '  pd_debug_finish "$1" 0',
    '  exit 0',
    '}',
    '',
    '# Fail-open circuit breaker. The state format is intentionally tiny and',
    '# sanitized: lifecycle state and timing only, never hook input or output.',
    'pd_health_dir="$PD_HOME/squid/health"',
    'pd_state_file="$pd_health_dir/$pd_hook.state"',
    'pd_probe_dir="$pd_health_dir/$pd_hook.probe"',
    'pd_state_lock="$pd_health_dir/$pd_hook.state.lock"',
    'pd_failure_receipt_dir="$pd_health_dir/$pd_hook.failures"',
    'pd_notice_file="$pd_health_dir/remediation.notice"',
    'pd_breaker_state=closed',
    'pd_failure_count=0',
    'pd_opened_ms=0',
    'pd_retry_ms=0',
    'pd_last_reason=none',
    'pd_last_duration_ms=0',
    'pd_last_exit=-',
    'pd_updated_ms=0',
    'pd_is_probe=0',
    'pd_timer_missing=0',
    'pd_receipt_seen=0',
    'pd_receipt_count=0',
    'pd_time_bin="${PD_HOOK_TIME_BIN:-/usr/bin/time}"',
    'case "$pd_time_bin" in /*) ;; *) pd_time_bin=/usr/bin/time ;; esac',
    'pd_deadline_perl_bin="${PD_HOOK_PERL_BIN:-/usr/bin/perl}"',
    'case "$pd_deadline_perl_bin" in /*) ;; *) pd_deadline_perl_bin=/usr/bin/perl ;; esac',
    'pd_time_file="$pd_health_dir/$pd_hook.time.$$"',
    'pd_child_done_file="$pd_health_dir/$pd_hook.child-done.$$"',
    'pd_child_pid_file="$pd_health_dir/$pd_hook.child-pid.$$"',
    'pd_deadline_file="$pd_health_dir/$pd_hook.deadline.$$"',
    'pd_deadline_watch_pid=""',
    'pd_health_receipt_count() {',
    '  pd_receipt_count=0',
    '  for pd_receipt in "$pd_failure_receipt_dir"/*.failure; do',
    '    [ -d "$pd_receipt" ] || continue',
    '    pd_receipt_count=$((pd_receipt_count + 1))',
    '  done',
    '}',
    'pd_health_receipt_write() {',
    '  umask 077',
    '  mkdir -p "$pd_failure_receipt_dir" 2>/dev/null || return 1',
    '  mkdir "$pd_failure_receipt_dir/$pd_health_now-$$.failure" 2>/dev/null',
    '}',
    'pd_health_receipt_clear() {',
    '  for pd_receipt in "$pd_failure_receipt_dir"/*.failure; do',
    '    [ -d "$pd_receipt" ] || continue',
    '    rmdir "$pd_receipt" 2>/dev/null || true',
    '  done',
    '  rmdir "$pd_failure_receipt_dir" 2>/dev/null || true',
    '}',
    'pd_health_load_state() {',
    '  [ -f "$pd_state_file" ] || return 0',
    '  IFS="$(printf "\\t")" read -r pd_version pd_loaded_state pd_loaded_failures pd_loaded_opened pd_loaded_retry pd_loaded_reason pd_loaded_duration pd_loaded_exit pd_loaded_updated pd_loaded_receipt_seen < "$pd_state_file" 2>/dev/null || return 0',
    '  case "$pd_version" in v1) pd_loaded_receipt_seen=0 ;; v2) ;; *) return 0 ;; esac',
    '  case "$pd_loaded_state" in closed|open) ;; *) return 0 ;; esac',
    '  case "$pd_loaded_failures:$pd_loaded_opened:$pd_loaded_retry:$pd_loaded_duration:$pd_loaded_updated:$pd_loaded_receipt_seen" in *[!0-9:]*) return 0 ;; esac',
    '  case "$pd_loaded_reason" in ""|*[!a-z0-9_-]*) return 0 ;; esac',
    '  case "$pd_loaded_exit" in -|[0-9]|[0-9][0-9]|[0-9][0-9][0-9]) ;; *) return 0 ;; esac',
    '  pd_breaker_state=$pd_loaded_state',
    '  pd_failure_count=$pd_loaded_failures',
    '  pd_opened_ms=$pd_loaded_opened',
    '  pd_retry_ms=$pd_loaded_retry',
    '  pd_last_reason=$pd_loaded_reason',
    '  pd_last_duration_ms=$pd_loaded_duration',
    '  pd_last_exit=$pd_loaded_exit',
    '  pd_updated_ms=$pd_loaded_updated',
    '  pd_receipt_seen=$pd_loaded_receipt_seen',
    '}',
    'pd_health_load() {',
    '  pd_breaker_state=closed',
    '  pd_failure_count=0',
    '  pd_opened_ms=0',
    '  pd_retry_ms=0',
    '  pd_last_reason=none',
    '  pd_last_duration_ms=0',
    '  pd_last_exit=-',
    '  pd_updated_ms=0',
    '  pd_receipt_seen=0',
    '  pd_health_load_state',
    '  pd_health_receipt_count',
    '  if [ "$pd_receipt_count" -gt "$pd_receipt_seen" ] 2>/dev/null; then',
    '    pd_failure_count=$((pd_failure_count + pd_receipt_count - pd_receipt_seen))',
    '  fi',
    '}',
    'pd_health_write() {',
    '  umask 077',
    '  mkdir -p "$pd_health_dir" 2>/dev/null || return 1',
    '  pd_state_tmp="$pd_state_file.$$"',
    '  printf "v2\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$pd_receipt_count" > "$pd_state_tmp" 2>/dev/null || return 1',
    '  chmod 600 "$pd_state_tmp" 2>/dev/null || true',
    '  mv "$pd_state_tmp" "$pd_state_file" 2>/dev/null || { rm -f "$pd_state_tmp" 2>/dev/null || true; return 1; }',
    '}',
    'pd_health_state_lock_acquire() {',
    '  pd_lock_attempt=0',
    '  while ! mkdir "$pd_state_lock" 2>/dev/null; do',
    '    pd_lock_attempt=$((pd_lock_attempt + 1))',
    '    pd_state_lock_now=$(date +%s 2>/dev/null || printf 0)',
    '    pd_state_lock_modified=$(stat -f %m "$pd_state_lock" 2>/dev/null || true)',
    '    case "$pd_state_lock_modified" in ""|*[!0-9]*) pd_state_lock_modified=$(stat -c %Y "$pd_state_lock" 2>/dev/null || true) ;; esac',
    '    case "$pd_state_lock_now:$pd_state_lock_modified" in *[!0-9:]*) ;; *) [ $((pd_state_lock_now - pd_state_lock_modified)) -gt 5 ] 2>/dev/null && rmdir "$pd_state_lock" 2>/dev/null ;; esac',
    '    [ "$pd_lock_attempt" -lt 20 ] || return 1',
    '    sleep 0.01',
    '  done',
    '}',
    'pd_health_state_lock_release() {',
    '  rmdir "$pd_state_lock" 2>/dev/null || true',
    '}',
    'pd_health_notice_open() {',
    '  case "$pd_hook" in pd-hook-prompt) pd_hook_label="PD TURN" ;; pd-hook-pre-tool) pd_hook_label="PD EDIT" ;; pd-hook-stop) pd_hook_label="PD CLOSE" ;; *) pd_hook_label="PD TRACE" ;; esac',
    '  umask 077',
    '  mkdir -p "$pd_health_dir" 2>/dev/null || return 0',
    '  pd_notice_tmp="$pd_notice_file.$$"',
    '  printf "◆ PD SAFE MODE · %s disabled after %s consecutive failed or slow calls. Open FleetBar > Giant Squid > Repair.\\n" "$pd_hook_label" "$pd_failure_count" > "$pd_notice_tmp" 2>/dev/null || return 0',
    '  chmod 600 "$pd_notice_tmp" 2>/dev/null || true',
    '  mv "$pd_notice_tmp" "$pd_notice_file" 2>/dev/null || rm -f "$pd_notice_tmp" 2>/dev/null || true',
    '}',
    'pd_health_notice_emit() {',
    '  [ "$pd_hook" = pd-hook-prompt ] || return 0',
    '  [ -f "$pd_notice_file" ] || return 0',
    '  pd_notice_claim="$pd_notice_file.emit.$$"',
    '  mv "$pd_notice_file" "$pd_notice_claim" 2>/dev/null || return 0',
    '  cat "$pd_notice_claim" 2>/dev/null || true',
    '  rm -f "$pd_notice_claim" 2>/dev/null || true',
    '}',
    'pd_health_record_unhealthy() {',
    '  pd_reason=$1',
    '  pd_exit_value=$2',
    '  pd_duration_value=$3',
    '  pd_health_now=$(pd_epoch_ms 2>/dev/null) || pd_health_now=0',
    '  pd_receipt_recorded=0',
    '  pd_health_receipt_write && pd_receipt_recorded=1',
    '  pd_health_state_lock_acquire || return 0',
    '  pd_health_load',
    '  pd_was_open=$pd_breaker_state',
    '  [ "$pd_receipt_recorded" -eq 1 ] || pd_failure_count=$((pd_failure_count + 1))',
    '  if [ "$pd_is_probe" -eq 1 ] || [ "$pd_failure_count" -ge "$pd_failure_threshold" ]; then',
    '    pd_breaker_state=open',
    '    pd_opened_ms=$pd_health_now',
    '    pd_retry_ms=$((pd_health_now + pd_cooldown_ms))',
    '    if pd_health_write open "$pd_failure_count" "$pd_opened_ms" "$pd_retry_ms" "$pd_reason" "$pd_duration_value" "$pd_exit_value" "$pd_health_now"; then',
    '      rmdir "$pd_probe_dir" 2>/dev/null || true',
    '      [ "$pd_was_open" = open ] || pd_health_notice_open',
    '    fi',
    '  else',
    '    pd_health_write closed "$pd_failure_count" 0 0 "$pd_reason" "$pd_duration_value" "$pd_exit_value" "$pd_health_now"',
    '  fi',
    '  pd_health_state_lock_release',
    '}',
    'pd_health_record_healthy() {',
    '  if [ -f "$pd_state_file" ] || [ -d "$pd_probe_dir" ] || [ -d "$pd_failure_receipt_dir" ]; then',
    '    pd_health_state_lock_acquire || return 0',
    '    rm -f "$pd_state_file" 2>/dev/null || true',
    '    rmdir "$pd_probe_dir" 2>/dev/null || true',
    '    pd_health_receipt_clear',
    '    rm -f "$pd_notice_file" 2>/dev/null || true',
    '    pd_health_state_lock_release',
    '  fi',
    '}',
    'pd_health_probe_acquire() {',
    '  # Half-open recovery is rare, so serialize the complete stale-marker',
    '  # decision. Without this lock, two callers can both inspect the old',
    '  # marker and the loser can remove the winner\'s newly-created marker',
    '  # (an ABA race), allowing two recovery probes to run concurrently.',
    '  pd_health_state_lock_acquire || return 1',
    '  pd_health_load',
    '  pd_probe_now_ms=$(pd_epoch_ms 2>/dev/null) || pd_probe_now_ms=0',
    '  if [ "$pd_breaker_state" != open ] || [ "$pd_probe_now_ms" -lt "$pd_retry_ms" ] 2>/dev/null; then',
    '    pd_health_state_lock_release',
    '    return 1',
    '  fi',
    '  if mkdir "$pd_probe_dir" 2>/dev/null; then',
    '    pd_health_state_lock_release',
    '    return 0',
    '  fi',
    '  pd_probe_now=$(date +%s 2>/dev/null || printf 0)',
    '  pd_probe_modified=$(stat -f %m "$pd_probe_dir" 2>/dev/null || true)',
    '  case "$pd_probe_modified" in ""|*[!0-9]*) pd_probe_modified=$(stat -c %Y "$pd_probe_dir" 2>/dev/null || true) ;; esac',
    '  case "$pd_probe_now:$pd_probe_modified" in *[!0-9:]*) pd_health_state_lock_release; return 1 ;; esac',
    '  pd_probe_age=$((pd_probe_now - pd_probe_modified))',
    `  if [ "$pd_probe_age" -lt -${SQUID_HOOK_BREAKER_PROBE_CLOCK_SKEW_SECONDS} ] 2>/dev/null; then pd_health_state_lock_release; return 1; fi`,
    `  if [ "$pd_probe_age" -le ${SQUID_HOOK_BREAKER_PROBE_STALE_SECONDS} ] 2>/dev/null; then pd_health_state_lock_release; return 1; fi`,
    '  rmdir "$pd_probe_dir" 2>/dev/null || { pd_health_state_lock_release; return 1; }',
    '  mkdir "$pd_probe_dir" 2>/dev/null',
    '  pd_probe_acquired=$?',
    '  pd_health_state_lock_release',
    '  return "$pd_probe_acquired"',
    '}',
    'pd_health_duration_read() {',
    '  pd_duration_ms=0',
    '  pd_elapsed=',
    '  while IFS=" " read -r pd_time_kind pd_time_value; do',
    '    if [ "$pd_time_kind" = real ]; then pd_elapsed=$pd_time_value; break; fi',
    '  done < "$pd_time_file" 2>/dev/null || true',
    '  rm -f "$pd_time_file" 2>/dev/null || true',
    '  case "$pd_elapsed" in',
    '    [0-9]*.[0-9][0-9])',
    '      pd_seconds=${pd_elapsed%.*}',
    '      pd_hundredths=${pd_elapsed#*.}',
    '      case "$pd_seconds:$pd_hundredths" in *[!0-9:]*) return 0 ;; esac',
    '      pd_seconds=${pd_seconds#0}; [ -n "$pd_seconds" ] || pd_seconds=0',
    '      pd_hundredths=${pd_hundredths#0}; [ -n "$pd_hundredths" ] || pd_hundredths=0',
    '      pd_duration_ms=$((pd_seconds * 1000 + pd_hundredths * 10))',
    '      ;;',
    '  esac',
    '}',
    '# pd_health_signal (the wrapper-level signal trap) and pd_kill_child (the',
    '# child-cleanup helper it and the deadline watchdog share) are defined',
    '# further down, right beside the trap that installs them.',
    'if [ -f "$pd_debug_dir/debug.enabled" ]; then',
    '  pd_debug=1',
    '  pd_started_ms=$(pd_debug_now_ms 2>/dev/null) || pd_started_ms="$(date +%s)000"',
    '  # Debug mode buffers only a BOUNDED prefix of hook stdin in memory (review',
    '  # finding 1) — just enough to discover a session identifier for the',
    '  # sanitized timing label. head -c physically stops reading at the budget;',
    '  # the real tentacle below still receives the FULL original stream, because',
    '  # this prefix is streamed back out ahead of a `cat` continuation rather',
    '  # than re-captured. Only a validated session identifier ever leaves this',
    '  # bounded buffer.',
    '  pd_input_head=$(head -c "$pd_debug_probe_bytes" 2>/dev/null)',
    '  pd_session_candidate=""',
    '  if [ -x /usr/bin/perl ]; then',
    '    pd_session_candidate=$(printf "%s" "$pd_input_head" | /usr/bin/perl -MJSON::PP -0777 -e \'eval { my $d = decode_json(<>); my $v = $d->{session_id} // $d->{sessionId} // $d->{thread_id} // $d->{threadId} // $d->{conversationId}; print $v if defined($v) && !ref($v); };\' 2>/dev/null || true)',
    '  fi',
    '  case "$pd_session_candidate" in ""|*[!A-Za-z0-9._:-]*|?????????????????????????????????????????????????????????????????????????????????*) pd_session_candidate="$PPID" ;; esac',
    '  pd_session_id="${pd_provider}:${pd_session_candidate}"',
    '  pd_run_id="${pd_provider}-${pd_phase}-${PPID}-$$-${pd_started_ms}"',
    '  pd_workspace_b64=$(printf "%s" "$PWD" | base64 2>/dev/null | tr -d "\\r\\n")',
    '  pd_debug_append start "$pd_started_ms" - -',
    'fi',
    '',
    '# (a-b) prove the selected daemon is ready without coupling a remote peer',
    '# to this machine\'s ready/pid/heartbeat files. An explicit remote URL is',
    '# authoritative for transport selection, but only a bounded /health probe',
    '# makes hooks live; a failed probe remains a silent, fail-open no-op.',
    'pd_remote_url="${PD_URL:-${PORT_DADDY_URL:-}}"',
    'if [ -n "$pd_remote_url" ]; then',
    '  case "$pd_remote_url" in http://*|https://*) ;; *) pd_debug_skip remote_url_invalid ;; esac',
    '  pd_curl=$(command -v curl 2>/dev/null || true)',
    '  [ -n "$pd_curl" ] || pd_debug_skip remote_probe_unavailable',
    '  pd_remote_health="${pd_remote_url%/}/health"',
    '  "$pd_curl" --fail --silent --output /dev/null --connect-timeout 1 --max-time 1 "$pd_remote_health" 2>/dev/null || pd_debug_skip remote_unreachable',
    'else',
    '  # The heartbeat starts before the database-integrity boot gate, so',
    '  # liveness alone must never delegate hooks to a local daemon.',
    '  ready_file="${PORT_DADDY_READY_FILE:-$PD_HOME/daemon.ready}"',
    '  pid_file="${PORT_DADDY_PID_FILE:-$PD_HOME/daemon.pid}"',
    '  [ ! -L "$ready_file" ] || pd_debug_skip ready_symlink',
    '  [ ! -L "$pid_file" ] || pd_debug_skip pid_symlink',
    '  [ -f "$ready_file" ] || pd_debug_skip daemon_booting',
    '  [ -f "$pid_file" ] || pd_debug_skip pid_missing',
    '  ready_pid=',
    '  daemon_pid=',
    '  { IFS= read -r ready_pid || [ -n "$ready_pid" ]; } < "$ready_file" 2>/dev/null || pd_debug_skip ready_unreadable',
    '  { IFS= read -r daemon_pid || [ -n "$daemon_pid" ]; } < "$pid_file" 2>/dev/null || pd_debug_skip pid_unreadable',
    '  case "$ready_pid:$daemon_pid" in *[!0-9:]*) pd_debug_skip generation_invalid ;; esac',
    '  [ "$ready_pid" -gt 0 ] 2>/dev/null || pd_debug_skip generation_invalid',
    '  [ "$daemon_pid" -gt 0 ] 2>/dev/null || pd_debug_skip generation_invalid',
    '  [ "$ready_pid" = "$daemon_pid" ] || pd_debug_skip generation_mismatch',
    '  # Local liveness uses the Bosun heartbeat; process probes are sandbox-denied.',
    '  heartbeat="${PORT_DADDY_HEARTBEAT_FILE:-$PD_HOME/heartbeat}"',
    '  [ ! -L "$heartbeat" ] || pd_debug_skip heartbeat_symlink',
    '  [ -f "$heartbeat" ] || pd_debug_skip heartbeat_missing',
    '  now=$(date +%s 2>/dev/null) || pd_debug_skip heartbeat_unreadable',
    '  modified=$(stat -f %m "$heartbeat" 2>/dev/null || true)',
    '  case "$modified" in ""|*[!0-9]*) modified=$(stat -c %Y "$heartbeat" 2>/dev/null || true) ;; esac',
    '  case "$modified" in ""|*[!0-9]*) pd_debug_skip heartbeat_unreadable ;; esac',
    '  age=$((now - modified))',
    `  [ "$age" -ge -${SQUID_DAEMON_HEARTBEAT_STALE_SECONDS} ] 2>/dev/null || pd_debug_skip daemon_stale`,
    `  [ "$age" -le ${SQUID_DAEMON_HEARTBEAT_STALE_SECONDS} ] 2>/dev/null || pd_debug_skip daemon_stale`,
    'fi',
    '# (c) cwd inside a project explicitly armed by `pd squid on`?',
    'd=$PWD',
    'while [ -n "$d" ] && [ "$d" != "/" ]; do',
    '  if [ -d "$d/.portdaddy" ]; then',
    '    project_root=$(cd "$d" 2>/dev/null && pwd -P) || pd_debug_skip project_unreadable',
    '    registry="$PD_HOME/squid/projects"',
    '    [ -f "$registry" ] || pd_debug_skip registry_missing',
    '    pd_project_armed=0',
    '    while IFS= read -r pd_registered_project; do',
    '      if [ "$pd_registered_project" = "$project_root" ]; then pd_project_armed=1; break; fi',
    '    done < "$registry" 2>/dev/null || true',
    '    [ "$pd_project_armed" -eq 1 ] || pd_debug_skip project_disarmed',
    '    pd_health_load',
    '    pd_health_notice_emit',
    '    if [ "$pd_breaker_state" = open ]; then',
    '      pd_health_now=$(pd_epoch_ms 2>/dev/null) || pd_health_now=0',
    '      [ "$pd_health_now" -ge "$pd_retry_ms" ] 2>/dev/null || pd_debug_skip circuit_open',
    '      mkdir -p "$pd_health_dir" 2>/dev/null || pd_debug_skip circuit_open',
    '      pd_health_probe_acquire || pd_debug_skip half_open_busy',
    '      pd_is_probe=1',
    '    fi',
    '    [ -d "$pd_health_dir" ] || mkdir -p "$pd_health_dir" 2>/dev/null || true',
    '    rm -f "$pd_child_done_file" "$pd_child_pid_file" "$pd_deadline_file" 2>/dev/null || true',
    '    # Best-effort targeted kill of a backgrounded child (finding 2, review',
    '    # 2026-08-24). Detection and liveness are FILESYSTEM-ONLY throughout —',
    '    # never a bare signal-0 existence probe or a process listing — because',
    '    # Codex\'s macOS Seatbelt profile denies both against a process outside',
    '    # the sandboxed process\'s own creation, the same constraint the daemon',
    '    # heartbeat check above already works around. This signals the CHILD of',
    '    # the timer process ($1), not the timer itself: killing the timer',
    '    # directly reparents its child to init before we can ever reach it,',
    '    # orphaning a hung tentacle instead of stopping it. pkill -P keeps the',
    '    # timer alive so it can still notice its own child die and exit on its',
    '    # own, which is what actually makes the sentinel file ($2) appear. Falls',
    '    # back to signaling the timer pid directly when pkill is unavailable',
    '    # (degrades to the same best-effort',
    '    # behavior this wrapper always had, never worse).',
    '    pd_kill_child() {',
    '      pd_kt="$1"',
    '      pd_sentinel="$2"',
    '      [ -n "$pd_kt" ] || return 0',
    '      if command -v pkill >/dev/null 2>&1; then pkill -TERM -P "$pd_kt" 2>/dev/null || true',
    '      else kill -TERM "$pd_kt" 2>/dev/null || true; fi',
    '      pd_kw=0',
    '      while [ "$pd_kw" -lt 15 ] && [ ! -f "$pd_sentinel" ]; do sleep 0.02 2>/dev/null; pd_kw=$((pd_kw + 1)); done',
    '      if [ ! -f "$pd_sentinel" ]; then',
    '        if command -v pkill >/dev/null 2>&1; then pkill -KILL -P "$pd_kt" 2>/dev/null || true; fi',
    '        kill -KILL "$pd_kt" 2>/dev/null || true',
    '        pd_kw=0',
    '        while [ "$pd_kw" -lt 15 ] && [ ! -f "$pd_sentinel" ]; do sleep 0.02 2>/dev/null; pd_kw=$((pd_kw + 1)); done',
    '      fi',
    '    }',
    '    pd_deadline_watch() {',
    '      pd_dw_ms="$1"',
    '      pd_dw_done="$2"',
    '      pd_dw_deadline="$3"',
    '      if [ -x "$pd_deadline_perl_bin" ]; then',
    '        exec "$pd_deadline_perl_bin" -MTime::HiRes=clock_gettime,sleep,CLOCK_MONOTONIC -e \'my ($ms, $done, $deadline) = @ARGV; my $end = clock_gettime(CLOCK_MONOTONIC) + ($ms / 1000); while (!-e $done) { my $left = $end - clock_gettime(CLOCK_MONOTONIC); last if $left <= 0; sleep($left < 0.01 ? $left : 0.01); } exit 0 if -e $done; open my $fh, ">", $deadline or exit 0; close $fh;\' "$pd_dw_ms" "$pd_dw_done" "$pd_dw_deadline"',
    '      fi',
    '      # Perl is present on supported macOS hosts and gives a sub-second',
    '      # monotonic deadline without spawning one process per poll. The',
    '      # portable fallback is second-granular but still uses one real timer',
    '      # instead of pretending every scheduler sleep was exactly 10ms.',
    '      pd_dw_seconds=$(((pd_dw_ms + 999) / 1000))',
    '      [ "$pd_dw_seconds" -gt 0 ] 2>/dev/null || pd_dw_seconds=1',
    '      sleep "$pd_dw_seconds" 2>/dev/null',
    '      [ -f "$pd_dw_done" ] || : > "$pd_dw_deadline" 2>/dev/null || true',
    '    }',
    '    pd_deadline_watch_stop() {',
    '      if [ -n "$pd_deadline_watch_pid" ]; then',
    '        if command -v pkill >/dev/null 2>&1; then pkill -TERM -P "$pd_deadline_watch_pid" 2>/dev/null || true; fi',
    '        kill -TERM "$pd_deadline_watch_pid" 2>/dev/null || true',
    '        wait "$pd_deadline_watch_pid" 2>/dev/null || true',
    '        pd_deadline_watch_pid=""',
    '      fi',
    '      rm -f "$pd_deadline_file" 2>/dev/null || true',
    '    }',
    '    pd_child_pid_read() {',
    '      pd_read_pid=$(cat "$pd_child_pid_file" 2>/dev/null || true)',
    '      case "$pd_read_pid" in ""|*[!0-9]*) pd_read_pid="" ;; esac',
    '      printf "%s" "$pd_read_pid"',
    '    }',
    '    pd_health_signal() {',
    '      trap - HUP INT TERM',
    '      rm -f "$pd_time_file" 2>/dev/null || true',
    '      pd_health_record_unhealthy signal 124 "$pd_slow_ms"',
    '      pd_debug_finish interrupted 124',
    '      pd_deadline_watch_stop',
    '      pd_kill_child "$(pd_child_pid_read)" "$pd_child_done_file"',
    '      rm -f "$pd_child_done_file" "$pd_child_pid_file" "$pd_deadline_file" 2>/dev/null || true',
    '      exit 0',
    '    }',
    '    trap pd_health_signal HUP INT TERM',
    '    pd_real_hook="$PD_HOME/bin/squid/${0##*/}"',
    '    if [ ! -x "$pd_real_hook" ]; then',
    '      printf "real 0.00\\nuser 0.00\\nsys 0.00\\n" > "$pd_time_file" 2>/dev/null || true',
    '      pd_exit=127',
    '    elif [ ! -x "$pd_time_bin" ]; then',
    '      printf "real 0.00\\nuser 0.00\\nsys 0.00\\n" > "$pd_time_file" 2>/dev/null || true',
    '      pd_timer_missing=1',
    '      pd_exit=0',
    '    else',
    '      # The wrapper OWNS the deadline (finding 2): the child runs in the',
    '      # background so THIS process — the survivor even if the child is',
    '      # hard-killed or wedges forever — polls its OWN pd_deadline_ms rather',
    '      # than only ever measuring elapsed time after a synchronous child',
    '      # returns. Completion is detected via a sentinel FILE the launcher',
    '      # writes (never a signal-0 probe — see pd_kill_child above), and the',
    '      # timer\'s own pid is captured to a file too, so it can be targeted precisely',
    '      # once the deadline elapses.',
    '      if [ "$pd_debug" -eq 1 ]; then',
    '        (',
    '          # Use the external POSIX timer: dash emits reserved-word `time`',
    '          # diagnostics after shell redirections are restored. -o isolates',
    '          # only timing data while hook stderr still reaches the host. The',
    '          # bounded head is replayed first, then the rest of the original',
    '          # stream is piped straight through — never re-buffered.',
    '          { printf "%s" "$pd_input_head"; cat; } | "$pd_time_bin" -p -o "$pd_time_file" "$pd_real_hook" "$@" &',
    '          pd_inner_pid=$!',
    '          printf "%s" "$pd_inner_pid" > "$pd_child_pid_file" 2>/dev/null || true',
    '          wait "$pd_inner_pid" 2>/dev/null',
    '          printf "%s" "$?" > "$pd_child_done_file.$$" 2>/dev/null && mv "$pd_child_done_file.$$" "$pd_child_done_file" 2>/dev/null',
    '        ) &',
    '      else',
    '        (',
    '          "$pd_time_bin" -p -o "$pd_time_file" "$pd_real_hook" "$@" &',
    '          pd_inner_pid=$!',
    '          printf "%s" "$pd_inner_pid" > "$pd_child_pid_file" 2>/dev/null || true',
    '          wait "$pd_inner_pid" 2>/dev/null',
    '          printf "%s" "$?" > "$pd_child_done_file.$$" 2>/dev/null && mv "$pd_child_done_file.$$" "$pd_child_done_file" 2>/dev/null',
    '        ) &',
    '      fi',
    '      pd_deadline_hit=0',
    '      # A separate monotonic timer owns the deadline. The old loop',
    '      # incremented a synthetic 10ms counter after each sleep, so a loaded',
    '      # macOS scheduler could turn a nominal 1s deadline into 4-7s.',
    '      pd_deadline_watch "$pd_deadline_ms" "$pd_child_done_file" "$pd_deadline_file" &',
    '      pd_deadline_watch_pid=$!',
    '      while [ ! -f "$pd_child_done_file" ] && [ ! -f "$pd_deadline_file" ]; do',
    '        sleep 0.01 2>/dev/null',
    '      done',
    '      if [ -f "$pd_deadline_file" ]; then',
    '        wait "$pd_deadline_watch_pid" 2>/dev/null || true',
    '        pd_deadline_watch_pid=""',
    '        pd_deadline_hit=1',
    '      else',
    '        pd_deadline_watch_stop',
    '      fi',
    '      if [ "$pd_deadline_hit" -eq 1 ]; then',
    '        # Durability first: the timeout receipt is written BEFORE any attempt',
    '        # to reap or kill the child, so it survives even if this process',
    '        # never regains control afterward (e.g. the host kills everything a',
    '        # moment later). This is the exact gap review finding 2 named: a',
    '        # hard-killed/hung child must not be able to vanish without the',
    '        # breaker recording it.',
    '        trap - HUP INT TERM',
    '        pd_health_record_unhealthy timeout 124 "$pd_deadline_ms"',
    '        pd_debug_finish interrupted 124',
    '        pd_kill_child "$(pd_child_pid_read)" "$pd_child_done_file"',
    '        rm -f "$pd_time_file" "$pd_child_done_file" "$pd_child_pid_file" "$pd_deadline_file" 2>/dev/null || true',
    '        exit 0',
    '      fi',
    '      pd_exit=$(cat "$pd_child_done_file" 2>/dev/null || printf 1)',
    '      case "$pd_exit" in ""|*[!0-9]*) pd_exit=1 ;; esac',
    '      rm -f "$pd_child_done_file" "$pd_child_pid_file" "$pd_deadline_file" 2>/dev/null || true',
    '    fi',
    '    trap - HUP INT TERM',
    '    pd_health_duration_read',
    '    if [ "$pd_timer_missing" -eq 1 ]; then',
    '      pd_health_record_unhealthy timer_missing 126 0',
    '      pd_debug_finish failure_swallowed 126',
    '      exit 0',
    '    fi',
    '    if [ "$pd_exit" -eq 2 ]; then',
    '      pd_health_record_healthy',
    '      pd_debug_finish blocked 2',
    '      exit 2',
    '    fi',
    '    if [ "$pd_exit" -eq 0 ] && [ "$pd_duration_ms" -lt "$pd_slow_ms" ]; then',
    '      pd_health_record_healthy',
    '      pd_debug_finish executed 0',
    '      exit 0',
    '    fi',
    '    if [ "$pd_exit" -eq 0 ]; then',
    '      pd_health_record_unhealthy slow 0 "$pd_duration_ms"',
    '      pd_debug_finish slow 0',
    '      exit 0',
    '    fi',
    '    pd_health_record_unhealthy "exit_$pd_exit" "$pd_exit" "$pd_duration_ms"',
    '    pd_debug_finish failure_swallowed "$pd_exit"',
    '    exit 0',
    '  fi',
    '  d=${d%/*}; [ -n "$d" ] || d=/',
    'done',
    '# not a pd project (or daemon down) -> no-op; allow the tool (fail open).',
    'pd_debug_skip no_project',
    '',
  ].join('\n');
}

// ─── Per-project arm registry ────────────────────────────────────────────────

export function squidProjectRegistryPath(pdHome = PD_HOME): string {
  return join(pdHome, 'squid', 'projects');
}

function canonicalProjectRoot(cwd: string): string {
  const absolute = resolve(cwd);
  try { return realpathSync(absolute); } catch { return absolute; }
}

export function readArmedSquidProjects(registryPath = squidProjectRegistryPath()): string[] {
  if (!existsSync(registryPath)) return [];
  try {
    return [...new Set(readFileSync(registryPath, 'utf8').split('\n').map((line) => line.trim()).filter(Boolean))].sort();
  } catch {
    return [];
  }
}

export function registerSquidProject(cwd: string, registryPath = squidProjectRegistryPath()): string {
  const project = canonicalProjectRoot(cwd);
  const projects = [...new Set([...readArmedSquidProjects(registryPath), project])].sort();
  mkdirSync(dirname(registryPath), { recursive: true });
  writeFileSync(registryPath, `${projects.join('\n')}\n`, { mode: 0o600 });
  chmodSync(registryPath, 0o600);
  return project;
}

export function unregisterSquidProject(cwd: string, registryPath = squidProjectRegistryPath()): boolean {
  const project = canonicalProjectRoot(cwd);
  const before = readArmedSquidProjects(registryPath);
  const after = before.filter((entry) => entry !== project);
  if (after.length === before.length) return false;
  if (after.length === 0) rmSync(registryPath, { force: true });
  else {
    writeFileSync(registryPath, `${after.join('\n')}\n`, { mode: 0o600 });
    chmodSync(registryPath, 0o600);
  }
  return true;
}

export function clearArmedSquidProjects(registryPath = squidProjectRegistryPath()): void {
  rmSync(registryPath, { force: true });
}

export function isSquidProjectArmed(cwd: string, registryPath = squidProjectRegistryPath()): boolean {
  return readArmedSquidProjects(registryPath).includes(canonicalProjectRoot(cwd));
}

// ─── Tentacle staging ────────────────────────────────────────────────────────

export interface StageResult {
  staged: string[];
  missing: TentacleName[];
  sourceDir: string;
}

/**
 * Copy the real tentacles to ~/.port-daddy/bin/squid/ and (re)write the gate
 * wrappers to ~/.port-daddy/bin/. The tentacles are owned by the squid program;
 * this installer only consumes them. If they are absent on this build, nothing
 * is staged and the caller surfaces guidance.
 */
export function stageTentacles(
  sourceDir?: string,
  destBinDir = tentacleBinDir(),
): StageResult {
  const resolved = TENTACLES.map((name) => {
    const explicit = sourceDir ? join(sourceDir, name) : null;
    const source = explicit ? (existsSync(explicit) ? explicit : null) : resolveSquidAsset(join('bin', name));
    return { name, source };
  });
  const missing = resolved.filter((candidate) => candidate.source === null).map((candidate) => candidate.name);
  if (missing.length > 0) {
    return { staged: [], missing, sourceDir: sourceDir ?? 'runtime asset resolver' };
  }

  const realDir = join(destBinDir, 'squid');
  const binDir = destBinDir;
  const healthDir = join(dirname(binDir), 'squid', 'health');
  mkdirSync(realDir, { recursive: true });
  mkdirSync(binDir, { recursive: true });
  mkdirSync(healthDir, { recursive: true, mode: 0o700 });
  chmodSync(healthDir, 0o700);

  const staged: string[] = [];
  const suffix = `.stage-${process.pid}-${Date.now()}`;
  const temporary: string[] = [];
  try {
    for (const { name, source } of resolved) {
      const src = source as string;
      const realDst = join(realDir, name);
      const realTmp = `${realDst}${suffix}`;
      const wrapper = join(binDir, name);
      const wrapperTmp = `${wrapper}${suffix}`;
      copyFileSync(src, realTmp);
      chmodSync(realTmp, 0o755);
      writeFileSync(wrapperTmp, gateWrapperScript(), { mode: 0o755 });
      chmodSync(wrapperTmp, 0o755);
      temporary.push(realTmp, wrapperTmp);
    }

    for (const { name } of resolved) {
      const realDst = join(realDir, name);
      const wrapper = join(binDir, name);
      renameSync(`${realDst}${suffix}`, realDst);
      renameSync(`${wrapper}${suffix}`, wrapper);
      staged.push(wrapper);
    }
  } finally {
    for (const path of temporary) rmSync(path, { force: true });
  }
  return { staged, missing, sourceDir: sourceDir ?? 'runtime asset resolver' };
}

// ─── Target definitions ──────────────────────────────────────────────────────

type HookFormat = 'json' | 'codex-toml';
type Vendor = 'claude' | 'gemini' | 'agy';

export interface AgentCliTarget {
  name: string;
  slug: string;
  bin: string;
  format: HookFormat;
  vendor?: Vendor; // JSON vendors only
  userConfigPath: string;
  /** Project-level config, or null when the CLI has no useful project-interactive surface. */
  projectConfigPath: ((cwd: string) => string) | null;
  detect(): boolean;
  note?: string;
}

function commandExists(bin: string): boolean {
  try {
    execFileSync('command', ['-v', bin], { stdio: ['pipe', 'pipe', 'pipe'], shell: '/bin/sh' });
    return true;
  } catch {
    try {
      execFileSync('which', [bin], { stdio: ['pipe', 'pipe', 'pipe'] });
      return true;
    } catch {
      return false;
    }
  }
}

export function buildTargets(home: string): AgentCliTarget[] {
  return [
    {
      name: 'Claude Code',
      slug: 'claude',
      bin: 'claude',
      format: 'json',
      vendor: 'claude',
      userConfigPath: join(home, '.claude', 'settings.json'),
      projectConfigPath: (cwd) => join(cwd, '.claude', 'settings.json'),
      detect: () => commandExists('claude'),
    },
    {
      name: 'Codex CLI',
      slug: 'codex',
      bin: 'codex',
      format: 'codex-toml',
      userConfigPath: join(home, '.codex', 'config.toml'),
      // repo-local hooks don't fire interactively (openai/codex#17532) — user-level
      // only; the runtime gate keeps it per-project.
      projectConfigPath: null,
      detect: () => commandExists('codex'),
      note: 'user-level ~/.codex (repo-local does not fire interactively, openai/codex#17532); trust once via /hooks',
    },
    {
      name: 'Gemini CLI',
      slug: 'gemini',
      bin: 'gemini',
      format: 'json',
      vendor: 'gemini',
      userConfigPath: join(home, '.gemini', 'settings.json'),
      projectConfigPath: (cwd) => join(cwd, '.gemini', 'settings.json'),
      detect: () => commandExists('gemini'),
    },
    {
      name: 'Antigravity (agy)',
      slug: 'agy',
      bin: 'agy',
      format: 'json',
      vendor: 'agy',
      userConfigPath: join(home, '.gemini', 'hooks.json'), // home-scoped engine file
      projectConfigPath: null,
      detect: () => commandExists('agy'),
      note: 'home-scoped ~/.gemini/hooks.json; runtime gate keeps it per-project',
    },
  ];
}

// ─── Configure a single target ───────────────────────────────────────────────

export interface ConfigureResult {
  success: boolean;
  created?: boolean;
  path: string;
  error?: string;
  skipped?: string;
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

/** Resolver pointing hook commands at the gate and attaching only static metadata. */
function gateResolverFor(provider: string): TentacleResolver {
  return (name) => [
    `PD_HOOK_PROVIDER=${provider}`,
    `PD_HOOK_DEADLINE_MS=${SQUID_HOOK_DEADLINE_MS}`,
    shellQuote(gatePath(name)),
  ].join(' ');
}

function atomicWriteConfig(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const temporary = join(dirname(path), `.${basename(path)}.pd-${process.pid}-${Date.now()}.tmp`);
  try {
    writeFileSync(temporary, content, { mode: 0o600 });
    renameSync(temporary, path);
  } finally {
    rmSync(temporary, { force: true });
  }
}

/**
 * Codex once loaded ~/.codex/hooks.json; current Codex uses config.toml. Remove
 * only Port Daddy entries from that legacy surface when present so an upgrade
 * cannot fire both generations of synchronous hooks. User hooks survive.
 */
function migratedLegacyCodexHooksJson(configPath: string): { path: string; content: string } | null {
  const path = join(dirname(configPath), 'hooks.json');
  if (!existsSync(path)) return null;
  const raw = readFileSync(path, 'utf-8').trim();
  let config: Record<string, unknown>;
  try {
    config = raw ? (JSON.parse(raw) as Record<string, unknown>) : {};
  } catch {
    // A malformed retired surface cannot be active, and must not prevent the
    // current TOML hook registration from being repaired. Preserve it exactly.
    return null;
  }
  if (!removeJsonHooks(config)) return null;
  return { path, content: JSON.stringify(config, null, 2) + '\n' };
}

/**
 * Install the current Codex TOML before retiring the legacy JSON registration.
 * Each write is atomic on its own. This order means an interrupted first write
 * leaves the still-working legacy hooks untouched; an interrupted cleanup may
 * briefly leave duplicates, but can never leave Codex with no Port Daddy hook.
 */
export function commitCodexConfigMigration(
  configPath: string,
  configContent: string,
  legacy: { path: string; content: string } | null,
  writeConfig: (path: string, content: string) => void = atomicWriteConfig,
): void {
  writeConfig(configPath, configContent);
  if (legacy) writeConfig(legacy.path, legacy.content);
}

export function configureTarget(
  target: AgentCliTarget,
  opts: { scope: 'user' | 'project'; cwd?: string },
): ConfigureResult {
  let configPath: string;
  if (opts.scope === 'user') {
    configPath = target.userConfigPath;
  } else {
    if (!target.projectConfigPath) {
      return { success: true, path: '', skipped: 'no interactive project surface' };
    }
    configPath = target.projectConfigPath(opts.cwd ?? process.cwd());
  }

  try {
    const existed = existsSync(configPath);
    mkdirSync(dirname(configPath), { recursive: true });

    if (target.format === 'codex-toml') {
      const existing = existed ? readFileSync(configPath, 'utf-8') : '';
      const base = stripCodexHooksTomlBlock(existing).replace(/\s*$/, '');
      const sep = base.length ? '\n\n' : '';
      const legacy = migratedLegacyCodexHooksJson(configPath);
      commitCodexConfigMigration(
        configPath,
        `${base}${sep}${codexHooksTomlBlock(gateResolverFor(target.slug))}\n`,
        legacy,
      );
      return { success: true, created: !existed, path: configPath };
    }

    let config: Record<string, unknown> = {};
    if (existed) {
      const raw = readFileSync(configPath, 'utf-8').trim();
      if (raw) config = JSON.parse(raw) as Record<string, unknown>;
    }
    upsertJsonHookMap(config, buildJsonHookMap(target.vendor!, gateResolverFor(target.slug)));
    atomicWriteConfig(configPath, JSON.stringify(config, null, 2) + '\n');
    return { success: true, created: !existed, path: configPath };
  } catch (err) {
    return { success: false, path: configPath, error: (err as Error).message };
  }
}

export function uninstallTarget(
  target: AgentCliTarget,
  opts: { scope: 'user' | 'project'; cwd?: string },
): ConfigureResult {
  let configPath: string;
  if (opts.scope === 'user') configPath = target.userConfigPath;
  else if (target.projectConfigPath) configPath = target.projectConfigPath(opts.cwd ?? process.cwd());
  else if (target.format === 'codex-toml') {
    // Current Codex reads user config, but releases before 3.30 also wrote a
    // project-local TOML block. Sweep that retired surface so a cached or future
    // project loader cannot keep calling a deleted Homebrew Cellar path.
    configPath = join(opts.cwd ?? process.cwd(), '.codex', 'config.toml');
  } else return { success: true, path: '', skipped: 'no project surface' };

  if (!existsSync(configPath)) return { success: true, path: configPath, skipped: 'no config' };

  try {
    if (target.format === 'codex-toml') {
      const legacy = migratedLegacyCodexHooksJson(configPath);
      commitCodexConfigMigration(
        configPath,
        stripCodexHooksTomlBlock(readFileSync(configPath, 'utf-8')),
        legacy,
      );
      return { success: true, path: configPath };
    }
    const raw = readFileSync(configPath, 'utf-8').trim();
    const config = raw ? (JSON.parse(raw) as Record<string, unknown>) : {};
    removeJsonHooks(config);
    atomicWriteConfig(configPath, JSON.stringify(config, null, 2) + '\n');
    return { success: true, path: configPath };
  } catch (err) {
    return { success: false, path: configPath, error: (err as Error).message };
  }
}

/**
 * Write the right scopes for a target: project where it has a project surface
 * (claude/gemini), user-level where it must be global (codex/agy). Everything is
 * runtime-gated to pd projects regardless of where the config lives.
 */
function wireTarget(target: AgentCliTarget, cwd: string, alsoUser: boolean): ConfigureResult[] {
  const out: ConfigureResult[] = [];
  if (target.projectConfigPath) {
    out.push(configureTarget(target, { scope: 'project', cwd }));
    if (alsoUser) out.push(configureTarget(target, { scope: 'user' }));
  } else {
    // codex/agy: user-level is the only interactive surface; the gate scopes it.
    if (target.format === 'codex-toml') {
      const cleanup = uninstallTarget(target, { scope: 'project', cwd });
      if (!cleanup.success) out.push(cleanup);
    }
    out.push(configureTarget(target, { scope: 'user' }));
  }
  return out;
}

// ─── Silent install (pd init) ────────────────────────────────────────────────

export interface SilentHooksResult {
  configured: number;
  detected: string[];
  tentaclesMissing: boolean;
  failures: string[];
}

export interface HookTargetStatus {
  name: string;
  slug: string;
  detected: boolean;
  projectPath: string | null;
  userPath: string;
  projectWired: boolean;
  userWired: boolean;
  expectedScope: 'project' | 'user';
  wired: boolean;
  note?: string;
  projectArmed: boolean;
}

function configCarriesPdHook(path: string): boolean {
  try {
    return existsSync(path) && readFileSync(path, 'utf8').includes(PD_HOOK_MARKER);
  } catch {
    return false;
  }
}

/** Read-only truth used by `pd squid status --json` and operator surfaces. */
export function inspectHookTargets(home = DEFAULT_HOME, cwd = process.cwd()): HookTargetStatus[] {
  const projectArmed = isSquidProjectArmed(cwd);
  return buildTargets(home).map((target) => {
    const projectPath = target.projectConfigPath?.(cwd) ?? null;
    const projectWired = projectPath ? configCarriesPdHook(projectPath) : false;
    const userWired = configCarriesPdHook(target.userConfigPath);
    const expectedScope = target.projectConfigPath ? 'project' : 'user';
    return {
      name: target.name,
      slug: target.slug,
      detected: target.detect(),
      projectPath,
      userPath: target.userConfigPath,
      projectWired,
      userWired,
      expectedScope,
      wired: projectArmed && (expectedScope === 'project' ? projectWired : userWired),
      note: target.note,
      projectArmed,
    };
  });
}

/**
 * Wire detected CLIs for a specific project (pd init). Project-level for
 * claude/gemini; gated user-level for codex/agy. Never global-by-default.
 */
export function silentHooksInstall(
  home = DEFAULT_HOME,
  opts: { cwd?: string; stage?: StageResult; resetHealthOnSuccess?: boolean } = {},
): SilentHooksResult {
  const cwd = opts.cwd ?? process.cwd();
  // `pd squid on` already stages once for the whole arm transaction. Reuse
  // that fulfilled result instead of repeating release-asset discovery/copies.
  const stage = opts.stage ?? stageTentacles();
  const detected = buildTargets(home).filter((t) => t.detect());
  const result: SilentHooksResult = {
    configured: 0,
    detected: detected.map((t) => t.slug),
    tentaclesMissing: stage.missing.length > 0,
    failures: [],
  };
  if (result.tentaclesMissing || detected.length === 0) return result;
  registerSquidProject(cwd);

  for (const target of detected) {
    const results = wireTarget(target, cwd, false);
    if (results.some((r) => r.success && !r.skipped)) result.configured++;
    for (const failure of results.filter((r) => !r.success)) {
      result.failures.push(`${target.slug}: ${failure.error ?? 'configuration failed'}`);
    }
  }
  if (result.failures.length > 0 || result.configured < detected.length) {
    unregisterSquidProject(cwd);
  } else if (opts.resetHealthOnSuccess !== false) {
    resetSquidHookHealth();
  }
  return result;
}

// ─── Interactive command (pd hooks ...) ──────────────────────────────────────

export async function handleHooks(
  positional: string[],
  options: Record<string, unknown>,
  home = DEFAULT_HOME,
): Promise<void> {
  const sub = positional[0] ?? 'install';
  const targets = buildTargets(home);

  if (isHooksStatusRequest(sub, options)) {
    console.log('');
    ui.info('Port Daddy agent-CLI hooks (per-project, daemon-gated)');
    console.log('');
    const cwd = process.cwd();
    console.log(`  This project: ${isSquidProjectArmed(cwd) ? '\x1b[32mARMED\x1b[0m' : '\x1b[2mnot armed\x1b[0m'} (${canonicalProjectRoot(cwd)})`);
    console.log('');
    for (const t of targets) {
      const present = t.detect();
      const status = present ? '\x1b[32m✓ installed\x1b[0m' : '\x1b[2m- not found\x1b[0m';
      const wired =
        existsSync(t.userConfigPath) && readFileSync(t.userConfigPath, 'utf-8').includes(PD_HOOK_MARKER)
          ? ' \x1b[32m(user-wired)\x1b[0m'
          : '';
      console.log(`    ${t.name.padEnd(22)} ${status}${wired}`);
      if (present && t.note) console.log(`      \x1b[2m${t.note}\x1b[0m`);
    }
    console.log('');
    return;
  }

  if (sub === 'uninstall' || sub === 'remove') {
    console.log('');
    ui.info('Removing Port Daddy hooks from all agent CLIs');
    const cwd = process.cwd();
    for (const t of targets) {
      for (const scope of ['user', 'project'] as const) {
        const r = uninstallTarget(t, { scope, cwd });
        if (r.success && !r.skipped) ui.success(`${t.name} (${scope}): cleared ${r.path}`);
      }
    }
    clearArmedSquidProjects();
    console.log('');
    return;
  }

  // install
  console.log('');
  ui.info('Port Daddy — agent-CLI interactive hooks (this project)');
  console.log('');

  const detected = targets.filter((t) => t.detect());
  if (detected.length === 0) {
    ui.warn('No agent CLIs detected (looked for claude, codex, gemini, agy).');
    console.log('');
    process.exitCode = 1;
    return;
  }

  const cwd = process.cwd();
  console.log('  Detected: ' + detected.map((t) => t.name).join(', '));
  console.log(`  Wires coordination into their interactive sessions for THIS project (${cwd}).`);
  console.log('  Hooks are inert unless the pd daemon is running and this exact project root is armed.');
  console.log('');

  const assumeYes = !!options.yes || !!options.y || !ui.canPrompt();
  const proceed = assumeYes ? true : await ui.confirm('Wire coordination hooks for this project?', true);
  if (!proceed) {
    ui.info('Skipped. Run `pd hooks install` any time.');
    return;
  }

  const stage = stageTentacles();
  if (stage.missing.length > 0) {
    ui.warn(`Squid tentacles not found on this build (${stage.missing.join(', ')}).`);
    console.log('  The hook scripts (bin/pd-hook-*) ship with the Giant Squid Harness.');
    console.log('  Update Port Daddy, then re-run `pd hooks install`.');
    console.log('');
    process.exitCode = 1;
    return;
  }
  ui.success(`Staged tentacles + gate → ${tentacleBinDir()}`);
  registerSquidProject(cwd);

  const alsoUser = !!options.user;
  const failures: string[] = [];
  console.log('');
  console.log('  Wiring hooks:');
  for (const target of detected) {
    const results = wireTarget(target, cwd, alsoUser);
    for (const r of results) {
      if (r.skipped) continue;
      if (r.success) console.log(`    \x1b[32m✓\x1b[0m ${target.name.padEnd(22)} ${r.path}`);
      else {
        failures.push(`${target.slug}: ${r.error ?? 'configuration failed'}`);
        console.log(`    \x1b[31m✗\x1b[0m ${target.name.padEnd(22)} ${r.error}`);
      }
    }
    if (target.note) console.log(`      \x1b[2m${target.note}\x1b[0m`);
  }

  console.log('');
  if (failures.length > 0) {
    unregisterSquidProject(cwd);
    ui.warn(`Hook installation failed closed; this project remains inert (${failures.join('; ')}).`);
    process.exitCode = 1;
  } else {
    resetSquidHookHealth();
    ui.success('Coordination hooks wired for this project (active only when the daemon is up).');
  }
  if (detected.some((t) => t.slug === 'codex')) {
    console.log('  Codex: run `codex` → `/hooks` once to trust the pd hooks (persisted thereafter).');
  }
  console.log('  Verify:  pd hooks list   ·   Remove:  pd hooks uninstall');
  console.log('');
}

export function isHooksStatusRequest(sub: string, options: Record<string, unknown>): boolean {
  return sub === 'list' || sub === 'status' || !!options.list || !!options.status;
}
