/**
 * pd hooks install — Per-project, daemon-gated coordination hooks for agent CLIs
 *
 * Wires the Giant Squid Harness tentacles into the INTERACTIVE sessions of the
 * agent CLIs on this machine (Claude Code, Codex, Gemini, Antigravity/agy). The
 * hook SHAPES come from one shared source of truth — lib/squid/hook-shape.ts —
 * which the squid headless adapter uses too, so the interactive and headless
 * injectors can never drift.
 *
 * Two guarantees the user asked for:
 *   1. PER PROJECT. Claude/Gemini get project-level config written into the repo
 *      (`<repo>/.claude/settings.json`, `<repo>/.gemini/settings.json`). Codex
 *      (repo-local hooks don't fire interactively — openai/codex#17532) and agy
 *      (home-scoped `~/.gemini/hooks.json`) must be user-level, so they are
 *      constrained at RUNTIME by the gate below.
 *   2. INERT UNLESS PORT DADDY IS RUNNING. Every hook command points at a gate
 *      wrapper, not the tentacle directly. The wrapper no-ops (allow / no
 *      context) unless (a) the pd daemon is alive AND (b) the cwd is inside a
 *      pd-enabled project (a `.portdaddy/` marker on the path). So the hooks do
 *      nothing in non-pd projects or when the daemon is down.
 *
 * Layout under ~/.port-daddy/bin/:
 *   squid/pd-hook-{prompt,pre-tool,post-tool}   <- the real tentacles (copied)
 *   pd-hook-{prompt,pre-tool,post-tool}         <- generated gate wrappers
 * Hook configs point at the gate wrappers.
 *
 * Usage:
 *   pd hooks install            # wire detected CLIs for THIS project (+gated user cfg)
 *   pd hooks install --user     # also write user-level config for claude/gemini
 *   pd hooks list               # detection + wiring status
 *   pd hooks uninstall          # remove Port Daddy hooks from every surface
 */

import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  copyFileSync,
  chmodSync,
  realpathSync,
  renameSync,
  rmSync,
} from 'node:fs';
import { basename, join, dirname, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import * as ui from '../utils/ui.js';
import { PD_HOME } from '../../shared/paths.js';
import {
  TENTACLES,
  type TentacleName,
  type TentacleResolver,
  PD_HOOK_MARKER,
  CODEX_PD_MARKER,
  SQUID_HOOK_DEADLINE_MS,
  buildJsonHookMap,
  codexHooksTomlBlock,
  upsertJsonHookMap,
  removeJsonHooks,
  stripCodexHooksTomlBlock,
} from '../../lib/squid/hook-shape.js';
import {
  SQUID_HOOK_BREAKER_COOLDOWN_MS,
  SQUID_HOOK_BREAKER_FAILURE_THRESHOLD,
  SQUID_HOOK_BREAKER_SLOW_MS,
  SQUID_HOOK_DEBUG_MAX_BYTES,
  SQUID_HOOK_DEBUG_TRIM_BYTES,
  resetSquidHookHealth,
} from '../../lib/squid/debug.js';
import { resolveSquidAsset } from '../../lib/squid/assets.js';

const DEFAULT_HOME = process.env.HOME || process.env.USERPROFILE || '';
const SQUID_DAEMON_HEARTBEAT_STALE_SECONDS = 30;

/** ~/.port-daddy/bin — staged gate wrappers (what hook configs point at). */
export function tentacleBinDir(): string {
  return join(PD_HOME, 'bin');
}
/** ~/.port-daddy/bin/squid — the real tentacles the wrappers delegate to. */
function realTentacleDir(): string {
  return join(PD_HOME, 'bin', 'squid');
}
/** The gate-wrapper path a hook config invokes for a given tentacle. */
function gatePath(name: TentacleName): string {
  return join(tentacleBinDir(), name);
}

// ─── Gate wrapper (pd-running + per-project) ─────────────────────────────────

/**
 * The shell gate. It runs on every tool call, so it is filesystem-only and
 * spawns no `pd` process. It allows/no-ops (exit 0) unless the daemon heartbeat
 * is fresh and the cwd is inside a pd-enabled project, then execs the real
 * tentacle with stdin/argv intact.
 *
 * Do not use `kill -0` or `ps` here. Codex's macOS Seatbelt profile denies both
 * against the Homebrew daemon even though it is owned by the same user, which
 * made every Codex hook silently fail open. The Bosun heartbeat is specifically
 * designed as the filesystem-only liveness contract for sandboxed observers.
 */
function gateWrapperScript(): string {
  return [
    '#!/bin/sh',
    '# Port Daddy hook gate — GENERATED by `pd hooks install`. Do not edit.',
    '# Makes coordination hooks per-project and inert unless the daemon is up.',
    'PD_HOME="${PD_HOME:-$HOME/.port-daddy}"',
    '',
    '# Opt-in, sanitized timing trace. The event format has no field for stdin,',
    '# argv, environment snapshots, prompt text, tool input/result, stdout, or stderr.',
    'pd_debug=0',
    'pd_debug_dir="$PD_HOME/squid"',
    'pd_debug_log="$pd_debug_dir/hook-events.log"',
    'pd_debug_lock="$pd_debug_dir/debug-write.lock"',
    'pd_hook="${0##*/}"',
    'case "$pd_hook" in',
    '  pd-hook-prompt) pd_phase=turn ;;',
    '  pd-hook-pre-tool) pd_phase=edit ;;',
    '  pd-hook-post-tool) pd_phase=trace ;;',
    '  *) pd_phase=turn ;;',
    'esac',
    'pd_provider="${PD_HOOK_PROVIDER:-unknown}"',
    'case "$pd_provider" in claude|codex|gemini|agy) ;; *) pd_provider=unknown ;; esac',
    `pd_deadline_ms="${'${PD_HOOK_DEADLINE_MS:-'}${SQUID_HOOK_DEADLINE_MS}}"`,
    `case "$pd_deadline_ms" in ""|*[!0-9]*) pd_deadline_ms=${SQUID_HOOK_DEADLINE_MS} ;; esac`,
    `pd_failure_threshold="${'${PD_HOOK_FAILURE_THRESHOLD:-'}${SQUID_HOOK_BREAKER_FAILURE_THRESHOLD}}"`,
    `case "$pd_failure_threshold" in ""|*[!0-9]*) pd_failure_threshold=${SQUID_HOOK_BREAKER_FAILURE_THRESHOLD} ;; esac`,
    `pd_slow_ms="${'${PD_HOOK_SLOW_MS:-'}${SQUID_HOOK_BREAKER_SLOW_MS}}"`,
    `case "$pd_slow_ms" in ""|*[!0-9]*) pd_slow_ms=${SQUID_HOOK_BREAKER_SLOW_MS} ;; esac`,
    `pd_cooldown_ms="${'${PD_HOOK_BREAKER_COOLDOWN_MS:-'}${SQUID_HOOK_BREAKER_COOLDOWN_MS}}"`,
    `case "$pd_cooldown_ms" in ""|*[!0-9]*) pd_cooldown_ms=${SQUID_HOOK_BREAKER_COOLDOWN_MS} ;; esac`,
    `[ "$pd_failure_threshold" -gt 0 ] 2>/dev/null || pd_failure_threshold=${SQUID_HOOK_BREAKER_FAILURE_THRESHOLD}`,
    `[ "$pd_slow_ms" -gt 0 ] 2>/dev/null || pd_slow_ms=${SQUID_HOOK_BREAKER_SLOW_MS}`,
    `[ "$pd_cooldown_ms" -gt 0 ] 2>/dev/null || pd_cooldown_ms=${SQUID_HOOK_BREAKER_COOLDOWN_MS}`,
    '',
    'pd_debug_now_ms() {',
    '  if [ -x /usr/bin/perl ]; then',
    '    /usr/bin/perl -MTime::HiRes=time -e \'printf "%.0f", time * 1000\'',
    '  else',
    '    printf "%s000" "$(date +%s)"',
    '  fi',
    '}',
    'pd_epoch_ms() {',
    '  printf "%s000" "$(date +%s)"',
    '}',
    'pd_debug_lock_acquire() {',
    '  pd_attempt=0',
    '  while ! mkdir "$pd_debug_lock" 2>/dev/null; do',
    '    pd_attempt=$((pd_attempt + 1))',
    '    pd_lock_now=$(date +%s 2>/dev/null || printf 0)',
    '    pd_lock_modified=$(stat -f %m "$pd_debug_lock" 2>/dev/null || true)',
    '    case "$pd_lock_modified" in ""|*[!0-9]*) pd_lock_modified=$(stat -c %Y "$pd_debug_lock" 2>/dev/null || true) ;; esac',
    '    case "$pd_lock_now:$pd_lock_modified" in *[!0-9:]*) ;; *) [ $((pd_lock_now - pd_lock_modified)) -gt 5 ] 2>/dev/null && rmdir "$pd_debug_lock" 2>/dev/null ;; esac',
    '    [ "$pd_attempt" -lt 20 ] || return 1',
    '    sleep 0.01',
    '  done',
    '}',
    'pd_debug_append() {',
    '  [ "$pd_debug" -eq 1 ] || return 0',
    '  umask 077',
    '  mkdir -p "$pd_debug_dir" 2>/dev/null || return 0',
    '  pd_debug_lock_acquire || return 0',
    '  printf "v1\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n" "$1" "$pd_run_id" "$pd_session_id" "$pd_provider" "$pd_phase" "$pd_hook" "$2" "$pd_deadline_ms" "$3" "$4" "$pd_workspace_b64" >> "$pd_debug_log" 2>/dev/null || true',
    '  pd_size=$(wc -c < "$pd_debug_log" 2>/dev/null || printf 0)',
    `  case "$pd_size" in ""|*[!0-9]*) ;; *) [ "$pd_size" -le ${SQUID_HOOK_DEBUG_MAX_BYTES} ] || tail -c ${SQUID_HOOK_DEBUG_TRIM_BYTES} "$pd_debug_log" > "$pd_debug_log.trim" 2>/dev/null ;; esac`,
    '  [ -f "$pd_debug_log.trim" ] && chmod 600 "$pd_debug_log.trim" 2>/dev/null && mv "$pd_debug_log.trim" "$pd_debug_log" 2>/dev/null',
    '  rm -f "$pd_debug_log.trim" 2>/dev/null || true',
    '  rmdir "$pd_debug_lock" 2>/dev/null || true',
    '}',
    'pd_debug_finish() {',
    '  [ "$pd_debug" -eq 1 ] || return 0',
    '  pd_finished_ms=$(pd_debug_now_ms 2>/dev/null) || return 0',
    '  pd_debug_append finish "$pd_finished_ms" "$1" "$2"',
    '}',
    'pd_debug_skip() {',
    '  pd_debug_finish "$1" 0',
    '  exit 0',
    '}',
    '',
    '# Fail-open circuit breaker. The state format is intentionally tiny and',
    '# sanitized: lifecycle state and timing only, never hook input or output.',
    'pd_health_dir="$PD_HOME/squid/health"',
    'pd_state_file="$pd_health_dir/$pd_hook.state"',
    'pd_probe_dir="$pd_health_dir/$pd_hook.probe"',
    'pd_state_lock="$pd_health_dir/$pd_hook.state.lock"',
    'pd_notice_file="$pd_health_dir/remediation.notice"',
    'pd_breaker_state=closed',
    'pd_failure_count=0',
    'pd_opened_ms=0',
    'pd_retry_ms=0',
    'pd_last_reason=none',
    'pd_last_duration_ms=0',
    'pd_last_exit=-',
    'pd_updated_ms=0',
    'pd_is_probe=0',
    'pd_time_file="$pd_health_dir/$pd_hook.time.$$"',
    'pd_health_load() {',
    '  [ -f "$pd_state_file" ] || return 0',
    '  IFS="$(printf "\\t")" read -r pd_version pd_loaded_state pd_loaded_failures pd_loaded_opened pd_loaded_retry pd_loaded_reason pd_loaded_duration pd_loaded_exit pd_loaded_updated < "$pd_state_file" 2>/dev/null || return 0',
    '  [ "$pd_version" = v1 ] || return 0',
    '  case "$pd_loaded_state" in closed|open) ;; *) return 0 ;; esac',
    '  case "$pd_loaded_failures:$pd_loaded_opened:$pd_loaded_retry:$pd_loaded_duration:$pd_loaded_updated" in *[!0-9:]*) return 0 ;; esac',
    '  case "$pd_loaded_reason" in ""|*[!a-z0-9_-]*) return 0 ;; esac',
    '  case "$pd_loaded_exit" in -|[0-9]|[0-9][0-9]|[0-9][0-9][0-9]) ;; *) return 0 ;; esac',
    '  pd_breaker_state=$pd_loaded_state',
    '  pd_failure_count=$pd_loaded_failures',
    '  pd_opened_ms=$pd_loaded_opened',
    '  pd_retry_ms=$pd_loaded_retry',
    '  pd_last_reason=$pd_loaded_reason',
    '  pd_last_duration_ms=$pd_loaded_duration',
    '  pd_last_exit=$pd_loaded_exit',
    '  pd_updated_ms=$pd_loaded_updated',
    '}',
    'pd_health_write() {',
    '  umask 077',
    '  mkdir -p "$pd_health_dir" 2>/dev/null || return 0',
    '  pd_state_tmp="$pd_state_file.$$"',
    '  printf "v1\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\t%s\\n" "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" > "$pd_state_tmp" 2>/dev/null || return 0',
    '  chmod 600 "$pd_state_tmp" 2>/dev/null || true',
    '  mv "$pd_state_tmp" "$pd_state_file" 2>/dev/null || rm -f "$pd_state_tmp" 2>/dev/null || true',
    '}',
    'pd_health_state_lock_acquire() {',
    '  pd_lock_attempt=0',
    '  while ! mkdir "$pd_state_lock" 2>/dev/null; do',
    '    pd_lock_attempt=$((pd_lock_attempt + 1))',
    '    pd_state_lock_now=$(date +%s 2>/dev/null || printf 0)',
    '    pd_state_lock_modified=$(stat -f %m "$pd_state_lock" 2>/dev/null || true)',
    '    case "$pd_state_lock_modified" in ""|*[!0-9]*) pd_state_lock_modified=$(stat -c %Y "$pd_state_lock" 2>/dev/null || true) ;; esac',
    '    case "$pd_state_lock_now:$pd_state_lock_modified" in *[!0-9:]*) ;; *) [ $((pd_state_lock_now - pd_state_lock_modified)) -gt 5 ] 2>/dev/null && rmdir "$pd_state_lock" 2>/dev/null ;; esac',
    '    [ "$pd_lock_attempt" -lt 20 ] || return 1',
    '    sleep 0.01',
    '  done',
    '}',
    'pd_health_state_lock_release() {',
    '  rmdir "$pd_state_lock" 2>/dev/null || true',
    '}',
    'pd_health_notice_open() {',
    '  case "$pd_hook" in pd-hook-prompt) pd_hook_label="PD TURN" ;; pd-hook-pre-tool) pd_hook_label="PD EDIT" ;; *) pd_hook_label="PD TRACE" ;; esac',
    '  umask 077',
    '  mkdir -p "$pd_health_dir" 2>/dev/null || return 0',
    '  pd_notice_tmp="$pd_notice_file.$$"',
    '  printf "◆ PD SAFE MODE · %s disabled after %s consecutive failed or slow calls. Open FleetBar > Giant Squid > Repair.\\n" "$pd_hook_label" "$pd_failure_count" > "$pd_notice_tmp" 2>/dev/null || return 0',
    '  chmod 600 "$pd_notice_tmp" 2>/dev/null || true',
    '  mv "$pd_notice_tmp" "$pd_notice_file" 2>/dev/null || rm -f "$pd_notice_tmp" 2>/dev/null || true',
    '}',
    'pd_health_notice_emit() {',
    '  [ "$pd_hook" = pd-hook-prompt ] || return 0',
    '  [ -f "$pd_notice_file" ] || return 0',
    '  pd_notice_claim="$pd_notice_file.emit.$$"',
    '  mv "$pd_notice_file" "$pd_notice_claim" 2>/dev/null || return 0',
    '  cat "$pd_notice_claim" 2>/dev/null || true',
    '  rm -f "$pd_notice_claim" 2>/dev/null || true',
    '}',
    'pd_health_record_unhealthy() {',
    '  pd_reason=$1',
    '  pd_exit_value=$2',
    '  pd_duration_value=$3',
    '  pd_health_state_lock_acquire || return 0',
    '  pd_health_load',
    '  pd_was_open=$pd_breaker_state',
    '  pd_health_now=$(pd_epoch_ms 2>/dev/null) || pd_health_now=0',
    '  pd_failure_count=$((pd_failure_count + 1))',
    '  if [ "$pd_is_probe" -eq 1 ] || [ "$pd_failure_count" -ge "$pd_failure_threshold" ]; then',
    '    pd_breaker_state=open',
    '    pd_opened_ms=$pd_health_now',
    '    pd_retry_ms=$((pd_health_now + pd_cooldown_ms))',
    '    pd_health_write open "$pd_failure_count" "$pd_opened_ms" "$pd_retry_ms" "$pd_reason" "$pd_duration_value" "$pd_exit_value" "$pd_health_now"',
    '    rmdir "$pd_probe_dir" 2>/dev/null || true',
    '    [ "$pd_was_open" = open ] || pd_health_notice_open',
    '  else',
    '    pd_health_write closed "$pd_failure_count" 0 0 "$pd_reason" "$pd_duration_value" "$pd_exit_value" "$pd_health_now"',
    '  fi',
    '  pd_health_state_lock_release',
    '}',
    'pd_health_record_healthy() {',
    '  if [ -f "$pd_state_file" ] || [ -d "$pd_probe_dir" ]; then',
    '    pd_health_state_lock_acquire || return 0',
    '    rm -f "$pd_state_file" 2>/dev/null || true',
    '    rmdir "$pd_probe_dir" 2>/dev/null || true',
    '    rm -f "$pd_notice_file" 2>/dev/null || true',
    '    pd_health_state_lock_release',
    '  fi',
    '}',
    'pd_health_probe_acquire() {',
    '  mkdir "$pd_probe_dir" 2>/dev/null && return 0',
    '  pd_probe_now=$(date +%s 2>/dev/null || printf 0)',
    '  pd_probe_modified=$(stat -f %m "$pd_probe_dir" 2>/dev/null || true)',
    '  case "$pd_probe_modified" in ""|*[!0-9]*) pd_probe_modified=$(stat -c %Y "$pd_probe_dir" 2>/dev/null || true) ;; esac',
    '  case "$pd_probe_now:$pd_probe_modified" in *[!0-9:]*) return 1 ;; esac',
    '  [ $((pd_probe_now - pd_probe_modified)) -gt 5 ] 2>/dev/null || return 1',
    '  rmdir "$pd_probe_dir" 2>/dev/null || return 1',
    '  mkdir "$pd_probe_dir" 2>/dev/null',
    '}',
    'pd_health_duration_read() {',
    '  pd_duration_ms=0',
    '  pd_elapsed=',
    '  while IFS=" " read -r pd_time_kind pd_time_value; do',
    '    if [ "$pd_time_kind" = real ]; then pd_elapsed=$pd_time_value; break; fi',
    '  done < "$pd_time_file" 2>/dev/null || true',
    '  rm -f "$pd_time_file" 2>/dev/null || true',
    '  case "$pd_elapsed" in',
    '    [0-9]*.[0-9][0-9])',
    '      pd_seconds=${pd_elapsed%.*}',
    '      pd_hundredths=${pd_elapsed#*.}',
    '      case "$pd_seconds:$pd_hundredths" in *[!0-9:]*) return 0 ;; esac',
    '      pd_seconds=${pd_seconds#0}; [ -n "$pd_seconds" ] || pd_seconds=0',
    '      pd_hundredths=${pd_hundredths#0}; [ -n "$pd_hundredths" ] || pd_hundredths=0',
    '      pd_duration_ms=$((pd_seconds * 1000 + pd_hundredths * 10))',
    '      ;;',
    '  esac',
    '}',
    'pd_health_signal() {',
    '  trap - HUP INT TERM',
    '  rm -f "$pd_time_file" 2>/dev/null || true',
    '  pd_health_record_unhealthy signal 124 "$pd_slow_ms"',
    '  pd_debug_finish interrupted 124',
    '  exit 0',
    '}',
    'if [ -f "$pd_debug_dir/debug.enabled" ]; then',
    '  pd_debug=1',
    '  pd_started_ms=$(pd_debug_now_ms 2>/dev/null) || pd_started_ms="$(date +%s)000"',
    '  # Debug mode buffers hook JSON in memory only so the real tentacle still',
    '  # receives stdin. Only a validated session identifier leaves that buffer.',
    '  pd_input=$(cat 2>/dev/null || true)',
    '  pd_session_candidate=""',
    '  if [ -x /usr/bin/perl ]; then',
    '    pd_session_candidate=$(printf "%s" "$pd_input" | /usr/bin/perl -MJSON::PP -0777 -e \'eval { my $d = decode_json(<>); my $v = $d->{session_id} // $d->{sessionId} // $d->{thread_id} // $d->{threadId} // $d->{conversationId}; print $v if defined($v) && !ref($v); };\' 2>/dev/null || true)',
    '  fi',
    '  case "$pd_session_candidate" in ""|*[!A-Za-z0-9._:-]*|?????????????????????????????????????????????????????????????????????????????????*) pd_session_candidate="$PPID" ;; esac',
    '  pd_session_id="${pd_provider}:${pd_session_candidate}"',
    '  pd_run_id="${pd_provider}-${pd_phase}-${PPID}-$$-${pd_started_ms}"',
    '  pd_workspace_b64=$(printf "%s" "$PWD" | base64 2>/dev/null | tr -d "\\r\\n")',
    '  pd_debug_append start "$pd_started_ms" - -',
    'fi',
    '',
    '# (a) daemon alive? Use the Bosun heartbeat; process probes are sandbox-denied.',
    'heartbeat="$PD_HOME/heartbeat"',
    '[ -f "$heartbeat" ] || pd_debug_skip heartbeat_missing',
    'now=$(date +%s 2>/dev/null) || pd_debug_skip heartbeat_unreadable',
    'modified=$(stat -f %m "$heartbeat" 2>/dev/null || true)',
    'case "$modified" in ""|*[!0-9]*) modified=$(stat -c %Y "$heartbeat" 2>/dev/null || true) ;; esac',
    'case "$modified" in ""|*[!0-9]*) pd_debug_skip heartbeat_unreadable ;; esac',
    'age=$((now - modified))',
    `[ "$age" -ge -${SQUID_DAEMON_HEARTBEAT_STALE_SECONDS} ] 2>/dev/null || pd_debug_skip daemon_stale`,
    `[ "$age" -le ${SQUID_DAEMON_HEARTBEAT_STALE_SECONDS} ] 2>/dev/null || pd_debug_skip daemon_stale`,
    '# (b) cwd inside a project explicitly armed by `pd squid on`?',
    'd=$PWD',
    'while [ -n "$d" ] && [ "$d" != "/" ]; do',
    '  if [ -d "$d/.portdaddy" ]; then',
    '    project_root=$(cd "$d" 2>/dev/null && pwd -P) || pd_debug_skip project_unreadable',
    '    registry="$PD_HOME/squid/projects"',
    '    [ -f "$registry" ] || pd_debug_skip registry_missing',
    '    pd_project_armed=0',
    '    while IFS= read -r pd_registered_project; do',
    '      if [ "$pd_registered_project" = "$project_root" ]; then pd_project_armed=1; break; fi',
    '    done < "$registry" 2>/dev/null || true',
    '    [ "$pd_project_armed" -eq 1 ] || pd_debug_skip project_disarmed',
    '    pd_health_load',
    '    pd_health_notice_emit',
    '    if [ "$pd_breaker_state" = open ]; then',
    '      pd_health_now=$(pd_epoch_ms 2>/dev/null) || pd_health_now=0',
    '      [ "$pd_health_now" -ge "$pd_retry_ms" ] 2>/dev/null || pd_debug_skip circuit_open',
    '      mkdir -p "$pd_health_dir" 2>/dev/null || pd_debug_skip circuit_open',
    '      pd_health_probe_acquire || pd_debug_skip half_open_busy',
    '      pd_is_probe=1',
    '    fi',
    '    [ -d "$pd_health_dir" ] || mkdir -p "$pd_health_dir" 2>/dev/null || true',
    '    trap pd_health_signal HUP INT TERM',
    '    pd_real_hook="$PD_HOME/bin/squid/${0##*/}"',
    '    if [ ! -x "$pd_real_hook" ]; then',
    '      printf "real 0.00\\nuser 0.00\\nsys 0.00\\n" > "$pd_time_file" 2>/dev/null || true',
    '      pd_exit=127',
    '    elif [ "$pd_debug" -eq 1 ]; then',
    '      { time -p printf "%s" "$pd_input" | "$pd_real_hook" "$@" 2>&3; } 3>&2 2> "$pd_time_file"',
    '      pd_exit=$?',
    '    else',
    '      { time -p "$pd_real_hook" "$@" 2>&3; } 3>&2 2> "$pd_time_file"',
    '      pd_exit=$?',
    '    fi',
    '    trap - HUP INT TERM',
    '    pd_health_duration_read',
    '    if [ "$pd_exit" -eq 2 ]; then',
    '      pd_health_record_healthy',
    '      pd_debug_finish blocked 2',
    '      exit 2',
    '    fi',
    '    if [ "$pd_exit" -eq 0 ] && [ "$pd_duration_ms" -lt "$pd_slow_ms" ]; then',
    '      pd_health_record_healthy',
    '      pd_debug_finish executed 0',
    '      exit 0',
    '    fi',
    '    if [ "$pd_exit" -eq 0 ]; then',
    '      pd_health_record_unhealthy slow 0 "$pd_duration_ms"',
    '      pd_debug_finish slow 0',
    '      exit 0',
    '    fi',
    '    pd_health_record_unhealthy "exit_$pd_exit" "$pd_exit" "$pd_duration_ms"',
    '    pd_debug_finish failure_swallowed "$pd_exit"',
    '    exit 0',
    '  fi',
    '  d=${d%/*}; [ -n "$d" ] || d=/',
    'done',
    '# not a pd project (or daemon down) -> no-op; allow the tool (fail open).',
    'pd_debug_skip no_project',
    '',
  ].join('\n');
}

// ─── Per-project arm registry ────────────────────────────────────────────────

export function squidProjectRegistryPath(pdHome = PD_HOME): string {
  return join(pdHome, 'squid', 'projects');
}

function canonicalProjectRoot(cwd: string): string {
  const absolute = resolve(cwd);
  try { return realpathSync(absolute); } catch { return absolute; }
}

export function readArmedSquidProjects(registryPath = squidProjectRegistryPath()): string[] {
  if (!existsSync(registryPath)) return [];
  try {
    return [...new Set(readFileSync(registryPath, 'utf8').split('\n').map((line) => line.trim()).filter(Boolean))].sort();
  } catch {
    return [];
  }
}

export function registerSquidProject(cwd: string, registryPath = squidProjectRegistryPath()): string {
  const project = canonicalProjectRoot(cwd);
  const projects = [...new Set([...readArmedSquidProjects(registryPath), project])].sort();
  mkdirSync(dirname(registryPath), { recursive: true });
  writeFileSync(registryPath, `${projects.join('\n')}\n`, { mode: 0o600 });
  chmodSync(registryPath, 0o600);
  return project;
}

export function unregisterSquidProject(cwd: string, registryPath = squidProjectRegistryPath()): boolean {
  const project = canonicalProjectRoot(cwd);
  const before = readArmedSquidProjects(registryPath);
  const after = before.filter((entry) => entry !== project);
  if (after.length === before.length) return false;
  if (after.length === 0) rmSync(registryPath, { force: true });
  else {
    writeFileSync(registryPath, `${after.join('\n')}\n`, { mode: 0o600 });
    chmodSync(registryPath, 0o600);
  }
  return true;
}

export function clearArmedSquidProjects(registryPath = squidProjectRegistryPath()): void {
  rmSync(registryPath, { force: true });
}

export function isSquidProjectArmed(cwd: string, registryPath = squidProjectRegistryPath()): boolean {
  return readArmedSquidProjects(registryPath).includes(canonicalProjectRoot(cwd));
}

// ─── Tentacle staging ────────────────────────────────────────────────────────

export interface StageResult {
  staged: string[];
  missing: TentacleName[];
  sourceDir: string;
}

/**
 * Copy the real tentacles to ~/.port-daddy/bin/squid/ and (re)write the gate
 * wrappers to ~/.port-daddy/bin/. The tentacles are owned by the squid program;
 * this installer only consumes them. If they are absent on this build, nothing
 * is staged and the caller surfaces guidance.
 */
export function stageTentacles(
  sourceDir?: string,
  destBinDir = tentacleBinDir(),
): StageResult {
  const resolved = TENTACLES.map((name) => {
    const explicit = sourceDir ? join(sourceDir, name) : null;
    const source = explicit ? (existsSync(explicit) ? explicit : null) : resolveSquidAsset(join('bin', name));
    return { name, source };
  });
  const missing = resolved.filter((candidate) => candidate.source === null).map((candidate) => candidate.name);
  if (missing.length > 0) {
    return { staged: [], missing, sourceDir: sourceDir ?? 'runtime asset resolver' };
  }

  const realDir = join(destBinDir, 'squid');
  const binDir = destBinDir;
  const healthDir = join(dirname(binDir), 'squid', 'health');
  mkdirSync(realDir, { recursive: true });
  mkdirSync(binDir, { recursive: true });
  mkdirSync(healthDir, { recursive: true, mode: 0o700 });
  chmodSync(healthDir, 0o700);

  const staged: string[] = [];
  const suffix = `.stage-${process.pid}-${Date.now()}`;
  const temporary: string[] = [];
  try {
    for (const { name, source } of resolved) {
      const src = source as string;
      const realDst = join(realDir, name);
      const realTmp = `${realDst}${suffix}`;
      const wrapper = join(binDir, name);
      const wrapperTmp = `${wrapper}${suffix}`;
      copyFileSync(src, realTmp);
      chmodSync(realTmp, 0o755);
      writeFileSync(wrapperTmp, gateWrapperScript(), { mode: 0o755 });
      chmodSync(wrapperTmp, 0o755);
      temporary.push(realTmp, wrapperTmp);
    }

    for (const { name } of resolved) {
      const realDst = join(realDir, name);
      const wrapper = join(binDir, name);
      renameSync(`${realDst}${suffix}`, realDst);
      renameSync(`${wrapper}${suffix}`, wrapper);
      staged.push(wrapper);
    }
  } finally {
    for (const path of temporary) rmSync(path, { force: true });
  }
  return { staged, missing, sourceDir: sourceDir ?? 'runtime asset resolver' };
}

// ─── Target definitions ──────────────────────────────────────────────────────

type HookFormat = 'json' | 'codex-toml';
type Vendor = 'claude' | 'gemini' | 'agy';

export interface AgentCliTarget {
  name: string;
  slug: string;
  bin: string;
  format: HookFormat;
  vendor?: Vendor; // JSON vendors only
  userConfigPath: string;
  /** Project-level config, or null when the CLI has no useful project-interactive surface. */
  projectConfigPath: ((cwd: string) => string) | null;
  detect(): boolean;
  note?: string;
}

function commandExists(bin: string): boolean {
  try {
    execFileSync('command', ['-v', bin], { stdio: ['pipe', 'pipe', 'pipe'], shell: '/bin/sh' });
    return true;
  } catch {
    try {
      execFileSync('which', [bin], { stdio: ['pipe', 'pipe', 'pipe'] });
      return true;
    } catch {
      return false;
    }
  }
}

export function buildTargets(home: string): AgentCliTarget[] {
  return [
    {
      name: 'Claude Code',
      slug: 'claude',
      bin: 'claude',
      format: 'json',
      vendor: 'claude',
      userConfigPath: join(home, '.claude', 'settings.json'),
      projectConfigPath: (cwd) => join(cwd, '.claude', 'settings.json'),
      detect: () => commandExists('claude'),
    },
    {
      name: 'Codex CLI',
      slug: 'codex',
      bin: 'codex',
      format: 'codex-toml',
      userConfigPath: join(home, '.codex', 'config.toml'),
      // repo-local hooks don't fire interactively (openai/codex#17532) — user-level
      // only; the runtime gate keeps it per-project.
      projectConfigPath: null,
      detect: () => commandExists('codex'),
      note: 'user-level ~/.codex (repo-local does not fire interactively, openai/codex#17532); trust once via /hooks',
    },
    {
      name: 'Gemini CLI',
      slug: 'gemini',
      bin: 'gemini',
      format: 'json',
      vendor: 'gemini',
      userConfigPath: join(home, '.gemini', 'settings.json'),
      projectConfigPath: (cwd) => join(cwd, '.gemini', 'settings.json'),
      detect: () => commandExists('gemini'),
    },
    {
      name: 'Antigravity (agy)',
      slug: 'agy',
      bin: 'agy',
      format: 'json',
      vendor: 'agy',
      userConfigPath: join(home, '.gemini', 'hooks.json'), // home-scoped engine file
      projectConfigPath: null,
      detect: () => commandExists('agy'),
      note: 'home-scoped ~/.gemini/hooks.json; runtime gate keeps it per-project',
    },
  ];
}

// ─── Configure a single target ───────────────────────────────────────────────

export interface ConfigureResult {
  success: boolean;
  created?: boolean;
  path: string;
  error?: string;
  skipped?: string;
}

function shellQuote(value: string): string {
  return `'${value.replace(/'/g, `'"'"'`)}'`;
}

/** Resolver pointing hook commands at the gate and attaching only static metadata. */
function gateResolverFor(provider: string): TentacleResolver {
  return (name) => [
    `PD_HOOK_PROVIDER=${provider}`,
    `PD_HOOK_DEADLINE_MS=${SQUID_HOOK_DEADLINE_MS}`,
    shellQuote(gatePath(name)),
  ].join(' ');
}

function atomicWriteConfig(path: string, content: string): void {
  mkdirSync(dirname(path), { recursive: true });
  const temporary = join(dirname(path), `.${basename(path)}.pd-${process.pid}-${Date.now()}.tmp`);
  try {
    writeFileSync(temporary, content, { mode: 0o600 });
    renameSync(temporary, path);
  } finally {
    rmSync(temporary, { force: true });
  }
}

/**
 * Codex once loaded ~/.codex/hooks.json; current Codex uses config.toml. Remove
 * only Port Daddy entries from that legacy surface when present so an upgrade
 * cannot fire both generations of synchronous hooks. User hooks survive.
 */
function migratedLegacyCodexHooksJson(configPath: string): { path: string; content: string } | null {
  const path = join(dirname(configPath), 'hooks.json');
  if (!existsSync(path)) return null;
  const raw = readFileSync(path, 'utf-8').trim();
  let config: Record<string, unknown>;
  try {
    config = raw ? (JSON.parse(raw) as Record<string, unknown>) : {};
  } catch {
    // A malformed retired surface cannot be active, and must not prevent the
    // current TOML hook registration from being repaired. Preserve it exactly.
    return null;
  }
  if (!removeJsonHooks(config)) return null;
  return { path, content: JSON.stringify(config, null, 2) + '\n' };
}

/**
 * Install the current Codex TOML before retiring the legacy JSON registration.
 * Each write is atomic on its own. This order means an interrupted first write
 * leaves the still-working legacy hooks untouched; an interrupted cleanup may
 * briefly leave duplicates, but can never leave Codex with no Port Daddy hook.
 */
export function commitCodexConfigMigration(
  configPath: string,
  configContent: string,
  legacy: { path: string; content: string } | null,
  writeConfig: (path: string, content: string) => void = atomicWriteConfig,
): void {
  writeConfig(configPath, configContent);
  if (legacy) writeConfig(legacy.path, legacy.content);
}

export function configureTarget(
  target: AgentCliTarget,
  opts: { scope: 'user' | 'project'; cwd?: string },
): ConfigureResult {
  let configPath: string;
  if (opts.scope === 'user') {
    configPath = target.userConfigPath;
  } else {
    if (!target.projectConfigPath) {
      return { success: true, path: '', skipped: 'no interactive project surface' };
    }
    configPath = target.projectConfigPath(opts.cwd ?? process.cwd());
  }

  try {
    const existed = existsSync(configPath);
    mkdirSync(dirname(configPath), { recursive: true });

    if (target.format === 'codex-toml') {
      const existing = existed ? readFileSync(configPath, 'utf-8') : '';
      const base = stripCodexHooksTomlBlock(existing).replace(/\s*$/, '');
      const sep = base.length ? '\n\n' : '';
      const legacy = migratedLegacyCodexHooksJson(configPath);
      commitCodexConfigMigration(
        configPath,
        `${base}${sep}${codexHooksTomlBlock(gateResolverFor(target.slug))}\n`,
        legacy,
      );
      return { success: true, created: !existed, path: configPath };
    }

    let config: Record<string, unknown> = {};
    if (existed) {
      const raw = readFileSync(configPath, 'utf-8').trim();
      if (raw) config = JSON.parse(raw) as Record<string, unknown>;
    }
    upsertJsonHookMap(config, buildJsonHookMap(target.vendor!, gateResolverFor(target.slug)));
    atomicWriteConfig(configPath, JSON.stringify(config, null, 2) + '\n');
    return { success: true, created: !existed, path: configPath };
  } catch (err) {
    return { success: false, path: configPath, error: (err as Error).message };
  }
}

export function uninstallTarget(
  target: AgentCliTarget,
  opts: { scope: 'user' | 'project'; cwd?: string },
): ConfigureResult {
  let configPath: string;
  if (opts.scope === 'user') configPath = target.userConfigPath;
  else if (target.projectConfigPath) configPath = target.projectConfigPath(opts.cwd ?? process.cwd());
  else if (target.format === 'codex-toml') {
    // Current Codex reads user config, but releases before 3.30 also wrote a
    // project-local TOML block. Sweep that retired surface so a cached or future
    // project loader cannot keep calling a deleted Homebrew Cellar path.
    configPath = join(opts.cwd ?? process.cwd(), '.codex', 'config.toml');
  } else return { success: true, path: '', skipped: 'no project surface' };

  if (!existsSync(configPath)) return { success: true, path: configPath, skipped: 'no config' };

  try {
    if (target.format === 'codex-toml') {
      const legacy = migratedLegacyCodexHooksJson(configPath);
      commitCodexConfigMigration(
        configPath,
        stripCodexHooksTomlBlock(readFileSync(configPath, 'utf-8')),
        legacy,
      );
      return { success: true, path: configPath };
    }
    const raw = readFileSync(configPath, 'utf-8').trim();
    const config = raw ? (JSON.parse(raw) as Record<string, unknown>) : {};
    removeJsonHooks(config);
    atomicWriteConfig(configPath, JSON.stringify(config, null, 2) + '\n');
    return { success: true, path: configPath };
  } catch (err) {
    return { success: false, path: configPath, error: (err as Error).message };
  }
}

/**
 * Write the right scopes for a target: project where it has a project surface
 * (claude/gemini), user-level where it must be global (codex/agy). Everything is
 * runtime-gated to pd projects regardless of where the config lives.
 */
function wireTarget(target: AgentCliTarget, cwd: string, alsoUser: boolean): ConfigureResult[] {
  const out: ConfigureResult[] = [];
  if (target.projectConfigPath) {
    out.push(configureTarget(target, { scope: 'project', cwd }));
    if (alsoUser) out.push(configureTarget(target, { scope: 'user' }));
  } else {
    // codex/agy: user-level is the only interactive surface; the gate scopes it.
    if (target.format === 'codex-toml') {
      const cleanup = uninstallTarget(target, { scope: 'project', cwd });
      if (!cleanup.success) out.push(cleanup);
    }
    out.push(configureTarget(target, { scope: 'user' }));
  }
  return out;
}

// ─── Silent install (pd init) ────────────────────────────────────────────────

export interface SilentHooksResult {
  configured: number;
  detected: string[];
  tentaclesMissing: boolean;
  failures: string[];
}

export interface HookTargetStatus {
  name: string;
  slug: string;
  detected: boolean;
  projectPath: string | null;
  userPath: string;
  projectWired: boolean;
  userWired: boolean;
  expectedScope: 'project' | 'user';
  wired: boolean;
  note?: string;
  projectArmed: boolean;
}

function configCarriesPdHook(path: string): boolean {
  try {
    return existsSync(path) && readFileSync(path, 'utf8').includes(PD_HOOK_MARKER);
  } catch {
    return false;
  }
}

/** Read-only truth used by `pd squid status --json` and operator surfaces. */
export function inspectHookTargets(home = DEFAULT_HOME, cwd = process.cwd()): HookTargetStatus[] {
  const projectArmed = isSquidProjectArmed(cwd);
  return buildTargets(home).map((target) => {
    const projectPath = target.projectConfigPath?.(cwd) ?? null;
    const projectWired = projectPath ? configCarriesPdHook(projectPath) : false;
    const userWired = configCarriesPdHook(target.userConfigPath);
    const expectedScope = target.projectConfigPath ? 'project' : 'user';
    return {
      name: target.name,
      slug: target.slug,
      detected: target.detect(),
      projectPath,
      userPath: target.userConfigPath,
      projectWired,
      userWired,
      expectedScope,
      wired: projectArmed && (expectedScope === 'project' ? projectWired : userWired),
      note: target.note,
      projectArmed,
    };
  });
}

/**
 * Wire detected CLIs for a specific project (pd init). Project-level for
 * claude/gemini; gated user-level for codex/agy. Never global-by-default.
 */
export function silentHooksInstall(
  home = DEFAULT_HOME,
  opts: { cwd?: string; stage?: StageResult; resetHealthOnSuccess?: boolean } = {},
): SilentHooksResult {
  const cwd = opts.cwd ?? process.cwd();
  // `pd squid on` already stages once for the whole arm transaction. Reuse
  // that fulfilled result instead of repeating release-asset discovery/copies.
  const stage = opts.stage ?? stageTentacles();
  const detected = buildTargets(home).filter((t) => t.detect());
  const result: SilentHooksResult = {
    configured: 0,
    detected: detected.map((t) => t.slug),
    tentaclesMissing: stage.missing.length > 0,
    failures: [],
  };
  if (result.tentaclesMissing || detected.length === 0) return result;
  registerSquidProject(cwd);

  for (const target of detected) {
    const results = wireTarget(target, cwd, false);
    if (results.some((r) => r.success && !r.skipped)) result.configured++;
    for (const failure of results.filter((r) => !r.success)) {
      result.failures.push(`${target.slug}: ${failure.error ?? 'configuration failed'}`);
    }
  }
  if (result.failures.length > 0 || result.configured < detected.length) {
    unregisterSquidProject(cwd);
  } else if (opts.resetHealthOnSuccess !== false) {
    resetSquidHookHealth();
  }
  return result;
}

// ─── Interactive command (pd hooks ...) ──────────────────────────────────────

export async function handleHooks(
  positional: string[],
  options: Record<string, unknown>,
  home = DEFAULT_HOME,
): Promise<void> {
  const sub = positional[0] ?? 'install';
  const targets = buildTargets(home);

  if (isHooksStatusRequest(sub, options)) {
    console.log('');
    ui.info('Port Daddy agent-CLI hooks (per-project, daemon-gated)');
    console.log('');
    const cwd = process.cwd();
    console.log(`  This project: ${isSquidProjectArmed(cwd) ? '\x1b[32mARMED\x1b[0m' : '\x1b[2mnot armed\x1b[0m'} (${canonicalProjectRoot(cwd)})`);
    console.log('');
    for (const t of targets) {
      const present = t.detect();
      const status = present ? '\x1b[32m✓ installed\x1b[0m' : '\x1b[2m- not found\x1b[0m';
      const wired =
        existsSync(t.userConfigPath) && readFileSync(t.userConfigPath, 'utf-8').includes(PD_HOOK_MARKER)
          ? ' \x1b[32m(user-wired)\x1b[0m'
          : '';
      console.log(`    ${t.name.padEnd(22)} ${status}${wired}`);
      if (present && t.note) console.log(`      \x1b[2m${t.note}\x1b[0m`);
    }
    console.log('');
    return;
  }

  if (sub === 'uninstall' || sub === 'remove') {
    console.log('');
    ui.info('Removing Port Daddy hooks from all agent CLIs');
    const cwd = process.cwd();
    for (const t of targets) {
      for (const scope of ['user', 'project'] as const) {
        const r = uninstallTarget(t, { scope, cwd });
        if (r.success && !r.skipped) ui.success(`${t.name} (${scope}): cleared ${r.path}`);
      }
    }
    clearArmedSquidProjects();
    console.log('');
    return;
  }

  // install
  console.log('');
  ui.info('Port Daddy — agent-CLI interactive hooks (this project)');
  console.log('');

  const detected = targets.filter((t) => t.detect());
  if (detected.length === 0) {
    ui.warn('No agent CLIs detected (looked for claude, codex, gemini, agy).');
    console.log('');
    process.exitCode = 1;
    return;
  }

  const cwd = process.cwd();
  console.log('  Detected: ' + detected.map((t) => t.name).join(', '));
  console.log(`  Wires coordination into their interactive sessions for THIS project (${cwd}).`);
  console.log('  Hooks are inert unless the pd daemon is running and this exact project root is armed.');
  console.log('');

  const assumeYes = !!options.yes || !!options.y || !ui.canPrompt();
  const proceed = assumeYes ? true : await ui.confirm('Wire coordination hooks for this project?', true);
  if (!proceed) {
    ui.info('Skipped. Run `pd hooks install` any time.');
    return;
  }

  const stage = stageTentacles();
  if (stage.missing.length > 0) {
    ui.warn(`Squid tentacles not found on this build (${stage.missing.join(', ')}).`);
    console.log('  The hook scripts (bin/pd-hook-*) ship with the Giant Squid Harness.');
    console.log('  Update Port Daddy, then re-run `pd hooks install`.');
    console.log('');
    process.exitCode = 1;
    return;
  }
  ui.success(`Staged tentacles + gate → ${tentacleBinDir()}`);
  registerSquidProject(cwd);

  const alsoUser = !!options.user;
  const failures: string[] = [];
  console.log('');
  console.log('  Wiring hooks:');
  for (const target of detected) {
    const results = wireTarget(target, cwd, alsoUser);
    for (const r of results) {
      if (r.skipped) continue;
      if (r.success) console.log(`    \x1b[32m✓\x1b[0m ${target.name.padEnd(22)} ${r.path}`);
      else {
        failures.push(`${target.slug}: ${r.error ?? 'configuration failed'}`);
        console.log(`    \x1b[31m✗\x1b[0m ${target.name.padEnd(22)} ${r.error}`);
      }
    }
    if (target.note) console.log(`      \x1b[2m${target.note}\x1b[0m`);
  }

  console.log('');
  if (failures.length > 0) {
    unregisterSquidProject(cwd);
    ui.warn(`Hook installation failed closed; this project remains inert (${failures.join('; ')}).`);
    process.exitCode = 1;
  } else {
    resetSquidHookHealth();
    ui.success('Coordination hooks wired for this project (active only when the daemon is up).');
  }
  if (detected.some((t) => t.slug === 'codex')) {
    console.log('  Codex: run `codex` → `/hooks` once to trust the pd hooks (persisted thereafter).');
  }
  console.log('  Verify:  pd hooks list   ·   Remove:  pd hooks uninstall');
  console.log('');
}

export function isHooksStatusRequest(sub: string, options: Record<string, unknown>): boolean {
  return sub === 'list' || sub === 'status' || !!options.list || !!options.status;
}
