/**
 * pd hooks install — Per-project, daemon-gated coordination hooks for agent CLIs
 *
 * Wires the Giant Squid Harness tentacles into the INTERACTIVE sessions of the
 * agent CLIs on this machine (Claude Code, Codex, Gemini, Antigravity/agy). The
 * hook SHAPES come from one shared source of truth — lib/squid/hook-shape.ts —
 * which the squid headless adapter uses too, so the interactive and headless
 * injectors can never drift.
 *
 * Two guarantees the user asked for:
 *   1. PER PROJECT. Claude/Gemini get project-level config written into the repo
 *      (`<repo>/.claude/settings.json`, `<repo>/.gemini/settings.json`). Codex
 *      (repo-local hooks don't fire interactively — openai/codex#17532) and agy
 *      (home-scoped `~/.gemini/hooks.json`) must be user-level, so they are
 *      constrained at RUNTIME by the gate below.
 *   2. INERT UNLESS PORT DADDY IS RUNNING. Every hook command points at a gate
 *      wrapper, not the tentacle directly. The wrapper no-ops (allow / no
 *      context) unless (a) the pd daemon is alive AND (b) the cwd is inside a
 *      pd-enabled project (a `.portdaddy/` marker on the path). So the hooks do
 *      nothing in non-pd projects or when the daemon is down.
 *
 * Layout under ~/.port-daddy/bin/:
 *   squid/pd-hook-{prompt,pre-tool,post-tool}   <- the real tentacles (copied)
 *   pd-hook-{prompt,pre-tool,post-tool}         <- generated gate wrappers
 * Hook configs point at the gate wrappers.
 *
 * Usage:
 *   pd hooks install            # wire detected CLIs for THIS project (+gated user cfg)
 *   pd hooks install --user     # also write user-level config for claude/gemini
 *   pd hooks list               # detection + wiring status
 *   pd hooks uninstall          # remove Port Daddy hooks from every surface
 */

import {
  existsSync,
  readFileSync,
  writeFileSync,
  mkdirSync,
  copyFileSync,
  chmodSync,
  realpathSync,
  rmSync,
} from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';
import * as ui from '../utils/ui.js';
import { PD_HOME } from '../../shared/paths.js';
import {
  TENTACLES,
  type TentacleName,
  type TentacleResolver,
  PD_HOOK_MARKER,
  CODEX_PD_MARKER,
  buildJsonHookMap,
  codexHooksTomlBlock,
  upsertJsonHookMap,
  removeJsonHooks,
  stripCodexHooksTomlBlock,
} from '../../lib/squid/hook-shape.js';
import { resolveSquidAsset } from '../../lib/squid/assets.js';

const DEFAULT_HOME = process.env.HOME || process.env.USERPROFILE || '';
const SQUID_DAEMON_HEARTBEAT_STALE_SECONDS = 30;

/** ~/.port-daddy/bin — staged gate wrappers (what hook configs point at). */
export function tentacleBinDir(): string {
  return join(PD_HOME, 'bin');
}
/** ~/.port-daddy/bin/squid — the real tentacles the wrappers delegate to. */
function realTentacleDir(): string {
  return join(PD_HOME, 'bin', 'squid');
}
/** The gate-wrapper path a hook config invokes for a given tentacle. */
function gatePath(name: TentacleName): string {
  return join(tentacleBinDir(), name);
}

// ─── Gate wrapper (pd-running + per-project) ─────────────────────────────────

/**
 * The shell gate. It runs on every tool call, so it is filesystem-only and
 * spawns no `pd` process. It allows/no-ops (exit 0) unless the daemon heartbeat
 * is fresh and the cwd is inside a pd-enabled project, then execs the real
 * tentacle with stdin/argv intact.
 *
 * Do not use `kill -0` or `ps` here. Codex's macOS Seatbelt profile denies both
 * against the Homebrew daemon even though it is owned by the same user, which
 * made every Codex hook silently fail open. The daemon heartbeat is specifically
 * designed as the filesystem-only liveness contract for sandboxed observers.
 */
function gateWrapperScript(): string {
  return [
    '#!/bin/sh',
    '# Port Daddy hook gate — GENERATED by `pd hooks install`. Do not edit.',
    '# Makes coordination hooks per-project and inert unless the daemon is up.',
    'PD_HOME="${PD_HOME:-$HOME/.port-daddy}"',
    '# (a) daemon alive? Use the daemon heartbeat; process probes are sandbox-denied.',
    'heartbeat="$PD_HOME/heartbeat"',
    '[ -f "$heartbeat" ] || exit 0',
    'now=$(date +%s 2>/dev/null) || exit 0',
    'modified=$(stat -f %m "$heartbeat" 2>/dev/null || true)',
    'case "$modified" in ""|*[!0-9]*) modified=$(stat -c %Y "$heartbeat" 2>/dev/null || true) ;; esac',
    'case "$modified" in ""|*[!0-9]*) exit 0 ;; esac',
    'age=$((now - modified))',
    `[ "$age" -ge -${SQUID_DAEMON_HEARTBEAT_STALE_SECONDS} ] 2>/dev/null || exit 0`,
    `[ "$age" -le ${SQUID_DAEMON_HEARTBEAT_STALE_SECONDS} ] 2>/dev/null || exit 0`,
    '# (b) cwd inside a project explicitly armed by `pd squid on`?',
    'd=$PWD',
    'while [ -n "$d" ] && [ "$d" != "/" ]; do',
    '  if [ -d "$d/.portdaddy" ]; then',
    '    project_root=$(cd "$d" 2>/dev/null && pwd -P) || exit 0',
    '    registry="$PD_HOME/squid/projects"',
    '    [ -f "$registry" ] || exit 0',
    '    grep -Fqx "$project_root" "$registry" 2>/dev/null || exit 0',
    '    exec "$PD_HOME/bin/squid/${0##*/}" "$@"',
    '  fi',
    '  d=$(dirname "$d")',
    'done',
    '# not a pd project (or daemon down) -> no-op; allow the tool (fail open).',
    'exit 0',
    '',
  ].join('\n');
}

// ─── Per-project arm registry ────────────────────────────────────────────────

export function squidProjectRegistryPath(pdHome = PD_HOME): string {
  return join(pdHome, 'squid', 'projects');
}

function canonicalProjectRoot(cwd: string): string {
  const absolute = resolve(cwd);
  try { return realpathSync(absolute); } catch { return absolute; }
}

export function readArmedSquidProjects(registryPath = squidProjectRegistryPath()): string[] {
  if (!existsSync(registryPath)) return [];
  try {
    return [...new Set(readFileSync(registryPath, 'utf8').split('\n').map((line) => line.trim()).filter(Boolean))].sort();
  } catch {
    return [];
  }
}

export function registerSquidProject(cwd: string, registryPath = squidProjectRegistryPath()): string {
  const project = canonicalProjectRoot(cwd);
  const projects = [...new Set([...readArmedSquidProjects(registryPath), project])].sort();
  mkdirSync(dirname(registryPath), { recursive: true });
  writeFileSync(registryPath, `${projects.join('\n')}\n`, { mode: 0o600 });
  chmodSync(registryPath, 0o600);
  return project;
}

export function unregisterSquidProject(cwd: string, registryPath = squidProjectRegistryPath()): boolean {
  const project = canonicalProjectRoot(cwd);
  const before = readArmedSquidProjects(registryPath);
  const after = before.filter((entry) => entry !== project);
  if (after.length === before.length) return false;
  if (after.length === 0) rmSync(registryPath, { force: true });
  else {
    writeFileSync(registryPath, `${after.join('\n')}\n`, { mode: 0o600 });
    chmodSync(registryPath, 0o600);
  }
  return true;
}

export function clearArmedSquidProjects(registryPath = squidProjectRegistryPath()): void {
  rmSync(registryPath, { force: true });
}

export function isSquidProjectArmed(cwd: string, registryPath = squidProjectRegistryPath()): boolean {
  return readArmedSquidProjects(registryPath).includes(canonicalProjectRoot(cwd));
}

// ─── Tentacle staging ────────────────────────────────────────────────────────

export interface StageResult {
  staged: string[];
  missing: TentacleName[];
  sourceDir: string;
}

/**
 * Copy the real tentacles to ~/.port-daddy/bin/squid/ and (re)write the gate
 * wrappers to ~/.port-daddy/bin/. The tentacles are owned by the squid program;
 * this installer only consumes them. If they are absent on this build, nothing
 * is staged and the caller surfaces guidance.
 */
export function stageTentacles(
  sourceDir?: string,
  destBinDir = tentacleBinDir(),
): StageResult {
  const realDir = join(destBinDir, 'squid');
  const binDir = destBinDir;
  mkdirSync(realDir, { recursive: true });
  mkdirSync(binDir, { recursive: true });

  const staged: string[] = [];
  const missing: TentacleName[] = [];

  for (const name of TENTACLES) {
    const explicit = sourceDir ? join(sourceDir, name) : null;
    const src = explicit ? (existsSync(explicit) ? explicit : null) : resolveSquidAsset(join('bin', name));
    if (!src) {
      missing.push(name);
      continue;
    }
    const realDst = join(realDir, name);
    copyFileSync(src, realDst);
    chmodSync(realDst, 0o755);
    // gate wrapper that delegates to the real tentacle
    const wrapper = join(binDir, name);
    writeFileSync(wrapper, gateWrapperScript(), { mode: 0o755 });
    chmodSync(wrapper, 0o755);
    staged.push(wrapper);
  }
  return { staged, missing, sourceDir: sourceDir ?? 'runtime asset resolver' };
}

// ─── Target definitions ──────────────────────────────────────────────────────

type HookFormat = 'json' | 'codex-toml';
type Vendor = 'claude' | 'gemini' | 'agy';

export interface AgentCliTarget {
  name: string;
  slug: string;
  bin: string;
  format: HookFormat;
  vendor?: Vendor; // JSON vendors only
  userConfigPath: string;
  /** Project-level config, or null when the CLI has no useful project-interactive surface. */
  projectConfigPath: ((cwd: string) => string) | null;
  detect(): boolean;
  note?: string;
}

function commandExists(bin: string): boolean {
  try {
    execFileSync('command', ['-v', bin], { stdio: ['pipe', 'pipe', 'pipe'], shell: '/bin/sh' });
    return true;
  } catch {
    try {
      execFileSync('which', [bin], { stdio: ['pipe', 'pipe', 'pipe'] });
      return true;
    } catch {
      return false;
    }
  }
}

export function buildTargets(home: string): AgentCliTarget[] {
  return [
    {
      name: 'Claude Code',
      slug: 'claude',
      bin: 'claude',
      format: 'json',
      vendor: 'claude',
      userConfigPath: join(home, '.claude', 'settings.json'),
      projectConfigPath: (cwd) => join(cwd, '.claude', 'settings.json'),
      detect: () => commandExists('claude'),
    },
    {
      name: 'Codex CLI',
      slug: 'codex',
      bin: 'codex',
      format: 'codex-toml',
      userConfigPath: join(home, '.codex', 'config.toml'),
      // repo-local hooks don't fire interactively (openai/codex#17532) — user-level
      // only; the runtime gate keeps it per-project.
      projectConfigPath: null,
      detect: () => commandExists('codex'),
      note: 'user-level ~/.codex (repo-local does not fire interactively, openai/codex#17532); trust once via /hooks',
    },
    {
      name: 'Gemini CLI',
      slug: 'gemini',
      bin: 'gemini',
      format: 'json',
      vendor: 'gemini',
      userConfigPath: join(home, '.gemini', 'settings.json'),
      projectConfigPath: (cwd) => join(cwd, '.gemini', 'settings.json'),
      detect: () => commandExists('gemini'),
    },
    {
      name: 'Antigravity (agy)',
      slug: 'agy',
      bin: 'agy',
      format: 'json',
      vendor: 'agy',
      userConfigPath: join(home, '.gemini', 'hooks.json'), // home-scoped engine file
      projectConfigPath: null,
      detect: () => commandExists('agy'),
      note: 'home-scoped ~/.gemini/hooks.json; runtime gate keeps it per-project',
    },
  ];
}

// ─── Configure a single target ───────────────────────────────────────────────

export interface ConfigureResult {
  success: boolean;
  created?: boolean;
  path: string;
  error?: string;
  skipped?: string;
}

/** Resolver pointing hook commands at the GATE WRAPPERS (not the raw tentacles). */
const gateResolver: TentacleResolver = (name) => gatePath(name);

export function configureTarget(
  target: AgentCliTarget,
  opts: { scope: 'user' | 'project'; cwd?: string },
): ConfigureResult {
  let configPath: string;
  if (opts.scope === 'user') {
    configPath = target.userConfigPath;
  } else {
    if (!target.projectConfigPath) {
      return { success: true, path: '', skipped: 'no interactive project surface' };
    }
    configPath = target.projectConfigPath(opts.cwd ?? process.cwd());
  }

  try {
    const existed = existsSync(configPath);
    mkdirSync(dirname(configPath), { recursive: true });

    if (target.format === 'codex-toml') {
      const existing = existed ? readFileSync(configPath, 'utf-8') : '';
      const base = stripCodexHooksTomlBlock(existing).replace(/\s*$/, '');
      const sep = base.length ? '\n\n' : '';
      writeFileSync(configPath, `${base}${sep}${codexHooksTomlBlock(gateResolver)}\n`);
      return { success: true, created: !existed, path: configPath };
    }

    let config: Record<string, unknown> = {};
    if (existed) {
      const raw = readFileSync(configPath, 'utf-8').trim();
      if (raw) config = JSON.parse(raw) as Record<string, unknown>;
    }
    upsertJsonHookMap(config, buildJsonHookMap(target.vendor!, gateResolver));
    writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');
    return { success: true, created: !existed, path: configPath };
  } catch (err) {
    return { success: false, path: configPath, error: (err as Error).message };
  }
}

export function uninstallTarget(
  target: AgentCliTarget,
  opts: { scope: 'user' | 'project'; cwd?: string },
): ConfigureResult {
  let configPath: string;
  if (opts.scope === 'user') configPath = target.userConfigPath;
  else if (target.projectConfigPath) configPath = target.projectConfigPath(opts.cwd ?? process.cwd());
  else return { success: true, path: '', skipped: 'no project surface' };

  if (!existsSync(configPath)) return { success: true, path: configPath, skipped: 'no config' };

  try {
    if (target.format === 'codex-toml') {
      writeFileSync(configPath, stripCodexHooksTomlBlock(readFileSync(configPath, 'utf-8')));
      return { success: true, path: configPath };
    }
    const raw = readFileSync(configPath, 'utf-8').trim();
    const config = raw ? (JSON.parse(raw) as Record<string, unknown>) : {};
    removeJsonHooks(config);
    writeFileSync(configPath, JSON.stringify(config, null, 2) + '\n');
    return { success: true, path: configPath };
  } catch (err) {
    return { success: false, path: configPath, error: (err as Error).message };
  }
}

/**
 * Write the right scopes for a target: project where it has a project surface
 * (claude/gemini), user-level where it must be global (codex/agy). Everything is
 * runtime-gated to pd projects regardless of where the config lives.
 */
function wireTarget(target: AgentCliTarget, cwd: string, alsoUser: boolean): ConfigureResult[] {
  const out: ConfigureResult[] = [];
  if (target.projectConfigPath) {
    out.push(configureTarget(target, { scope: 'project', cwd }));
    if (alsoUser) out.push(configureTarget(target, { scope: 'user' }));
  } else {
    // codex/agy: user-level is the only interactive surface; the gate scopes it.
    out.push(configureTarget(target, { scope: 'user' }));
  }
  return out;
}

// ─── Silent install (pd init) ────────────────────────────────────────────────

export interface SilentHooksResult {
  configured: number;
  detected: string[];
  tentaclesMissing: boolean;
  failures: string[];
}

export interface HookTargetStatus {
  name: string;
  slug: string;
  detected: boolean;
  projectPath: string | null;
  userPath: string;
  projectWired: boolean;
  userWired: boolean;
  expectedScope: 'project' | 'user';
  wired: boolean;
  note?: string;
  projectArmed: boolean;
}

function configCarriesPdHook(path: string): boolean {
  try {
    return existsSync(path) && readFileSync(path, 'utf8').includes(PD_HOOK_MARKER);
  } catch {
    return false;
  }
}

/** Read-only truth used by `pd squid status --json` and operator surfaces. */
export function inspectHookTargets(home = DEFAULT_HOME, cwd = process.cwd()): HookTargetStatus[] {
  const projectArmed = isSquidProjectArmed(cwd);
  return buildTargets(home).map((target) => {
    const projectPath = target.projectConfigPath?.(cwd) ?? null;
    const projectWired = projectPath ? configCarriesPdHook(projectPath) : false;
    const userWired = configCarriesPdHook(target.userConfigPath);
    const expectedScope = target.projectConfigPath ? 'project' : 'user';
    return {
      name: target.name,
      slug: target.slug,
      detected: target.detect(),
      projectPath,
      userPath: target.userConfigPath,
      projectWired,
      userWired,
      expectedScope,
      wired: projectArmed && (expectedScope === 'project' ? projectWired : userWired),
      note: target.note,
      projectArmed,
    };
  });
}

/**
 * Wire detected CLIs for a specific project (pd init). Project-level for
 * claude/gemini; gated user-level for codex/agy. Never global-by-default.
 */
export function silentHooksInstall(
  home = DEFAULT_HOME,
  opts: { cwd?: string } = {},
): SilentHooksResult {
  const cwd = opts.cwd ?? process.cwd();
  const stage = stageTentacles();
  const detected = buildTargets(home).filter((t) => t.detect());
  const result: SilentHooksResult = {
    configured: 0,
    detected: detected.map((t) => t.slug),
    tentaclesMissing: stage.missing.length > 0,
    failures: [],
  };
  if (result.tentaclesMissing || detected.length === 0) return result;
  registerSquidProject(cwd);

  for (const target of detected) {
    const results = wireTarget(target, cwd, false);
    if (results.some((r) => r.success && !r.skipped)) result.configured++;
    for (const failure of results.filter((r) => !r.success)) {
      result.failures.push(`${target.slug}: ${failure.error ?? 'configuration failed'}`);
    }
  }
  if (result.failures.length > 0 || result.configured < detected.length) {
    unregisterSquidProject(cwd);
  }
  return result;
}

// ─── Interactive command (pd hooks ...) ──────────────────────────────────────

export async function handleHooks(
  positional: string[],
  options: Record<string, unknown>,
  home = DEFAULT_HOME,
): Promise<void> {
  const sub = positional[0] ?? 'install';
  const targets = buildTargets(home);

  if (isHooksStatusRequest(sub, options)) {
    console.log('');
    ui.info('Port Daddy agent-CLI hooks (per-project, daemon-gated)');
    console.log('');
    const cwd = process.cwd();
    console.log(`  This project: ${isSquidProjectArmed(cwd) ? '\x1b[32mARMED\x1b[0m' : '\x1b[2mnot armed\x1b[0m'} (${canonicalProjectRoot(cwd)})`);
    console.log('');
    for (const t of targets) {
      const present = t.detect();
      const status = present ? '\x1b[32m✓ installed\x1b[0m' : '\x1b[2m- not found\x1b[0m';
      const wired =
        existsSync(t.userConfigPath) && readFileSync(t.userConfigPath, 'utf-8').includes(PD_HOOK_MARKER)
          ? ' \x1b[32m(user-wired)\x1b[0m'
          : '';
      console.log(`    ${t.name.padEnd(22)} ${status}${wired}`);
      if (present && t.note) console.log(`      \x1b[2m${t.note}\x1b[0m`);
    }
    console.log('');
    return;
  }

  if (sub === 'uninstall' || sub === 'remove') {
    console.log('');
    ui.info('Removing Port Daddy hooks from all agent CLIs');
    const cwd = process.cwd();
    for (const t of targets) {
      for (const scope of ['user', 'project'] as const) {
        const r = uninstallTarget(t, { scope, cwd });
        if (r.success && !r.skipped) ui.success(`${t.name} (${scope}): cleared ${r.path}`);
      }
    }
    clearArmedSquidProjects();
    console.log('');
    return;
  }

  // install
  console.log('');
  ui.info('Port Daddy — agent-CLI interactive hooks (this project)');
  console.log('');

  const detected = targets.filter((t) => t.detect());
  if (detected.length === 0) {
    ui.warn('No agent CLIs detected (looked for claude, codex, gemini, agy).');
    console.log('');
    process.exitCode = 1;
    return;
  }

  const cwd = process.cwd();
  console.log('  Detected: ' + detected.map((t) => t.name).join(', '));
  console.log(`  Wires coordination into their interactive sessions for THIS project (${cwd}).`);
  console.log('  Hooks are inert unless the pd daemon is running and this exact project root is armed.');
  console.log('');

  const assumeYes = !!options.yes || !!options.y || !ui.canPrompt();
  const proceed = assumeYes ? true : await ui.confirm('Wire coordination hooks for this project?', true);
  if (!proceed) {
    ui.info('Skipped. Run `pd hooks install` any time.');
    return;
  }

  const stage = stageTentacles();
  if (stage.missing.length > 0) {
    ui.warn(`Squid tentacles not found on this build (${stage.missing.join(', ')}).`);
    console.log('  The hook scripts (bin/pd-hook-*) ship with the Giant Squid Harness.');
    console.log('  Update Port Daddy, then re-run `pd hooks install`.');
    console.log('');
    process.exitCode = 1;
    return;
  }
  ui.success(`Staged tentacles + gate → ${tentacleBinDir()}`);
  registerSquidProject(cwd);

  const alsoUser = !!options.user;
  const failures: string[] = [];
  console.log('');
  console.log('  Wiring hooks:');
  for (const target of detected) {
    const results = wireTarget(target, cwd, alsoUser);
    for (const r of results) {
      if (r.skipped) continue;
      if (r.success) console.log(`    \x1b[32m✓\x1b[0m ${target.name.padEnd(22)} ${r.path}`);
      else {
        failures.push(`${target.slug}: ${r.error ?? 'configuration failed'}`);
        console.log(`    \x1b[31m✗\x1b[0m ${target.name.padEnd(22)} ${r.error}`);
      }
    }
    if (target.note) console.log(`      \x1b[2m${target.note}\x1b[0m`);
  }

  console.log('');
  if (failures.length > 0) {
    unregisterSquidProject(cwd);
    ui.warn(`Hook installation failed closed; this project remains inert (${failures.join('; ')}).`);
    process.exitCode = 1;
  } else {
    ui.success('Coordination hooks wired for this project (active only when the daemon is up).');
  }
  if (detected.some((t) => t.slug === 'codex')) {
    console.log('  Codex: run `codex` → `/hooks` once to trust the pd hooks (persisted thereafter).');
  }
  console.log('  Verify:  pd hooks list   ·   Remove:  pd hooks uninstall');
  console.log('');
}

export function isHooksStatusRequest(sub: string, options: Record<string, unknown>): boolean {
  return sub === 'list' || sub === 'status' || !!options.list || !!options.status;
}
