#!/usr/bin/env node
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const VALID_KEY_GENERATORS = ['client', 'server'];
const VALID_KEY_SOURCES = ['random-uuid', 'pii-derived', 'sequential'];
const VALID_STATUS_FLAVORS = ['stripe', 'ietf'];
const VALID_DURABLE_STORES = ['postgres', 'redis-plus-postgres', 'redis-only'];
const VALID_UNIQUENESS_SCOPES = ['per-tenant', 'global'];

function isPlainObject(value) {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

/**
 * Audit an idempotency-key implementation plan against this skill's core
 * rules (fingerprint check + in-progress lock + recovery-point state machine
 * — drop any one and you have a cache pretending to be idempotency) and its
 * Quality Gates. Rules operate on structured/enum/boolean/number fields only.
 *
 * @param {unknown} plan - parsed JSON plan, see schemas/idempotency-plan.schema.json
 * @returns {{pass: boolean, score: number, findings: Array<{rule: string, severity: string, message: string}>, recommendations: string[]}}
 */
export function auditIdempotencyKeyPatterns(plan) {
  if (!isPlainObject(plan)) {
    throw new TypeError('plan must be a non-null, non-array JSON object');
  }
  if (!VALID_KEY_GENERATORS.includes(plan.keyGenerator)) {
    throw new TypeError(`plan.keyGenerator must be one of: ${VALID_KEY_GENERATORS.join(', ')}`);
  }
  if (typeof plan.fingerprintCheck !== 'boolean') {
    throw new TypeError('plan.fingerprintCheck must be a boolean');
  }
  if (typeof plan.inProgressLock !== 'boolean') {
    throw new TypeError('plan.inProgressLock must be a boolean');
  }
  if (!VALID_STATUS_FLAVORS.includes(plan.statusCodeFlavor)) {
    throw new TypeError(`plan.statusCodeFlavor must be one of: ${VALID_STATUS_FLAVORS.join(', ')}`);
  }

  const findings = [];
  const recommendations = [];
  let score = 100;
  let criticalHit = false;

  function fail(rule, severity, message, recommendation) {
    findings.push({ rule, severity, message });
    if (recommendation) recommendations.push(recommendation);
    if (severity === 'critical') criticalHit = true;
    score -= { critical: 30, high: 15, medium: 8, low: 3 }[severity] ?? 5;
  }

  // --- Gate 1: the key must be generated by the CLIENT, before the request ---
  if (plan.keyGenerator === 'server') {
    fail(
      'server-generated-key',
      'critical',
      'keyGenerator is "server": a server-generated key cannot survive the network retry it exists to protect against — the retry arrives with no key (or a new one).',
      'Have the client generate a UUID v4 before the request and send it as the Idempotency-Key header.'
    );
  }

  // --- Gate 2: opaque random key, never PII or a guessable sequence ---
  if (plan.keySource !== undefined && !VALID_KEY_SOURCES.includes(plan.keySource)) {
    fail(
      'invalid-key-source',
      'medium',
      `keySource "${plan.keySource}" is not one of: ${VALID_KEY_SOURCES.join(', ')}.`,
      'Declare the key source as random-uuid, pii-derived, or sequential so it can be audited.'
    );
  } else if (plan.keySource === 'pii-derived') {
    fail(
      'pii-as-key',
      'high',
      'keySource is "pii-derived": PII keys leak into logs, and legitimately different requests from the same user collide.',
      'Use a random opaque UUID v4 as the idempotency key; keep PII out of it entirely.'
    );
  } else if (plan.keySource === 'sequential') {
    fail(
      'sequential-key',
      'medium',
      'keySource is "sequential": sequential keys collide across client instances and are trivially guessable across tenants.',
      'Use a random UUID v4 per logical operation.'
    );
  }

  // --- Gate 3: the fingerprint check (drop it and you return the wrong cached response) ---
  if (plan.fingerprintCheck !== true) {
    fail(
      'missing-fingerprint-check',
      'critical',
      'fingerprintCheck is false: a buggy client reusing a key with a different body will silently receive the wrong cached response.',
      'Store the request fingerprint (method, path, params) and return 422 (IETF) / 400 (Stripe) on mismatch.'
    );
  }

  // --- Gate 4: the in-progress lock with a TTL ---
  if (plan.inProgressLock !== true) {
    fail(
      'missing-in-progress-lock',
      'critical',
      'inProgressLock is false: two concurrent retries with the same key will both execute the work — the exact double-side-effect the pattern exists to prevent.',
      'Lock the key row (locked_at) on first touch and return 409 Conflict to concurrent retries.'
    );
  } else if (!(typeof plan.lockTtlSeconds === 'number' && plan.lockTtlSeconds > 0)) {
    fail(
      'lock-without-ttl',
      'high',
      'inProgressLock is set but lockTtlSeconds is not a positive number: a crashed worker leaves the key stuck "in progress" forever.',
      'Add a stale-lock TTL (e.g. locked_at < now() - 90s, or Redis SET NX EX) sized to worst-case request latency.'
    );
  }

  // --- Gate 5: recovery-point state machine, one side effect per atomic phase ---
  if (plan.recoveryPointStateMachine !== true) {
    fail(
      'missing-recovery-points',
      'high',
      'recoveryPointStateMachine is not true: a worker crash mid-request leaves partial state that a naive retry either duplicates (double-charge) or abandons (lost order).',
      'Advance a recovery_point label after each atomic phase so retries resume mid-flow instead of restarting.'
    );
  }
  if (typeof plan.maxSideEffectsPerPhase === 'number' && plan.maxSideEffectsPerPhase > 1) {
    fail(
      'multiple-side-effects-per-phase',
      'critical',
      `maxSideEffectsPerPhase is ${plan.maxSideEffectsPerPhase}: two or more external side effects inside one atomic phase reintroduces the dual-write hazard the state machine exists to remove.`,
      'Restructure phases so each commits at most ONE foreign side effect before advancing recovery_point.'
    );
  }

  // --- Gate 6: durable storage — Redis-only is a lossy response cache ---
  if (plan.durableStore !== undefined && !VALID_DURABLE_STORES.includes(plan.durableStore)) {
    fail(
      'invalid-durable-store',
      'medium',
      `durableStore "${plan.durableStore}" is not one of: ${VALID_DURABLE_STORES.join(', ')}.`,
      'Declare the storage split so durability can be audited.'
    );
  } else if (plan.durableStore === 'redis-only') {
    fail(
      'redis-only-store',
      'high',
      'durableStore is "redis-only": eviction or persistence config loses keys, silently re-enabling duplicate side effects.',
      'Keep the durable record + response cache in Postgres (unique index as last-line defense); use Redis only for the fast TTL lock.'
    );
  }

  // --- Gate 7: per-tenant uniqueness scope ---
  if (plan.uniquenessScope !== undefined && !VALID_UNIQUENESS_SCOPES.includes(plan.uniquenessScope)) {
    fail(
      'invalid-uniqueness-scope',
      'medium',
      `uniquenessScope "${plan.uniquenessScope}" is not one of: ${VALID_UNIQUENESS_SCOPES.join(', ')}.`,
      'Declare the uniqueness scope so tenant isolation can be audited.'
    );
  } else if (plan.uniquenessScope === 'global') {
    fail(
      'global-key-scope',
      'high',
      'uniquenessScope is "global": one tenant\'s key can collide with another\'s and return their cached response — a data leak.',
      'Scope the unique index per (user_id, idempotency_key).'
    );
  }

  // --- Gate 8: retention window (24h is the canonical floor; < 1h strands flaky clients) ---
  if (typeof plan.retentionHours === 'number') {
    if (plan.retentionHours < 1) {
      fail(
        'retention-below-one-hour',
        'high',
        `retentionHours is ${plan.retentionHours}: mobile clients on flaky networks cannot complete a retry cycle inside that window.`,
        'Use 24 hours as the retention floor; tune up for offline-first apps.'
      );
    } else if (plan.retentionHours < 24) {
      fail(
        'retention-below-canonical-floor',
        'medium',
        `retentionHours is ${plan.retentionHours}: below the canonical 24h window (Stripe).`,
        'Raise retention to at least 24 hours unless a measured constraint says otherwise.'
      );
    }
  } else {
    fail(
      'retention-undeclared',
      'medium',
      'retentionHours is not declared: without a reaper window the table grows forever and stale fingerprints become debugging hazards.',
      'Declare retentionHours (24 is the canonical value) and wire a reaper job.'
    );
  }

  // --- Gate 9: only unsafe methods need the header ---
  if (plan.appliesToSafeMethods === true) {
    fail(
      'idempotency-key-on-safe-methods',
      'medium',
      'appliesToSafeMethods is true: GET/PUT/DELETE are already idempotent per HTTP semantics; requiring the header there adds cost without protection.',
      'Require the Idempotency-Key header only on POST and other non-idempotent mutators.'
    );
  }

  const clampedScore = Math.max(0, Math.min(100, Math.round(score)));
  const pass = !criticalHit && clampedScore >= 60;

  if (findings.length === 0) {
    recommendations.push('Plan has all three critical ingredients (fingerprint check, TTL lock, recovery points) plus sane scope/retention. Still run the concurrent-retry and crash-mid-phase integration tests from the Quality Gates before shipping.');
  }

  return { pass, score: clampedScore, findings, recommendations };
}

function parseArgs(argv) {
  const i = argv.indexOf('--input');
  if (i === -1 || !argv[i + 1]) throw new Error('usage: idempotency_key_patterns_audit.mjs --input <file>.json');
  return { input: argv[i + 1] };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  try {
    const { input } = parseArgs(process.argv.slice(2));
    const data = JSON.parse(readFileSync(input, 'utf8'));
    const report = auditIdempotencyKeyPatterns(data);
    process.stdout.write(`${JSON.stringify(report, null, 2)}\n`);
    if (!report.pass) process.exit(1);
  } catch (e) {
    process.stderr.write(`idempotency_key_patterns_audit: ${e.message}\n`);
    process.exit(1);
  }
}
