import type { RoadmapItem, RoadmapItems, RoadmapStatus } from './roadmap-items.js';

/**
 * Cockpit mission status. Mirrors RoadmapStatus 1:1 — there are five
 * buckets now, not the nine semi-overlapping markdown-derived statuses
 * the cockpit used to compute. The richer derivation (in-flight vs
 * drifting vs stalled etc.) wasn't authoritative — it was a regex over
 * the cartographer's prose. Slice C made roadmap_items the source of
 * record, so cockpit reads what's actually there.
 */
export type MissionStatus = RoadmapStatus;

export const MISSION_STATUSES: ReadonlyArray<MissionStatus> = [
  'now',
  'backlog',
  'parked',
  'merge',
  'done',
];

export interface MissionCard {
  id: string;
  title: string;
  status: MissionStatus;
  /** Always 'roadmap_items' now; kept for SDK back-compat. */
  source: string;
  /** The canonical key — same as id/slug. Kept for SDK back-compat. */
  sourceAnchor: string;
  summary: string;
  /** Promoted from the roadmap_items.notes stream (one entry per note). */
  evidence: string[];
  /** Promoted from roadmap_items.dependencies. */
  files: string[];
  updatedAt: number;
}

export interface MissionIntake {
  /** Echoes the projectDir the route was called with. The data itself is
   * keyed on `harbor` inside roadmap_items, not on projectDir. */
  projectDir: string;
  /** Constant single-element list: ['roadmap_items']. Kept for SDK
   * back-compat with the old markdown-reader return shape. */
  sources: string[];
  /** Always empty — no markdown files to be missing anymore. */
  missing: string[];
  /** Always empty — no markdown files to be present-but-empty. */
  sourcesWithNoCards: string[];
  missions: MissionCard[];
  generatedAt: number;
}

export interface ReadMissionsOptions {
  /**
   * Echoed back in the response. Used by callers that want a stable
   * `projectDir` field in the intake. Data lookups go via harbor, not
   * via projectDir.
   */
  projectDir: string;
  /** Harbor to query roadmap_items in. Defaults to the daemon's harbor
   * for the project. */
  harbor?: string;
  status?: ReadonlyArray<MissionStatus>;
  limit?: number;
  /** Required: a RoadmapItems module instance to query. Cockpit routes
   * receive this via deps; tests inject a stub. */
  roadmapItems: RoadmapItems;
}

/**
 * Promote a RoadmapItem to the MissionCard view shape that the cockpit
 * panel and SDK consumers expect. Pure mapping; no I/O.
 */
export function roadmapItemToMissionCard(item: RoadmapItem): MissionCard {
  const summaryMd = (item.summaryMd ?? '').trim();
  // Title: first non-empty line, with any leading markdown heading hash
  // stripped. Everything else becomes summary.
  const firstNewline = summaryMd.indexOf('\n');
  const firstLine = firstNewline === -1 ? summaryMd : summaryMd.slice(0, firstNewline);
  const title = firstLine.replace(/^#+\s*/, '').trim() || item.slug;
  const summary =
    firstNewline === -1 ? '' : summaryMd.slice(firstNewline + 1).trim();

  return {
    id: item.slug,
    title,
    status: item.status,
    source: 'roadmap_items',
    sourceAnchor: item.slug,
    summary,
    evidence: (item.notes ?? []).map((n) => n.text),
    files: Array.isArray(item.dependencies) ? item.dependencies : [],
    updatedAt: item.lastTouchedAt,
  };
}

/**
 * Read mission cards from the roadmap_items tuple stream. Replaces the
 * pre-Slice-C markdown reader that consumed CURRENT-WORK.md /
 * UNIFIED-ROADMAP.md / .cartographer/status.md. The cartographer now
 * writes directly into roadmap_items; the markdown files are projections
 * generated by `pd roadmap render`, not authoritative.
 */
export function readMissions(options: ReadMissionsOptions): MissionIntake {
  const { projectDir, harbor, roadmapItems } = options;
  const items = roadmapItems.list({ harbor, limit: options.limit ?? 1000 });

  const allowedStatuses =
    options.status && options.status.length > 0
      ? new Set<MissionStatus>(options.status)
      : null;
  const filtered = allowedStatuses
    ? items.filter((i) => allowedStatuses.has(i.status))
    : items;

  const missions = filtered.map(roadmapItemToMissionCard);

  return {
    projectDir,
    sources: ['roadmap_items'],
    missing: [],
    sourcesWithNoCards: [],
    missions,
    generatedAt: Date.now(),
  };
}
