/**
 * Client for the Fleetbot GitHub App publisher (`POST /v1/fleetbot/publish`).
 *
 * This is the only supported way for Port Daddy tooling to mutate GitHub as
 * `port-daddy[bot]`. It exists so that no agent ever reaches for `gh`, a PAT, or
 * an ambient login to open a PR: work published through here is attributable to
 * the App, not to whichever human happened to be logged in.
 *
 * Three deliberate properties:
 *
 * 1. It imports `lib/github-publisher-contract.ts` — the same module Relay
 *    imports — rather than restating canonicalization. The contract's own header
 *    explains why: a parser difference between the identity gate and the
 *    component holding the App key is exploitable. One implementation, one
 *    canonical form, one idempotency key.
 *
 * 2. It cannot mint its own authority. The capability is Ed25519-signed by the
 *    daemon identity and resolved server-side; this client only assembles the
 *    exact bytes to be signed and carries the result. A caller with no
 *    capability provider gets a `MissingActuatorError`, never a degraded path.
 *
 * 3. It has no fallback. Every refusal raises. Silently publishing as the human
 *    when admission fails is the bug this module exists to prevent, so there is
 *    no branch in this file that reads a GitHub token from anywhere.
 *
 * Attribution is applied by `buildActionRequest`, not by callers, so no caller
 * can forget it.
 */

import { createHash } from 'node:crypto';
import {
  FLEETBOT_ACTION_SCHEMA,
  FLEETBOT_PUBLISHER_CAPABILITY_SCHEMA,
  fleetbotIdempotencyPreimage,
  fleetbotPublisherCapabilityPreimage,
  isGitSha,
  isRepository,
  type FleetbotActionRequest,
  type FleetbotAuthorship,
  type FleetbotOperation,
  type FleetbotPublisherCapability,
  type FleetbotReceipt,
} from './github-publisher-contract.js';

/** The App identity every receipt from this client must name. */
export const FLEETBOT_APP_LOGIN = 'port-daddy[bot]';

export const DEFAULT_RELAY_ORIGIN = 'https://relay.portdaddy.dev';
export const PUBLISH_PATH = '/v1/fleetbot/publish';

/** Operations whose payload carries an existing pull request. */
const EXISTING_PR_OPERATIONS: ReadonlySet<FleetbotOperation> = new Set([
  'pull-request.update',
  'pull-request.ready',
  'pull-request.request-reviewers',
  'pull-request.comment',
  'pull-request.review-reply',
  'pull-request.enqueue',
  'pull-request.inspect',
]);

/** Operations that put author-visible prose on the PR. */
const NARRATIVE_OPERATIONS: ReadonlySet<FleetbotOperation> = new Set([
  'pull-request.publish',
  'pull-request.update',
  'pull-request.comment',
  'pull-request.review-reply',
]);

// ── Attribution ──────────────────────────────────────────────────────────────

/** The single visible line that marks Claude Code authorship. */
export const ATTRIBUTION_LINE = '_Generated by [Claude Code](https://claude.ai/code)_';

/** Exact required trailer: blank line, rule, attribution line. */
export const ATTRIBUTION_BLOCK = `\n\n---\n${ATTRIBUTION_LINE}`;

/**
 * Append the Claude Code attribution, idempotently.
 *
 * Applied to every PR body, comment and review reply by `buildActionRequest`,
 * so a caller cannot omit it. Re-stamping an already-stamped body is a no-op
 * rather than a second footer, which matters because `pull-request.update`
 * routinely re-sends a body this function already touched.
 *
 * The block goes at the very end, after any `Roadmap-Item:` trailer. Relay's
 * trailer validator matches the trailer on its own line anywhere in the body
 * and requires exactly one, so trailing content does not disturb it.
 */
export function withAttribution(body: string): string {
  const trimmed = String(body ?? '').replace(/\s+$/, '');
  const existing = trimmed.lastIndexOf(ATTRIBUTION_LINE);
  if (existing >= 0 && trimmed.slice(existing + ATTRIBUTION_LINE.length).trim() === '') {
    // Already ends with the attribution line. Re-normalize the rule above it
    // so a hand-edited body converges on the canonical block.
    const head = trimmed.slice(0, existing).replace(/\n*-{3,}\s*$/, '').replace(/\s+$/, '');
    return `${head}${ATTRIBUTION_BLOCK}`;
  }
  return `${trimmed}${ATTRIBUTION_BLOCK}`;
}

/** True when a body ends with the exact attribution block. */
export function hasAttribution(body: string): boolean {
  return String(body ?? '').replace(/\s+$/, '').endsWith(ATTRIBUTION_BLOCK.trim());
}

// ── Errors ───────────────────────────────────────────────────────────────────

/**
 * Raised when the actuator cannot be reached or cannot admit the request.
 *
 * Per `skills/github-app-actuator`: infrastructure absence must not become
 * authorship fraud. The error carries everything needed to publish the work
 * later, so a caller can record pending publication rather than reach for a
 * personal credential.
 */
export class FleetbotPublishError extends Error {
  readonly code: string;
  readonly status: number | null;
  readonly pending: PendingPublication;
  readonly remedy: string;

  constructor(input: {
    code: string;
    status: number | null;
    message: string;
    remedy: string;
    pending: PendingPublication;
  }) {
    super(input.message);
    this.name = 'FleetbotPublishError';
    this.code = input.code;
    this.status = input.status;
    this.remedy = input.remedy;
    this.pending = input.pending;
  }

  /** Operator-facing block: what failed, what is preserved, what to do. */
  report(): string {
    const p = this.pending;
    return [
      `✗ fleetbot-publish: ${this.code}${this.status ? ` (HTTP ${this.status})` : ''}`,
      `  ${this.message}`,
      '',
      '  PUBLICATION IS PENDING — the work is recoverable but not delivered.',
      `    operation:  ${p.operation}`,
      `    repository: ${p.repository}`,
      `    base:       ${p.baseBranch} @ ${p.baseSha}`,
      `    head:       ${p.headSha ?? '(none)'}`,
      p.sourceBranch ? `    branch:     ${p.sourceBranch}` : null,
      p.pullRequestNumber ? `    pull:       #${p.pullRequestNumber}` : null,
      `    session:    ${p.sessionId}`,
      '',
      `  ${this.remedy}`,
      '',
      '  Do NOT publish this with a personal GitHub credential. A PR opened with',
      '  an operator token is authorship fraud, not a workaround.',
    ]
      .filter((line) => line !== null)
      .join('\n');
  }
}

/** Raised specifically when no daemon capability provider is wired up. */
export class MissingActuatorError extends FleetbotPublishError {
  constructor(input: { message: string; remedy: string; pending: PendingPublication }) {
    super({ code: 'ACTUATOR_MISSING', status: null, ...input });
    this.name = 'MissingActuatorError';
  }
}

/** Everything needed to re-attempt publication once the actuator is live. */
export interface PendingPublication {
  operation: FleetbotOperation;
  repository: string;
  baseBranch: string;
  baseSha: string;
  headSha: string | null;
  sourceBranch: string | null;
  pullRequestNumber: number | null;
  sessionId: string;
}

// ── Request assembly ─────────────────────────────────────────────────────────

function sha256Hex(input: string): string {
  return createHash('sha256').update(input, 'utf8').digest('hex');
}

export interface BuildActionRequestInput {
  operation: FleetbotOperation;
  repository: string;
  payload: Record<string, unknown>;
  sessionId: string;
  authorship: FleetbotAuthorship;
}

/**
 * Assemble the canonical wire request, attribution applied and idempotency key
 * bound.
 *
 * Relay recomputes the key from the same preimage and refuses a mismatch, so
 * the key is derived here rather than accepted from a caller. The envelope must
 * carry exactly the nine keys Relay's `parseRequest` allows; an extra field is
 * a 400, not a warning.
 */
export function buildActionRequest(input: BuildActionRequestInput): FleetbotActionRequest {
  if (!isRepository(input.repository) || input.repository !== input.repository.toLowerCase()) {
    throw new TypeError(`repository must be lowercase "owner/repo": ${input.repository}`);
  }

  const payload = { ...input.payload };
  if (NARRATIVE_OPERATIONS.has(input.operation) && typeof payload.body === 'string') {
    payload.body = withAttribution(payload.body);
  }

  const unkeyed = {
    schema: FLEETBOT_ACTION_SCHEMA,
    operation: input.operation,
    repository: input.repository,
    payload,
    sessionId: input.sessionId,
    authorship: input.authorship,
  } as FleetbotActionRequest;

  const requestHash = sha256Hex(fleetbotIdempotencyPreimage(unkeyed));
  return { ...unkeyed, idempotencyKey: `pd-gh-${requestHash}` } as FleetbotActionRequest;
}

/** The request hash Relay will recompute and bind the capability against. */
export function requestHashOf(request: FleetbotActionRequest): string {
  return sha256Hex(fleetbotIdempotencyPreimage(request));
}

// ── Capability ───────────────────────────────────────────────────────────────

/** The exact scope a daemon is asked to authorize. */
export interface CapabilitySpec {
  schema: typeof FLEETBOT_PUBLISHER_CAPABILITY_SCHEMA;
  sessionId: string;
  repository: string;
  operation: FleetbotOperation;
  baseBranch: string;
  baseSha: string;
  headSha: string;
  requestHash: string;
}

/**
 * A daemon-backed signer.
 *
 * The daemon holds the Ed25519 private key and the account binding; it fills in
 * `accountTokenHash`, `daemonFingerprint`, `signingKeyGeneration`, `issuedAt`,
 * `expiresAt` and `nonce`, then signs SHA-256 of the canonical capability bytes.
 * This client never sees a key.
 */
export interface CapabilityProvider {
  mint(spec: CapabilitySpec): Promise<{
    capability: FleetbotPublisherCapability;
    capabilitySignature: string;
  }>;
}

/** Build the scope a capability must cover for this request. */
export function capabilitySpec(
  request: FleetbotActionRequest,
  scope: { baseBranch: string; baseSha: string; headSha: string },
): CapabilitySpec {
  if (!isGitSha(scope.baseSha) || !isGitSha(scope.headSha)) {
    throw new TypeError('baseSha and headSha must be 40-character git SHAs');
  }
  return {
    schema: FLEETBOT_PUBLISHER_CAPABILITY_SCHEMA,
    sessionId: request.sessionId,
    repository: request.repository,
    operation: request.operation,
    baseBranch: scope.baseBranch,
    baseSha: scope.baseSha,
    headSha: scope.headSha,
    requestHash: requestHashOf(request),
  };
}

/** The exact string a daemon signs (SHA-256 of it, as raw Ed25519). */
export function capabilitySigningPreimage(capability: FleetbotPublisherCapability): string {
  return fleetbotPublisherCapabilityPreimage(capability);
}

/**
 * Check a minted capability actually covers the request before spending a
 * network round trip on a guaranteed 401.
 */
export function capabilityCoversRequest(
  capability: FleetbotPublisherCapability,
  request: FleetbotActionRequest,
): { ok: true } | { ok: false; reason: string } {
  const expected = requestHashOf(request);
  if (capability.schema !== FLEETBOT_PUBLISHER_CAPABILITY_SCHEMA) {
    return { ok: false, reason: 'capability schema is not the publisher capability schema' };
  }
  if (capability.requestHash !== expected) {
    return { ok: false, reason: 'capability requestHash does not bind this request' };
  }
  if (capability.repository !== request.repository) {
    return { ok: false, reason: 'capability repository differs from the request repository' };
  }
  if (capability.operation !== request.operation) {
    return { ok: false, reason: 'capability operation differs from the request operation' };
  }
  if (capability.sessionId !== request.sessionId) {
    return { ok: false, reason: 'capability sessionId differs from the request sessionId' };
  }
  return { ok: true };
}

// ── Failure classification ───────────────────────────────────────────────────

/**
 * Turn a publisher response into a legible refusal.
 *
 * 404 is called out by name. The handler's own failure modes are 405/400/401/
 * 409/502/503 and it never answers 404, so a 404 means the route is not
 * deployed on the relay being addressed — a deployment fact, not an auth fact,
 * and the single most confusing failure to hit without this message.
 */
export function classifyPublishFailure(
  status: number,
  body: unknown,
  origin: string,
): { code: string; message: string; remedy: string } {
  const row = (body && typeof body === 'object' ? body : {}) as Record<string, unknown>;
  const code = typeof row.code === 'string' ? row.code : `HTTP_${status}`;
  const detail = typeof row.error === 'string' ? row.error : '';

  if (status === 404) {
    return {
      code: 'ROUTE_NOT_DEPLOYED',
      message:
        `${origin}${PUBLISH_PATH} answered 404. The publisher handler never returns 404 — `
        + 'its refusals are 400/401/405/409/502/503 — so the route is absent from the deployed '
        + 'Worker bundle, even if it is present in source.',
      remedy:
        'Ship the relay release that carries the route, then retry. Check which bundle is live '
        + 'before assuming an auth problem.',
    };
  }
  if (status === 503 && code === 'PUBLISHER_UNCONFIGURED') {
    return {
      code,
      message: detail || 'the publisher is deployed but not configured',
      remedy:
        'Relay is missing the GitHub App identity or its Ed25519 signing key. An operator must '
        + 'set the publisher secrets on the relay Worker; names live in apps/relay/wrangler.deploy.toml.',
    };
  }
  if (status === 401) {
    return {
      code,
      message: detail || 'admission refused',
      remedy:
        code === 'CAPABILITY_INVALID'
          ? 'The daemon capability was malformed, expired, replayed, or signed by a key Relay does '
            + 'not recognize. Re-mint it for this exact request; do not retry the same bytes.'
          : 'The pdu_ account bearer is missing, expired, or its stored GitHub authorization needs '
            + 'refreshing. Sign in again to re-authorize App publication.',
    };
  }
  if (status === 400) {
    return {
      code,
      message: detail || 'the request envelope was rejected',
      remedy:
        code.startsWith('ROADMAP_')
          ? 'Fix the Roadmap-Item trailer: exactly one, naming the session roadmap item, or '
            + '"none — <specific reason>" matching the session sidequest reason.'
          : 'The envelope or payload does not match the contract for this operation. Rebuild it '
            + 'with buildActionRequest rather than hand-assembling fields.',
    };
  }
  if (status === 502 && code === 'TOKEN_CLEANUP_UNCONFIRMED') {
    return {
      code,
      message: detail || 'GitHub accepted the action but scoped token cleanup is unconfirmed',
      remedy:
        'The mutation likely LANDED. Read GitHub back before retrying — a blind retry can double-post. '
        + 'The receipt is in the response body.',
    };
  }
  return {
    code,
    message: detail || `publisher refused the request with HTTP ${status}`,
    remedy: 'Read the receipt or error body; do not retry blindly and do not switch credentials.',
  };
}

// ── Receipt verification ─────────────────────────────────────────────────────

/**
 * Refuse a receipt that does not name the App.
 *
 * The whole point of this path is that the mutation is attributable to
 * `port-daddy[bot]`. A receipt naming anything else means the publish happened
 * under some other identity and must be treated as a failure.
 */
export function assertBotAuthorship(
  receipt: FleetbotReceipt,
  expected: { repository: string; operation: FleetbotOperation },
): void {
  const problems: string[] = [];
  if (receipt.authority !== 'port-daddy-relay-github-app') {
    problems.push(`authority is "${receipt.authority}", not the Relay GitHub App`);
  }
  if (receipt.repository !== expected.repository) {
    problems.push(`receipt names repository "${receipt.repository}", expected "${expected.repository}"`);
  }
  if (receipt.operation !== expected.operation) {
    problems.push(`receipt names operation "${receipt.operation}", expected "${expected.operation}"`);
  }
  if (!receipt.appSlug) {
    problems.push('receipt carries no App slug');
  }
  if (problems.length > 0) {
    throw new Error(`fleetbot receipt failed verification: ${problems.join('; ')}`);
  }
}

// ── Publish ──────────────────────────────────────────────────────────────────

export interface PublishOptions {
  /** Relay origin. Defaults to production. */
  origin?: string;
  /** Operator `pdu_` account bearer. Never logged, never defaulted. */
  accountToken: string;
  /** Daemon signer. Required — absence is a refusal, not a fallback. */
  capabilityProvider: CapabilityProvider | null | undefined;
  /** Exact scope for the capability. */
  scope: { baseBranch: string; baseSha: string; headSha: string };
  /** Injected for tests. */
  fetchImpl?: typeof fetch;
}

export interface PublishResult {
  receipt: FleetbotReceipt;
  status: number;
  /** `true` when Relay replayed a prior identical intent. */
  reused: boolean;
}

function pendingFrom(
  request: FleetbotActionRequest,
  scope: { baseBranch: string; baseSha: string; headSha: string },
): PendingPublication {
  const payload = (request.payload ?? {}) as Record<string, unknown>;
  return {
    operation: request.operation,
    repository: request.repository,
    baseBranch: scope.baseBranch,
    baseSha: scope.baseSha,
    headSha: scope.headSha ?? null,
    sourceBranch: request.authorship?.sourceBranch ?? null,
    pullRequestNumber:
      typeof payload.pullRequestNumber === 'number' ? payload.pullRequestNumber : null,
    sessionId: request.sessionId,
  };
}

/**
 * Publish one action through the actuator.
 *
 * Raises `FleetbotPublishError` on every refusal. There is intentionally no
 * success path that does not go through the relay and no branch that reads a
 * GitHub credential.
 */
export async function publish(
  request: FleetbotActionRequest,
  options: PublishOptions,
): Promise<PublishResult> {
  const origin = (options.origin ?? DEFAULT_RELAY_ORIGIN).replace(/\/+$/, '');
  const pending = pendingFrom(request, options.scope);

  if (!options.capabilityProvider) {
    throw new MissingActuatorError({
      message:
        'no daemon capability provider is configured, so no publisher authority can be minted',
      remedy:
        'Wire a CapabilityProvider backed by the local Port Daddy daemon identity. The daemon holds '
        + 'the Ed25519 signing key; this client deliberately cannot sign for itself.',
      pending,
    });
  }
  if (!/^pdu_[0-9a-f]{64}$/i.test(String(options.accountToken ?? ''))) {
    throw new FleetbotPublishError({
      code: 'ACCOUNT_TOKEN_MISSING',
      status: null,
      message: 'a Port Daddy pdu_ account bearer is required and was not supplied',
      remedy:
        'Supply the operator pdu_ account token. Do not substitute a GitHub PAT, GH_TOKEN, or an '
        + 'ambient gh login — those publish as the human and are exactly what this path replaces.',
      pending,
    });
  }

  const spec = capabilitySpec(request, options.scope);
  const minted = await options.capabilityProvider.mint(spec);
  const covers = capabilityCoversRequest(minted.capability, request);
  if (!covers.ok) {
    throw new FleetbotPublishError({
      code: 'CAPABILITY_SCOPE_MISMATCH',
      status: null,
      message: `the minted capability does not cover this request: ${covers.reason}`,
      remedy:
        'The daemon signed a different scope than the request carries. Re-mint against '
        + 'capabilitySpec(request, scope) instead of reusing a capability.',
      pending,
    });
  }

  const body = {
    ...request,
    capability: minted.capability,
    capabilitySignature: minted.capabilitySignature,
  };

  const doFetch = options.fetchImpl ?? fetch;
  let response: Response;
  try {
    response = await doFetch(`${origin}${PUBLISH_PATH}`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${options.accountToken}`,
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify(body),
    });
  } catch (err) {
    throw new FleetbotPublishError({
      code: 'RELAY_UNREACHABLE',
      status: null,
      message: `could not reach ${origin}${PUBLISH_PATH}: ${err instanceof Error ? err.message : String(err)}`,
      remedy: 'Check relay reachability. Publication stays pending until the actuator answers.',
      pending,
    });
  }

  let parsed: unknown = null;
  try {
    parsed = await response.json();
  } catch {
    parsed = null;
  }

  if (!response.ok) {
    const classified = classifyPublishFailure(response.status, parsed, origin);
    throw new FleetbotPublishError({
      code: classified.code,
      status: response.status,
      message: classified.message,
      remedy: classified.remedy,
      pending,
    });
  }

  const row = (parsed ?? {}) as Record<string, unknown>;
  const receipt = row.receipt as FleetbotReceipt | undefined;
  if (!receipt || typeof receipt !== 'object') {
    throw new FleetbotPublishError({
      code: 'RECEIPT_MISSING',
      status: response.status,
      message: 'the publisher returned success without a receipt',
      remedy: 'Treat the mutation as ambiguous and read GitHub back before any retry.',
      pending,
    });
  }
  assertBotAuthorship(receipt, { repository: request.repository, operation: request.operation });

  return { receipt, status: response.status, reused: receipt.result === 'reused' };
}

// ── Convenience wrappers ─────────────────────────────────────────────────────

/** Open a pull request as `port-daddy[bot]`. */
export async function openPullRequest(
  input: BuildActionRequestInput & { options: PublishOptions },
): Promise<PublishResult> {
  const { options, ...build } = input;
  return publish(buildActionRequest({ ...build, operation: 'pull-request.publish' }), options);
}

/** Update an existing pull request's title/body/head. */
export async function updatePullRequest(
  input: BuildActionRequestInput & { options: PublishOptions },
): Promise<PublishResult> {
  const { options, ...build } = input;
  return publish(buildActionRequest({ ...build, operation: 'pull-request.update' }), options);
}

/** Post an issue-level comment on a pull request. */
export async function commentOnPullRequest(
  input: BuildActionRequestInput & { options: PublishOptions },
): Promise<PublishResult> {
  const { options, ...build } = input;
  return publish(buildActionRequest({ ...build, operation: 'pull-request.comment' }), options);
}

/** Reply to one review comment thread. */
export async function replyToReviewComment(
  input: BuildActionRequestInput & { options: PublishOptions },
): Promise<PublishResult> {
  const { options, ...build } = input;
  return publish(buildActionRequest({ ...build, operation: 'pull-request.review-reply' }), options);
}

/** True when the operation's payload must name an existing PR. */
export function operationNeedsPullRequest(operation: FleetbotOperation): boolean {
  return EXISTING_PR_OPERATIONS.has(operation);
}
