#!/usr/bin/env node
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const E={disclosure:['not-applicable','summary','detailed'],privateReasoning:['not-requested','redacted-summary-only'],interrupt:['not-applicable','before-dispatch','between-steps','mid-run'],status:['used','not-applicable'],strategy:['bounded-input','provider-cache','eviction-or-summary','memory-promotion'],secret:['not-applicable','secret-store-reference','scoped-environment','stdin','argv','inline'],effect:['none','reversible-local','external-or-irreversible'],control:['not-applicable','automated-policy','human-approval'],agent:['coding','non-coding'],isolation:['not-applicable','declared']};
const object=x=>Boolean(x)&&typeof x==='object'&&!Array.isArray(x);
const text=x=>typeof x==='string'&&x.trim().length>0;
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
const isoDate=x=>{if(typeof x!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(x))return false;const [y,m,d]=x.split('-').map(Number);const z=new Date(0);z.setUTCFullYear(y,m-1,d);return z.getUTCFullYear()===y&&z.getUTCMonth()===m-1&&z.getUTCDate()===d};
const https=x=>{if(typeof x!=='string'||!x.startsWith('https://'))return false;try{const u=new URL(x);return u.protocol==='https:'&&Boolean(u.hostname)}catch{return false}};

/**
 * Portable declaration validation: the JSON Schema supplies structural checks;
 * this API additionally checks calendar dates, URL hosts and conditional fields.
 * It checks an input declaration only; it does not inspect accounts, providers,
 * deployments, enforcement, or effect execution.
 */
export function validateAgenticAppSpec(spec){
 const errors=[]; const req=(o,k,p)=>{if(!own(o,k))errors.push(`${p}.${k} is required`)}; const val=(x,values,p)=>{if(!values.includes(x))errors.push(`${p} has an invalid value`)}; const nonempty=(x,p)=>{if(!text(x))errors.push(`${p} must be nonempty trimmed text`)}; const obj=(x,p)=>{if(!object(x)){errors.push(`${p} must be an object`);return false}return true};
 if(!obj(spec,'spec'))return {valid:false,errors}; nonempty(spec.appName,'appName');
 const t=spec.transparency;if(obj(t,'transparency')){for(const k of ['actionDisclosure','evidenceDisclosure','uncertaintyDisclosure','privateReasoningPolicy','interruptMode','rationale'])req(t,k,'transparency');val(t.actionDisclosure,E.disclosure,'transparency.actionDisclosure');val(t.evidenceDisclosure,E.disclosure,'transparency.evidenceDisclosure');val(t.uncertaintyDisclosure,E.disclosure,'transparency.uncertaintyDisclosure');val(t.privateReasoningPolicy,E.privateReasoning,'transparency.privateReasoningPolicy');val(t.interruptMode,E.interrupt,'transparency.interruptMode');nonempty(t.rationale,'transparency.rationale');}
 const s=spec.stateModel;if(obj(s,'stateModel')){for(const k of ['conversationTranscript','durableTaskState','userMemory','provenanceEvidence','retention','restoreForkPolicy','rationale'])req(s,k,'stateModel');for(const k of ['conversationTranscript','durableTaskState','userMemory','provenanceEvidence'])val(s[k],E.status,`stateModel.${k}`);for(const k of ['retention','restoreForkPolicy','rationale'])nonempty(s[k],`stateModel.${k}`);}
 const c=spec.contextStrategy;if(obj(c,'contextStrategy')){req(c,'strategies','contextStrategy');req(c,'rationale','contextStrategy');if(!Array.isArray(c.strategies)||!c.strategies.length)errors.push('contextStrategy.strategies must be a nonempty array');else {for(const x of c.strategies)val(x,E.strategy,'contextStrategy.strategies item');if(new Set(c.strategies).size!==c.strategies.length)errors.push('contextStrategy.strategies must be unique')}nonempty(c.rationale,'contextStrategy.rationale');if(own(c,'providerCache')){const pc=c.providerCache;if(obj(pc,'contextStrategy.providerCache')){for(const k of ['provider','modelOrFamily','documentationUrl','checkedOn'])req(pc,k,'contextStrategy.providerCache');nonempty(pc.provider,'contextStrategy.providerCache.provider');nonempty(pc.modelOrFamily,'contextStrategy.providerCache.modelOrFamily');if(!https(pc.documentationUrl))errors.push('contextStrategy.providerCache.documentationUrl must be an HTTPS URL with host');if(!isoDate(pc.checkedOn))errors.push('contextStrategy.providerCache.checkedOn must be a real ISO calendar date')}}}
 const p=spec.capabilities;if(obj(p,'capabilities')){for(const k of ['tools','skills','mcp','secretCustody','rationale'])req(p,k,'capabilities');val(p.tools,E.status,'capabilities.tools');val(p.skills,E.status,'capabilities.skills');nonempty(p.rationale,'capabilities.rationale');const m=p.mcp;if(obj(m,'capabilities.mcp')){for(const k of ['status','rationale'])req(m,k,'capabilities.mcp');val(m.status,E.status,'capabilities.mcp.status');nonempty(m.rationale,'capabilities.mcp.rationale');if(own(m,'coreSize')&&(!Number.isInteger(m.coreSize)||m.coreSize<0))errors.push('capabilities.mcp.coreSize must be a finite nonnegative integer');if(own(m,'perProjectSpecialists')&&typeof m.perProjectSpecialists!=='boolean')errors.push('capabilities.mcp.perProjectSpecialists must be boolean');if(m.status==='used'&&!own(m,'coreSize'))errors.push('capabilities.mcp.coreSize is required when MCP is used');if(m.status==='used'&&!own(m,'perProjectSpecialists'))errors.push('capabilities.mcp.perProjectSpecialists is required when MCP is used')}const sc=p.secretCustody;if(obj(sc,'capabilities.secretCustody')){for(const k of ['required','mode','scope','rationale'])req(sc,k,'capabilities.secretCustody');if(typeof sc.required!=='boolean')errors.push('capabilities.secretCustody.required must be boolean');val(sc.mode,E.secret,'capabilities.secretCustody.mode');nonempty(sc.scope,'capabilities.secretCustody.scope');nonempty(sc.rationale,'capabilities.secretCustody.rationale');}}
 const e=spec.execution;if(obj(e,'execution')){for(const k of ['agentType','effectClass','isolation','control','authority','receiptPolicy','rationale'])req(e,k,'execution');val(e.agentType,E.agent,'execution.agentType');val(e.effectClass,E.effect,'execution.effectClass');val(e.isolation,E.isolation,'execution.isolation');for(const k of ['authority','receiptPolicy','rationale'])nonempty(e[k],`execution.${k}`);if(obj(e.control,'execution.control')){for(const k of ['kind','rationale'])req(e.control,k,'execution.control');val(e.control.kind,E.control,'execution.control.kind');nonempty(e.control.rationale,'execution.control.rationale')}}
 return {valid:errors.length===0,errors};
}
export function auditAgenticAppArchitecture(spec){
 const v=validateAgenticAppSpec(spec);if(!v.valid)return {pass:false,schemaValid:false,coverageByAxis:{},findings:v.errors.map(message=>({id:'invalid-declaration',axis:'schema',severity:'critical',message})),recommendations:['Repair the declaration before interpreting design findings.'],scope:'Static declaration audit only; no runtime, enforcement, provider, account, or effect evidence was observed.'};
 const findings=[];const add=(axis,id,severity,message)=>findings.push({axis,id,severity,message});const {transparency:t,stateModel:s,contextStrategy:c,capabilities:p,execution:e}=spec;const consequential=e.effectClass==='external-or-irreversible';const effectful=e.effectClass!=='none';const powered=p.tools==='used'||p.mcp.status==='used';
 if((powered||effectful)&&t.actionDisclosure==='not-applicable')add('transparency','missing-action-disclosure','high','Declared tools, MCP or effects require an action disclosure level.');
 if(consequential&&(t.evidenceDisclosure==='not-applicable'||t.uncertaintyDisclosure==='not-applicable'))add('transparency','missing-consequential-disclosure','high','Consequential effects require evidence and uncertainty disclosure.');
 if(effectful&&s.durableTaskState!=='used')add('stateModel','missing-effect-task-state','high','Effectful work requires durable task state for restore/replay handling.');
 if(consequential&&s.provenanceEvidence!=='used')add('stateModel','missing-consequential-provenance','high','Consequential effects require declared provenance evidence.');
 if(c.strategies.includes('provider-cache')&&!own(c,'providerCache'))add('contextStrategy','missing-provider-cache-receipt','high','Provider-cache strategy requires versioned provider cache metadata.');
 if(p.mcp.status==='not-applicable'&&(own(p.mcp,'coreSize')||own(p.mcp,'perProjectSpecialists')))add('capabilities','incoherent-mcp-scope','high','MCP is not applicable but MCP configuration fields were supplied.');
 if(p.secretCustody.required&&['argv','inline','not-applicable'].includes(p.secretCustody.mode))add('capabilities','secret-exposure-path','high','Required secret custody uses argv, inline text, or an inapplicable path.');
 if(effectful&&e.isolation!=='declared')add('execution','missing-effect-isolation','high','Effectful work requires a declared isolation boundary.');
 if(consequential&&e.control.kind==='not-applicable')add('execution','missing-consequential-control','critical','External or irreversible effects cannot use a not-applicable control.');
 const coverage={transparency:100,stateModel:100,contextStrategy:100,capabilities:100,execution:100};for(const f of findings)coverage[f.axis]=0;
 return {pass:!findings.some(f=>f.severity==='critical'||f.severity==='high'),schemaValid:true,coverageByAxis:coverage,findings,recommendations:findings.length?['Resolve each applicable high or critical finding; marked-inapplicable features remain valid only with their supplied scope rationale.']:['Declaration is coherent for the stated scope. This does not prove implementation or enforcement.'],scope:'Static declaration audit only; no runtime, enforcement, provider, account, or effect evidence was observed.'};
}
function input(argv){const i=argv.indexOf('--input');if(i<0||!argv[i+1])throw Error('usage: agentic_app_audit.mjs --input <spec.json>');return argv[i+1]}
if(process.argv[1]&&fileURLToPath(import.meta.url)===resolve(process.argv[1])){try{const r=auditAgenticAppArchitecture(JSON.parse(readFileSync(input(process.argv.slice(2)),'utf8')));process.stdout.write(JSON.stringify(r,null,2)+'\n');process.exit(r.pass?0:1)}catch(error){process.stderr.write(`agentic_app_audit: ${error.message}\n`);process.exit(1)}}
