import fs from 'node:fs';
import crypto from 'node:crypto';

// The publication digests are generated by `npm run fix:whitepaper-metadata`
// (website-v2) and guarded by the whitepaper-metadata CI job. Pinning the test
// to that file instead of to literals means a regenerated PDF is one --fix
// away from green, while a PDF that changed without a regen still fails here.
const DIGESTS = 'website-v2/public/whitepaper/publication-digests.json';

// The Book is one published PDF. Its typographic character is chosen by
// \pdedition's default in coordination-papers-mega-volume-preamble.tex (Swiss
// today), so the canonical artifact below carries the central edition. The
// maritime and technical drivers stay in the tree, build on demand, and
// publish nothing — so they are not pinned here and have no digest entry.
//
// The eight chapters used to publish a standalone PDF of their own (retired:
// an A4 render of the same words with no margin column, a worse layout of
// the Book's 7x10in trim) and had a row each here. A chapter is chapter N of
// one book now; there is nothing left to pin.
const EXPECTED_PUBLICATIONS = [
  'website-v2/public/whitepaper/coordination-papers-mega-volume.pdf',
];

const digests = JSON.parse(fs.readFileSync(DIGESTS, 'utf8')).pdfs;

describe('Whitepaper PDF hash verification', () => {
  test('the digest manifest lists every publication PDF and nothing else', () => {
    expect(Object.keys(digests).sort()).toEqual([...EXPECTED_PUBLICATIONS].sort());
  });

  EXPECTED_PUBLICATIONS.forEach((path) => {
    test(`SHA-256, size and page count match the manifest for ${path.split('/').pop()}`, () => {
      const file = fs.readFileSync(path);
      const hash = crypto.createHash('sha256').update(file).digest('hex');
      expect(hash).toBe(digests[path].sha256);
      expect(file.length).toBe(digests[path].bytes);
      expect(digests[path].pages).toBeGreaterThan(0);
    });
  });
});
