import fs from 'node:fs';
import crypto from 'node:crypto';

// The publication digests are generated by `npm run fix:whitepaper-metadata`
// (website-v2) and guarded by the whitepaper-metadata CI job. Pinning the test
// to that file instead of to literals means a regenerated PDF is one --fix
// away from green, while a PDF that changed without a regen still fails here.
const DIGESTS = 'website-v2/public/whitepaper/publication-digests.json';

const EXPECTED_PUBLICATIONS = [
  'website-v2/public/whitepaper/coordination-papers-mega-volume.pdf',
  'website-v2/public/whitepaper/single-writer-kernel-whitepaper.pdf',
  'website-v2/public/whitepaper/anchor-protocol-whitepaper.pdf',
  'website-v2/public/whitepaper/sealed-harbor-whitepaper.pdf',
  'website-v2/public/whitepaper/legible-swarm-whitepaper.pdf',
  'website-v2/public/whitepaper/spawn-to-person-whitepaper.pdf',
  'website-v2/public/whitepaper/harbor-economy-whitepaper.pdf',
  'website-v2/public/whitepaper/agent-transactions-whitepaper.pdf',
  'website-v2/public/whitepaper/federated-harbor-whitepaper.pdf',
];

const digests = JSON.parse(fs.readFileSync(DIGESTS, 'utf8')).pdfs;

describe('Whitepaper PDF hash verification', () => {
  test('the digest manifest lists every publication PDF and nothing else', () => {
    expect(Object.keys(digests).sort()).toEqual([...EXPECTED_PUBLICATIONS].sort());
  });

  EXPECTED_PUBLICATIONS.forEach((path) => {
    test(`SHA-256, size and page count match the manifest for ${path.split('/').pop()}`, () => {
      const file = fs.readFileSync(path);
      const hash = crypto.createHash('sha256').update(file).digest('hex');
      expect(hash).toBe(digests[path].sha256);
      expect(file.length).toBe(digests[path].bytes);
      expect(digests[path].pages).toBeGreaterThan(0);
    });
  });
});
