/**
 * PWA static assets for the fleet's HTML surfaces (run receipts + transcript
 * viewer): the web app manifest and the home-screen icons.
 *
 * WHY THIS EXISTS (docs/FLEET-SESSION-TRANSCRIPTS.md, Phase 5): the RFC's iOS
 * answer is "make the web viewer fully responsive and PWA-installable first" —
 * a SwiftUI reader stays a demand-driven later step. These routes are the
 * installable half: Add to Home Screen on iOS reads the apple-touch-icon link,
 * Android/desktop read the manifest.
 *
 * AUTHZ: none, deliberately. Everything here is public app metadata — a name,
 * two colors, three flat-color icons. No run data, no capability tokens, no
 * per-account anything; the pages themselves keep their uniform-404 posture.
 * That is also why these responses are cacheable while every fleet page is
 * no-store.
 */

// Flat-color "pd" tiles (cobalt slab, cream wordmark, lime keel stripe — the
// site's linework palette). Palette-mode PNGs, ~1–2KB each; regenerate by
// redrawing at 180/192/512 with the same three colors if the brand shifts.
const APPLE_TOUCH_ICON_B64 =
  'iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAMAAAAKE/YAAAADAFBMVEUAP7j79+/K2QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMS857AAABRklEQVR42u3aSXKDMBBAUXXuf+hsU2VALcVogPe3TM+pgI2kUiRJkiRJkiRJkiRJryz+Bg0NDQ0NDQ0NDQ29A7rlip+8m9GHp4+Gi8bRzuPR8VGafHiOEeiIvDrOdr75f/rqcrULx+nOY9EReXWc7zwUHZFXx7PQMRQdkVfHIujLJ1/twMrpbkZff29UN85An2+7Oi57xuHozs8zAN3355yLTv/GbLhH56Ljv0ctjS5D0aULXRZDF2jordHph0v1mQYNDQ2deKeZi/blAv18dDwW7R3xLW/jW457RHZbfpOxvPogZ9eo6aSh3sgN2a4yPr3lTEBpMK8z5/Kw2a3k7bDU5Gf6Jp6CLg3mdebGv78KYcraiZ4fXDNWqZSmC85b92ONFDQ0NDQ0NDQ0NDS0JEmSJEmSJEmSJOk1/WwYNDQ0NDT01/sFAQMbo4Pxq0oAAAAASUVORK5CYII=';
const ICON_192_B64 =
  'iVBORw0KGgoAAAANSUhEUgAAAMAAAADACAMAAABlApw1AAADAFBMVEUAP7j79+/K2QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMS857AAABTElEQVR42u3awW6DMBRFQV7//6O7q1QVEz/J5eJkzhYTmA0x2MchSZIkSZIkSZIkSZKke6tfAQAAAAAAAAAAAAAAAHwOoHflkxu9CXB+ld7F63R4EFB/atz+z/AYoKo6guHwFKCqJRgPDwGqWoKL4RlAVUtwNTwBqKs7qtb9hwC1DlBJwOTDdPrEmwHDY6/OnfrR/wfM3OGro0nAxCRh4mAOMD+l7Jz4FEA9H9CY1bdOBFgPqEcCGsDm33TuzXUOcAAAAAAAAAAAAAAAvB9gsxea7V8pfZWIA7b/sNX4tHg8E7D9x939P6/vv8Cx/xLTGyzy7bvMum6hOzaZW7fV4AjNRpdt9kgBlm23iQG6T/Hh6OALTfMROBiefSNrXjm3O9HuTgAAAAAAAAAAAAAAAIBPBUiSJEmSJEmSJEmSJG3f1+YBAAAAAAAAJPsGLFsf96hpxJQAAAAASUVORK5CYII=';
const ICON_512_B64 =
  'iVBORw0KGgoAAAANSUhEUgAAAgAAAAIACAMAAADDpiTIAAADAFBMVEUAP7j79+/K2QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMS857AAAFZklEQVR42u3d647TQAyAUZv3f2gkBNKCKiAzHjtNz/lPJrG/LXujRAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/JD/w5gEgAAQAAJAAAgAASAABIAAEAACQAAIAAEgAASAABAAAkAACAABIAAEgAAQAAJAAAgAASAABIAAEAACQAAIAAEgAASAABAAAkAACAABIAAE8DYjnd6oAO7w4TT9wSyAqhfDjT8+fPcCOBvA7BhzfY0CqNhhZg4OMnPjfAHsB5C5tYK29b88XwC7AWRurqBx/S/OF8ClWRQsIGf3/+f5Ath6CcjMwQQy988XwE4AFRvo3/9v5wtgI4CSDQzs/+v5AlgOIGs2MLH/L+cLYDWArNkCsuh8ASwGkDlaQFadL4CpAHJ2/7/OF8BaAHUbmNr/z/MFsBRA4QbG9i+A9QByNIDMwvMFsBBA6QYGA0gBDAeQs/sXwFoAmZMFZO3xArgcQD4ogBTAcAA5u38BXA8gRwPIEQK4+iFzbLgCmA6g/mdEZ2+x+PEE8B/juU8Ap55QAP8YzqnxFlxXALUBVFzrzB12PKUASi7Wuv/jn6Z8VABFV6u/weIHFcDZMZffYPWTCuDwmHtfAM5+ofI5ATR+xNZfTgAtQ7nvxUIALTOZCCAEIIC+ryk/NYDqa7bvXwD3+t5NfwAhgJaJdAdw5HkFcHzK/S8AAmgaSO93lUIADQHEMwIIAQhAAOfnUXLN2V8xFUDDlAUgAAE8MoDoC+DUIwugYcoCEMBdb00A41MWgADO7EkA7zFlAQhAAAIQgAAEMB3ASFkHP1kXwG0CSAE8NYDoCSAEIAABCEAAAhCAAAQgAAEIQADVs4inBRACEIAABCAAAQhAAAIQgAAEIAABCEAAAhCAAAQgAAEIQAACEIAABCCAJwbg9wEEIIDjsxCAAAQgAAEIQAACEIAABPBhAWRPAP55+HsHEBMBpADeIQBvEXOfALxHkAAEIAABCKDxi4Bb35oA7hOAN4vuCMDbxQtg4JVFAAI4cGspgIZxZF8A/tMoAQjgTQOY+OspBdAwj6JrDt6aAB4aQAqgYyAC+OwAyq44dmsC2JrIfQNIATRMJLsDyANPK4DzYxbAMwOovFztraUAOmYigMcGULqzG19MABtDGXo5yepHFcDaVKb+Pin7rpIAmsbc/Z2bFEDDXAa/pqz5BUMBbA0mZwPIyscUwPXRnBlvwVUzBVAZwOvhnBpv950JYGk8B6fbe2cCWJjQ2en23pkAOszeozeImA5g+CYFcHW28agAwnsFDwcw/DolgOsBxIMCCAEsBBCj+y8/XgCDAQx/shoCWAogHhJACGAxgBjdf/HxAhgLYPg7FiGA5QBidv8l54cANgKI2f0XnB8C2AogZve/fX4IYDOAmN3/5vkhgO0AYnb/ZT/eFcBqADG7/43zQwAlAcTo+svOF8ByALW/R9qVwMo1BLDx4XN0lgXHC2AngPl/Zrl9vAD2Aph/r53N8wWwG8D8f7uwdbwAWsY4fO/B4QD++ueH799qewJ4dZHhZ7DU9gAQAAJAAAgAASAABIAAEAACQAAIAAEgAASAABAAAkAACAABIAAEgAAQAAJAAAgAASAABIAAEAACQAAIAAEgAASAABAAAkAACAABIAAEgAAQAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAtW98NAEIAAEgAASAABAAAkAACAABIAAEgAAQAAJAAAgAASAABIAAEAACQAAIAAHwdr4DDcLgIkdKGJsAAAAASUVORK5CYII=';

function pngResponse(b64: string): Response {
  const raw = atob(b64);
  const bytes = new Uint8Array(raw.length);
  for (let i = 0; i < raw.length; i += 1) bytes[i] = raw.charCodeAt(i);
  return new Response(bytes, {
    status: 200,
    headers: {
      'Content-Type': 'image/png',
      // Public static asset — safe to cache, unlike the no-store fleet pages.
      'Cache-Control': 'public, max-age=86400',
      'X-Content-Type-Options': 'nosniff',
    },
  });
}

export function handleFleetAppleTouchIcon(): Response {
  return pngResponse(APPLE_TOUCH_ICON_B64);
}

export function handleFleetIcon192(): Response {
  return pngResponse(ICON_192_B64);
}

export function handleFleetIcon512(): Response {
  return pngResponse(ICON_512_B64);
}

/**
 * The web app manifest. start_url is the operator's runs index — the one
 * fleet surface with a stable URL (run receipts are per-run capability URLs,
 * so pinning THE app means pinning the index; signed-out it lands on /login,
 * which is the honest behavior for an authenticated surface). scope stays "/"
 * so opened run receipts and transcript viewers remain inside the installed
 * app instead of bouncing to the browser.
 */
export function handleFleetManifest(): Response {
  const manifest = {
    name: 'Port Daddy Fleet',
    short_name: 'PD Fleet',
    description: 'Fleet run receipts and raw ship session transcripts.',
    start_url: '/account/runs',
    scope: '/',
    display: 'standalone',
    background_color: '#f2eee6',
    theme_color: '#f2eee6',
    icons: [
      { src: '/fleet/icon-192.png', sizes: '192x192', type: 'image/png' },
      { src: '/fleet/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
  };
  return new Response(JSON.stringify(manifest, null, 2), {
    status: 200,
    headers: {
      'Content-Type': 'application/manifest+json',
      'Cache-Control': 'public, max-age=86400',
      'X-Content-Type-Options': 'nosniff',
    },
  });
}
