// tests/unit/purser/actor-binding-sanitization.test.ts

/**
 * Unit tests for the kernel‑issued actor principal validation (CAP0).
 *
 * The contract requires that only canonical Crockford‑base32 ULIDs are accepted
 * as actor identifiers.  The constraints are:
 *
 *  - Exactly 26 characters long.
 *  - Characters must be from the Crockford base‑32 alphabet
 *    (0‑9, A‑Z excluding I, L, O, U).
 *  - The first character must be in the range `0`‑`7` (i.e. the ULID timestamp
 *    high‑bits cannot exceed the maximum value for a 48‑bit timestamp).
 *
 * The exported helper `isCanonicalActorPrincipal` is expected to return a
 * boolean (`true` for a valid actor, `false` otherwise) or throw on invalid
 * input.  The test normalises both behaviours via the `accepts` wrapper.
 */

import { isCanonicalActorPrincipal } from '../../../lib/macaroon-ffi.ts';

/**
 * Normalises the validation function's possible behaviours:
 *   - Returns the boolean result when the function returns a value.
 *   - Returns `false` when the function throws.
 *   - Coerces any non‑boolean truthy value to `true`.
 */
function accepts(actor: string): boolean {
  try {
    const result = (isCanonicalActorPrincipal as (a: string) => unknown)(actor);
    return Boolean(result);
  } catch {
    return false;
  }
}

describe('kernel actor principal validation (Crockford‑base32 ULID)', () => {
  // A known‑good ULID generated by a reference implementation.
  const VALID_ULID = '01ARZ3NDEKTSV4RRFFQ69G5FAV';

  test('accepts a correct ULID', () => {
    expect(accepts(VALID_ULID)).toBe(true);
  });

  test('rejects ULIDs with an invalid first character (>7)', () => {
    const bad = '81ARZ3NDEKTSV4RRFFQ69G5FAV'; // first char '8'
    expect(accepts(bad)).toBe(false);
  });

  test('rejects ULIDs that are too short', () => {
    const short = VALID_ULID.slice(0, 25);
    expect(accepts(short)).toBe(false);
  });

  test('rejects ULIDs that are too long', () => {
    const long = VALID_ULID + 'X';
    expect(accepts(long)).toBe(false);
  });

  test('rejects ULIDs containing prohibited characters (I, L, O, U)', () => {
    const withI = VALID_ULID.replace('R', 'I'); // inject 'I'
    const withL = VALID_ULID.replace('R', 'L');
    const withO = VALID_ULID.replace('R', 'O');
    const withU = VALID_ULID.replace('R', 'U');

    expect(accepts(withI)).toBe(false);
    expect(accepts(withL)).toBe(false);
    expect(accepts(withO)).toBe(false);
    expect(accepts(withU)).toBe(false);
  });

  test('rejects ULIDs containing lowercase letters', () => {
    const lower = VALID_ULID.toLowerCase();
    expect(accepts(lower)).toBe(false);
  });

  test('rejects completely unrelated strings', () => {
    const random = 'THISISNOTAVALIDULID1234567890';
    expect(accepts(random)).toBe(false);
  });

  test('rejects empty string', () => {
    expect(accepts('')).toBe(false);
  });

  test('rejects whitespace‑padded identifiers', () => {
    const padded = ` ${VALID_ULID} `;
    expect(accepts(padded)).toBe(false);
  });

  test('rejects strings with non‑ASCII characters', () => {
    const unicode = '01ARZ3NDEKTSV4RRFFQ69G5FÁV'; // accented V
    expect(accepts(unicode)).toBe(false);
  });

  test('ensures deterministic behaviour (no side‑effects)', () => {
    const first = accepts(VALID_ULID);
    const second = accepts(VALID_ULID);
    expect(first).toBe(true);
    expect(second).toBe(true);
  });
});