// tests/unit/purser/test_xie_et_al_content_flagging.test.ts

import { readFileSync, existsSync } from 'fs';
import { resolve, join } from 'path';
import { describe, test, expect } from '@jest/globals';

/**
 * Helper to resolve a path relative to this test file.
 */
const __dirname = new URL('.', import.meta.url).pathname;

/**
 * Load the audit report generated by `scripts/audit-skills.mjs`.
 */
const auditReportPath = resolve(__dirname, '../../../metadata/audit-report.json');
const auditReportRaw = readFileSync(auditReportPath, 'utf8');
const auditReport = JSON.parse(auditReportRaw);

/**
 * Find the exported record for the xie-et-al-2025-survey-llm-task-planning skill.
 */
const skillName = 'xie-et-al-2025-survey-llm-task-planning';
const skillRecord = auditReport.skills?.find((s: any) => s.name === skillName);

describe('xie-et-al-2025-survey-llm-task-planning content flagging', () => {
  test('audit report contains a content‑mismatch flag for the skill', () => {
    expect(skillRecord).toBeDefined();

    const flags = skillRecord?.flags;
    expect(flags).toBeDefined();
    expect(Array.isArray(flags)).toBe(true);

    const hasContentMismatch = flags?.some((f: any) => {
      if (typeof f === 'string') {
        return f.includes('content-mismatch');
      }
      if (f && typeof f === 'object') {
        return f.type === 'content-mismatch';
      }
      return false;
    });

    expect(hasContentMismatch).toBe(true);
  });

  test('skill is imported unchanged (all required files exist)', () => {
    const skillDir = resolve(__dirname, '../../../skills/xie-et-al-2025-survey-llm-task-planning');
    expect(existsSync(skillDir)).toBeTruthy();

    const skillMd = join(skillDir, 'SKILL.md');
    expect(existsSync(skillMd)).toBeTruthy();

    const referencesDir = join(skillDir, 'references');
    const diagramsDir = join(skillDir, 'diagrams');

    expect(existsSync(referencesDir)).toBeTruthy();
    expect(existsSync(diagramsDir)).toBeTruthy();

    // Basic sanity: the frontmatter contains a description field
    const skillContent = readFileSync(skillMd, 'utf8');
    const frontmatterMatch = skillContent.match(/^---\s*([\s\S]*?)\s*---/);
    const frontmatter = frontmatterMatch ? frontmatterMatch[1] : '';
    expect(frontmatter).toContain('description:');
  });
});