#!/usr/bin/env bash
# Record the terminal sessions the Book prints ("At the terminal" listings).
# Every transcript is produced by running the real CLI against an isolated
# daemon profile, then normalised (ULIDs, timestamps, PIDs, durations) so the
# checked-in text is stable across runs. Usage:
#   scripts/harbor-research/record_sessions.sh            # (re)record all
#   scripts/harbor-research/record_sessions.sh --check    # exit 1 on drift
# Output fragments live under whitepaper/figures/session-*.tex and are \input
# by the chapters like figures.
set -euo pipefail
cd "$(dirname "$0")/../.."
PD="node bin/port-daddy-cli.js"
PROFILE=demo
PORT=9877
OUT=whitepaper/figures
MODE=${1:-record}
TMP=$(mktemp -d)
trap 'timeout 30 $PD daemon stop $PROFILE >/dev/null 2>&1 || true; rm -rf "$TMP"' EXIT

normalise() {
  sed -E \
    -e 's/[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9:.]+Z/<timestamp>/g' \
    -e 's/[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}/<timestamp>/g' \
    -e 's/\b[0-9A-HJKMNP-TV-Z]{26}\b/<actor-id>/g' \
    -e 's/\b[0-9A-HJKMNP-TV-Z]{24}\b/<actor-id>/g' \
    -e 's/PID [0-9]+/PID <pid>/g' \
    -e 's/Expires in: [0-9]+s/Expires in: <n>s/g' \
    -e 's/^⚠.*$//' \
    -e '/^$/N;/^\n$/D'
}

run() { local id=$1; shift; env PORT_DADDY_AGENT_ID="$id" timeout 30 $PD "$@" 2>&1 || true; }

wrap() {  # title, transcript file, out file
  {
    echo "% GENERATED by scripts/harbor-research/record_sessions.sh -- do not edit."
    echo "\\begin{pdsession}[$1]"
    cat "$2"
    echo "\\end{pdsession}"
  } > "$3"
}

# ---- session 1: two agents, one lock (chapter 1, the resource organ) -------
timeout 90 $PD daemon start $PROFILE --port $PORT >/dev/null 2>&1
eval "$($PD daemon env $PROFILE 2>/dev/null)"
sleep 2
{
  echo '$ export PORT_DADDY_AGENT_ID=alice'
  echo '$ pd lock lib.webhooks.ts --ttl 600000'
  run alice lock lib.webhooks.ts --ttl 600000
  echo
  echo '$ export PORT_DADDY_AGENT_ID=bob'
  echo '$ pd lock lib.webhooks.ts --wait --timeout 2000'
  run bob lock lib.webhooks.ts --wait --timeout 2000
  echo
  echo '$ pd locks'
  run bob locks
  echo
  echo '$ export PORT_DADDY_AGENT_ID=alice'
  echo '$ pd unlock lib.webhooks.ts'
  run alice unlock lib.webhooks.ts
  echo
  echo '$ export PORT_DADDY_AGENT_ID=bob'
  echo '$ pd lock lib.webhooks.ts'
  run bob lock lib.webhooks.ts
} | normalise > "$TMP/s1.txt"
wrap "two agents, one lock, one holder at a time" "$TMP/s1.txt" "$TMP/session-swk-lock-demo.tex"

# ---- compare or install ----------------------------------------------------
status=0
for f in "$TMP"/session-*.tex; do
  b=$(basename "$f")
  if [ "$MODE" = "--check" ]; then
    if ! diff -q "$f" "$OUT/$b" >/dev/null 2>&1; then echo "DRIFT: $OUT/$b"; diff "$OUT/$b" "$f" || true; status=1; fi
  else
    cp "$f" "$OUT/$b"; echo "wrote $OUT/$b"
  fi
done
[ "$MODE" = "--check" ] && [ $status -eq 0 ] && echo "sessions match"
exit $status
