#!/usr/bin/env bash
# Record the terminal sessions the Book prints ("At the terminal" listings).
# Every transcript is produced by running the real CLI against an isolated
# daemon profile, then normalised (ULIDs, timestamps, PIDs, durations) so the
# checked-in text is stable across runs. Usage:
#   scripts/harbor-research/record_sessions.sh            # (re)record all
#   scripts/harbor-research/record_sessions.sh --check    # exit 1 on drift
# Output fragments live under whitepaper/figures/session-*.tex and are \input
# by the chapters like figures.
set -euo pipefail
cd "$(dirname "$0")/../.."
PD="node bin/port-daddy-cli.js"
PROFILE=demo
PORT=9877
OUT=whitepaper/figures
MODE=${1:-record}
TMP=$(mktemp -d)
trap 'timeout 30 $PD daemon stop $PROFILE >/dev/null 2>&1 || true; rm -rf "$TMP"' EXIT

normalise() { python3 scripts/harbor-research/normalise_session.py; }

run() { local id=$1; shift; env PORT_DADDY_AGENT_ID="$id" timeout 30 $PD "$@" 2>&1 || true; }

wrap() {  # title, transcript file, out file
  {
    echo "% GENERATED by scripts/harbor-research/record_sessions.sh -- do not edit."
    echo "\\begin{pdsession}[$1]"
    cat "$2"
    echo "\\end{pdsession}"
  } > "$3"
}

# ---- session 1: two agents, one lock (chapter 1, the resource organ) -------
timeout 90 $PD daemon start $PROFILE --port $PORT >/dev/null 2>&1
eval "$($PD daemon env $PROFILE 2>/dev/null)"
sleep 2
# the demo profile persists between runs: release anything a previous recording left
run alice unlock lib.webhooks.ts >/dev/null 2>&1; run bob unlock lib.webhooks.ts >/dev/null 2>&1
{
  echo '$ export PORT_DADDY_AGENT_ID=alice'
  echo '$ pd lock lib.webhooks.ts --ttl 600000'
  run alice lock lib.webhooks.ts --ttl 600000
  echo
  echo '$ export PORT_DADDY_AGENT_ID=bob'
  echo '$ pd lock lib.webhooks.ts --wait --timeout 2000'
  run bob lock lib.webhooks.ts --wait --timeout 2000
  echo
  echo '$ pd locks'
  run bob locks
  echo
  echo '$ export PORT_DADDY_AGENT_ID=alice'
  echo '$ pd unlock lib.webhooks.ts'
  run alice unlock lib.webhooks.ts
  echo
  echo '$ export PORT_DADDY_AGENT_ID=bob'
  echo '$ pd lock lib.webhooks.ts'
  run bob lock lib.webhooks.ts
} | normalise > "$TMP/s1.txt"
wrap "two agents, one lock, one holder at a time" "$TMP/s1.txt" "$TMP/session-swk-lock-demo.tex"

# ---- session 2: the work-unit checker and its mutation suite (chapter 1) ----
{
  echo '$ python3 skills/harbor-results/scripts/c0_workunit.py'
  timeout 300 python3 skills/harbor-results/scripts/c0_workunit.py 2>&1 \
    | sed -n '/^BASELINE/,/^Guards restored/p' | sed -E 's/ +$//'
} | normalise > "$TMP/s2.txt"
wrap "the work-unit machine: 536 states, every guard load-bearing" "$TMP/s2.txt" "$TMP/session-swk-workunit-check.tex"

# ---- sessions 3 and 4: model-checker traces, from the committed run logs -----
# TLC is not re-run here (proofs.yml does that); the session is an excerpt of
# the checked-in log, so the printed trace is the one CI reproduces and drifts
# only when the log does. excerpt_trace.py keeps the named states and strips
# wall-clock stamps.
{
  echo '$ java -cp tla2tools.jar tlc2.TLC -config claim_signaling_delta30.cfg claim_signaling.tla'
  python3 scripts/harbor-research/excerpt_trace.py proofs/economics/claim_signaling_delta30.run.log --keep-states 1,2,3,6
} | normalise > "$TMP/s3.txt"
wrap "claim signaling at \\(\\delta = 0.30\\): TLC finds the profitable deviation" "$TMP/s3.txt" "$TMP/session-bc-delta30.tex"

{
  echo '$ java -cp tla2tools.jar tlc2.TLC -config CardRevocation_rollback.cfg CardRevocation.tla'
  python3 scripts/harbor-research/excerpt_trace.py proofs/relay/CardRevocation_rollback.run.log
} | normalise > "$TMP/s4.txt"
wrap "the rollback configuration fails by design" "$TMP/s4.txt" "$TMP/session-fh-rollback.tex"

# ---- session 5: the ProVerif attack trace and its fix (chapter 2) ------------
# ProVerif is not re-run here either (proofs.yml diffs the committed results);
# the session prints the query, the reachable goal and the verdict from the
# committed results of the version-6 model, then the verdict of version 7.
{
  echo '$ proverif analyses/harbor_card_v6_multihop_attack.pv'
  grep -E "^-- Query not event\(Accepted|^goal reachable" analyses/harbor_card_v6_results.txt | head -2
  echo
  echo '  ... derivation, 11 steps, elided; the trace is in analyses/harbor_card_v6_results.txt ...'
  echo
  grep -E "^A trace has been found|^RESULT not event\(Accepted" analyses/harbor_card_v6_results.txt | head -2
  echo
  echo '$ proverif analyses/harbor_card_v7_multihop_fixed.pv'
  grep -E "^RESULT not event\(Accepted" analyses/harbor_card_v7_results.txt | head -1
} | normalise > "$TMP/s5.txt"
wrap "the multi-hop attack on version 6, and version 7 closing it" "$TMP/s5.txt" "$TMP/session-anchor-v6-attack.tex"

# ---- compare or install ----------------------------------------------------
# Kernel sessions (session-swk-*) live beside the kernel's figures; every other
# chapter resolves figures/ under website-v2/public/whitepaper.
status=0
for f in "$TMP"/session-*.tex; do
  b=$(basename "$f")
  case "$b" in session-swk-*) OUT=whitepaper/figures;; *) OUT=website-v2/public/whitepaper/figures;; esac
  if [ "$MODE" = "--check" ]; then
    if ! diff -q "$f" "$OUT/$b" >/dev/null 2>&1; then echo "DRIFT: $OUT/$b"; diff "$OUT/$b" "$f" || true; status=1; fi
  else
    cp "$f" "$OUT/$b"; echo "wrote $OUT/$b"
  fi
done
[ "$MODE" = "--check" ] && [ $status -eq 0 ] && echo "sessions match"
exit $status
