import { describe, expect, jest, test } from '@jest/globals';
import {
  ATTRIBUTION_BLOCK,
  ATTRIBUTION_LINE,
  DEFAULT_RELAY_ORIGIN,
  FLEETBOT_APP_LOGIN,
  FleetbotPublishError,
  MissingActuatorError,
  assertBotAuthorship,
  buildActionRequest,
  capabilityCoversRequest,
  capabilitySpec,
  classifyPublishFailure,
  hasAttribution,
  publish,
  requestHashOf,
  withAttribution,
} from '../../lib/fleetbot-publish-client.js';
import {
  FLEETBOT_ACTION_SCHEMA,
  FLEETBOT_PUBLISHER_CAPABILITY_SCHEMA,
  FLEETBOT_RECEIPT_SCHEMA,
  roadmapTrailers,
  type FleetbotAuthorship,
  type FleetbotPublisherCapability,
  type FleetbotReceipt,
} from '../../lib/github-publisher-contract.js';

const authorship: FleetbotAuthorship = {
  actorId: '01ACTOR',
  agentId: 'agent-publisher',
  sessionId: 'session-publisher',
  purpose: 'Publish a tested fix',
  identityProject: 'port-daddy',
  roadmapItem: 'fleetbot-publisher',
  sidequestReason: null,
  worktreeId: 'worktree-1',
  sourceBranch: 'claude/fleetbot-publish-client',
};

const BASE_SHA = 'a'.repeat(40);
const HEAD_SHA = 'b'.repeat(40);
const SCOPE = { baseBranch: 'main', baseSha: BASE_SHA, headSha: HEAD_SHA };
const ACCOUNT_TOKEN = `pdu_${'0'.repeat(64)}`;

function publishInput(body = 'Summary\n\nRoadmap-Item: fleetbot-publisher') {
  return {
    operation: 'pull-request.publish' as const,
    repository: 'curiositech/port-daddy',
    sessionId: 'session-publisher',
    authorship,
    payload: {
      baseBranch: 'main',
      baseSha: BASE_SHA,
      sourceHeadSha: HEAD_SHA,
      sourceTreeSha: 'c'.repeat(40),
      sourceCommittedAt: 1_760_000_000,
      commitMessage: 'feat: thing',
      changes: [],
      title: 'feat: thing',
      body,
      draft: false,
    },
  };
}

function capabilityFor(request: ReturnType<typeof buildActionRequest>): FleetbotPublisherCapability {
  return {
    schema: FLEETBOT_PUBLISHER_CAPABILITY_SCHEMA,
    accountTokenHash: 'd'.repeat(64),
    daemonFingerprint: 'e'.repeat(64),
    signingKeyGeneration: 1,
    sessionId: request.sessionId,
    repository: request.repository,
    operation: request.operation,
    baseBranch: 'main',
    baseSha: BASE_SHA,
    headSha: HEAD_SHA,
    requestHash: requestHashOf(request),
    issuedAt: 1_760_000_000,
    expiresAt: 1_760_000_300,
    nonce: 'f'.repeat(64),
  };
}

function providerFor(request: ReturnType<typeof buildActionRequest>) {
  return {
    mint: jest.fn(async () => ({
      capability: capabilityFor(request),
      capabilitySignature: '1'.repeat(128),
    })),
  };
}

function receiptFor(overrides: Partial<FleetbotReceipt> = {}): FleetbotReceipt {
  return {
    schema: FLEETBOT_RECEIPT_SCHEMA,
    receiptId: 'github_receipt_abc',
    authority: 'port-daddy-relay-github-app',
    appSlug: 'port-daddy',
    operation: 'pull-request.publish',
    repository: 'curiositech/port-daddy',
    idempotencyKey: 'pd-gh-abc',
    accountUserId: 'user-1',
    accountGithubUserId: 2093678,
    actorId: '01ACTOR',
    agentId: 'agent-publisher',
    sessionId: 'session-publisher',
    roadmapItem: 'fleetbot-publisher',
    resourceUrl: 'https://github.com/curiositech/port-daddy/pull/1',
    resourceNumber: 1,
    publishedBranch: 'claude/fleetbot-publish-client',
    sourceHeadSha: HEAD_SHA,
    githubHeadSha: HEAD_SHA,
    result: 'created',
    verifiedAt: 1_760_000_100,
    relayPublicKey: '9'.repeat(64),
    signature: '8'.repeat(128),
    tokenCleanup: 'confirmed',
    ...overrides,
  };
}

describe('attribution', () => {
  test('appends the exact required block', () => {
    expect(withAttribution('Body text')).toBe(`Body text${ATTRIBUTION_BLOCK}`);
    expect(withAttribution('Body text')).toMatch(/\n\n---\n_Generated by \[Claude Code\]\(https:\/\/claude\.ai\/code\)_$/);
  });

  test('is idempotent — re-stamping does not double the footer', () => {
    const once = withAttribution('Body text');
    const twice = withAttribution(once);
    expect(twice).toBe(once);
    expect(twice.split(ATTRIBUTION_LINE)).toHaveLength(2);
  });

  test('normalizes a hand-written footer to the canonical block', () => {
    const sloppy = `Body text\n-----\n${ATTRIBUTION_LINE}   \n\n`;
    expect(withAttribution(sloppy)).toBe(`Body text${ATTRIBUTION_BLOCK}`);
  });

  test('hasAttribution detects the stamped form only', () => {
    expect(hasAttribution(withAttribution('x'))).toBe(true);
    expect(hasAttribution('x')).toBe(false);
  });

  test('buildActionRequest stamps the body so callers cannot forget', () => {
    const request = buildActionRequest(publishInput());
    expect(hasAttribution((request.payload as { body: string }).body)).toBe(true);
  });

  test('stamping leaves exactly one Roadmap-Item trailer intact', () => {
    const request = buildActionRequest(publishInput());
    expect(roadmapTrailers((request.payload as { body: string }).body)).toEqual(['fleetbot-publisher']);
  });

  test('comments and review replies are stamped too', () => {
    for (const operation of ['pull-request.comment', 'pull-request.review-reply'] as const) {
      const request = buildActionRequest({
        operation,
        repository: 'curiositech/port-daddy',
        sessionId: 'session-publisher',
        authorship,
        payload: {
          baseBranch: 'main',
          baseSha: BASE_SHA,
          pullRequestNumber: 7,
          expectedGithubHeadSha: HEAD_SHA,
          body: 'A remark.',
          ...(operation === 'pull-request.review-reply' ? { commentId: 42 } : {}),
        },
      });
      expect(hasAttribution((request.payload as { body: string }).body)).toBe(true);
    }
  });

  test('operations without prose are not stamped', () => {
    const request = buildActionRequest({
      operation: 'pull-request.ready',
      repository: 'curiositech/port-daddy',
      sessionId: 'session-publisher',
      authorship,
      payload: {
        baseBranch: 'main',
        baseSha: BASE_SHA,
        pullRequestNumber: 7,
        expectedGithubHeadSha: HEAD_SHA,
      },
    });
    expect(request.payload).not.toHaveProperty('body');
  });
});

describe('request assembly', () => {
  test('binds the idempotency key to the canonical request', () => {
    const request = buildActionRequest(publishInput());
    expect(request.idempotencyKey).toBe(`pd-gh-${requestHashOf(request)}`);
    expect(request.idempotencyKey).toMatch(/^pd-gh-[0-9a-f]{64}$/);
  });

  test('carries exactly the nine keys Relay accepts', () => {
    const request = buildActionRequest(publishInput());
    expect(Object.keys(request).sort()).toEqual(
      ['authorship', 'idempotencyKey', 'operation', 'payload', 'repository', 'schema', 'sessionId'].sort(),
    );
    expect(request.schema).toBe(FLEETBOT_ACTION_SCHEMA);
  });

  test('identical inputs produce an identical key; a changed body does not', () => {
    const a = buildActionRequest(publishInput());
    const b = buildActionRequest(publishInput());
    const c = buildActionRequest(publishInput('Different\n\nRoadmap-Item: fleetbot-publisher'));
    expect(a.idempotencyKey).toBe(b.idempotencyKey);
    expect(c.idempotencyKey).not.toBe(a.idempotencyKey);
  });

  test('rejects a non-lowercase repository before any network call', () => {
    expect(() => buildActionRequest({ ...publishInput(), repository: 'Curiositech/Port-Daddy' }))
      .toThrow(/lowercase/);
  });
});

describe('capability scope', () => {
  test('spec binds repository, operation, session and request hash', () => {
    const request = buildActionRequest(publishInput());
    const spec = capabilitySpec(request, SCOPE);
    expect(spec.requestHash).toBe(requestHashOf(request));
    expect(spec.repository).toBe('curiositech/port-daddy');
    expect(spec.operation).toBe('pull-request.publish');
  });

  test('rejects a malformed sha', () => {
    const request = buildActionRequest(publishInput());
    expect(() => capabilitySpec(request, { ...SCOPE, headSha: 'nope' })).toThrow(/git SHAs/);
  });

  test('detects a capability minted for a different request', () => {
    const request = buildActionRequest(publishInput());
    const other = buildActionRequest(publishInput('Other\n\nRoadmap-Item: fleetbot-publisher'));
    expect(capabilityCoversRequest(capabilityFor(request), request)).toEqual({ ok: true });
    const mismatch = capabilityCoversRequest(capabilityFor(other), request);
    expect(mismatch.ok).toBe(false);
    expect((mismatch as { reason: string }).reason).toMatch(/requestHash/);
  });
});

describe('failure classification', () => {
  test('404 is named as a deployment fact, not an auth failure', () => {
    const result = classifyPublishFailure(404, null, DEFAULT_RELAY_ORIGIN);
    expect(result.code).toBe('ROUTE_NOT_DEPLOYED');
    expect(result.message).toMatch(/not deployed|absent from the deployed/i);
    expect(result.message).not.toMatch(/unauthenticated|permission/i);
  });

  test('401 CAPABILITY_INVALID says re-mint, not retry', () => {
    const result = classifyPublishFailure(401, { code: 'CAPABILITY_INVALID', error: 'bad' }, DEFAULT_RELAY_ORIGIN);
    expect(result.remedy).toMatch(/Re-mint/i);
    expect(result.remedy).toMatch(/do not retry the same bytes/i);
  });

  test('502 token-cleanup warns the mutation probably landed', () => {
    const result = classifyPublishFailure(502, { code: 'TOKEN_CLEANUP_UNCONFIRMED' }, DEFAULT_RELAY_ORIGIN);
    expect(result.remedy).toMatch(/likely LANDED|read GitHub back/i);
  });

  test('503 unconfigured points at relay secrets, never at the caller', () => {
    const result = classifyPublishFailure(503, { code: 'PUBLISHER_UNCONFIGURED' }, DEFAULT_RELAY_ORIGIN);
    expect(result.remedy).toMatch(/operator must/i);
  });
});

describe('receipt verification', () => {
  const expected = { repository: 'curiositech/port-daddy', operation: 'pull-request.publish' as const };

  test('accepts a receipt from the Relay GitHub App', () => {
    expect(() => assertBotAuthorship(receiptFor(), expected)).not.toThrow();
  });

  test('rejects a receipt whose authority is not the App', () => {
    expect(() => assertBotAuthorship(receiptFor({ authority: 'something-else' as never }), expected))
      .toThrow(/not the Relay GitHub App/);
  });

  test('rejects a receipt naming a different repository', () => {
    expect(() => assertBotAuthorship(receiptFor({ repository: 'someone/else' }), expected))
      .toThrow(/names repository/);
  });

  // A Relay pointed at some other GitHub App returns a well-formed, correctly
  // signed receipt. Without this check the client would report the mutation as
  // published "as the bot" while GitHub showed a different author — the exact
  // misattribution this module exists to prevent.
  test('rejects a receipt from a different GitHub App', () => {
    expect(() => assertBotAuthorship(receiptFor({ appSlug: 'someone-elses-app' }), expected))
      .toThrow(/names App "someone-elses-app\[bot\]", expected "port-daddy\[bot\]"/);
  });

  test('still rejects a receipt carrying no App slug at all', () => {
    expect(() => assertBotAuthorship(receiptFor({ appSlug: '' }), expected))
      .toThrow(/carries no App slug/);
  });

  // A deployment that installs a differently-named App states that explicitly
  // rather than by weakening the default.
  test('an explicit expectedAppLogin admits a deliberately different App', () => {
    expect(() => assertBotAuthorship(
      receiptFor({ appSlug: 'other-harbor' }),
      { ...expected, expectedAppLogin: 'other-harbor[bot]' },
    )).not.toThrow();
  });

  test('the default expectation is the Fleetbot App login', () => {
    expect(FLEETBOT_APP_LOGIN).toBe('port-daddy[bot]');
    expect(() => assertBotAuthorship(receiptFor({ appSlug: 'port-daddy' }), expected)).not.toThrow();
  });
});

describe('publish admission', () => {
  test('refuses loudly when no capability provider is wired', async () => {
    const request = buildActionRequest(publishInput());
    const fetchImpl = jest.fn();
    await expect(
      publish(request, {
        accountToken: ACCOUNT_TOKEN,
        capabilityProvider: null,
        scope: SCOPE,
        fetchImpl: fetchImpl as unknown as typeof fetch,
      }),
    ).rejects.toBeInstanceOf(MissingActuatorError);
    expect(fetchImpl).not.toHaveBeenCalled();
  });

  test('refuses a GitHub token in place of the pdu_ bearer, and says why', async () => {
    const request = buildActionRequest(publishInput());
    const fetchImpl = jest.fn();
    const err = await publish(request, {
      accountToken: 'ghp_notanaccounttoken',
      capabilityProvider: providerFor(request),
      scope: SCOPE,
      fetchImpl: fetchImpl as unknown as typeof fetch,
    }).catch((e: unknown) => e as FleetbotPublishError);

    expect(err).toBeInstanceOf(FleetbotPublishError);
    expect((err as FleetbotPublishError).code).toBe('ACCOUNT_TOKEN_MISSING');
    expect((err as FleetbotPublishError).remedy).toMatch(/Do not substitute a GitHub PAT/i);
    expect(fetchImpl).not.toHaveBeenCalled();
  });

  test('a 404 from the relay surfaces as ROUTE_NOT_DEPLOYED with preserved work', async () => {
    const request = buildActionRequest(publishInput());
    const fetchImpl = jest.fn(async () =>
      new Response(JSON.stringify({ error: 'Not Found' }), { status: 404 }));

    const err = await publish(request, {
      accountToken: ACCOUNT_TOKEN,
      capabilityProvider: providerFor(request),
      scope: SCOPE,
      fetchImpl: fetchImpl as unknown as typeof fetch,
    }).catch((e: unknown) => e as FleetbotPublishError);

    expect((err as FleetbotPublishError).code).toBe('ROUTE_NOT_DEPLOYED');
    const report = (err as FleetbotPublishError).report();
    expect(report).toMatch(/PUBLICATION IS PENDING/);
    expect(report).toMatch(/claude\/fleetbot-publish-client/);
    expect(report).toMatch(/Do NOT publish this with a personal GitHub credential/);
  });

  test('the error report never suggests a credential fallback', async () => {
    const request = buildActionRequest(publishInput());
    const fetchImpl = jest.fn(async () =>
      new Response(JSON.stringify({ code: 'CAPABILITY_INVALID', error: 'bad' }), { status: 401 }));

    const err = await publish(request, {
      accountToken: ACCOUNT_TOKEN,
      capabilityProvider: providerFor(request),
      scope: SCOPE,
      fetchImpl: fetchImpl as unknown as typeof fetch,
    }).catch((e: unknown) => e as FleetbotPublishError);

    const report = (err as FleetbotPublishError).report();
    expect(report).not.toMatch(/\bgh auth\b|GH_TOKEN|personal access token/i);
    expect(report).toMatch(/authorship fraud/);
  });

  test('sends the bearer and the capability, and returns a verified receipt', async () => {
    const request = buildActionRequest(publishInput());
    let seenUrl = '';
    let seenInit: RequestInit | undefined;
    const fetchImpl = jest.fn(async (url: unknown, init: unknown) => {
      seenUrl = String(url);
      seenInit = init as RequestInit;
      return new Response(JSON.stringify({ code: 'OK', receipt: receiptFor() }), { status: 201 });
    });

    const result = await publish(request, {
      accountToken: ACCOUNT_TOKEN,
      capabilityProvider: providerFor(request),
      scope: SCOPE,
      fetchImpl: fetchImpl as unknown as typeof fetch,
    });

    expect(seenUrl).toBe(`${DEFAULT_RELAY_ORIGIN}/v1/fleetbot/publish`);
    expect((seenInit?.headers as Record<string, string>).Authorization).toBe(`Bearer ${ACCOUNT_TOKEN}`);
    const sent = JSON.parse(String(seenInit?.body));
    expect(sent.capabilitySignature).toMatch(/^[0-9a-f]{128}$/);
    expect(sent.capability.requestHash).toBe(requestHashOf(request));
    expect(result.status).toBe(201);
    expect(result.receipt.resourceNumber).toBe(1);
    expect(result.reused).toBe(false);
  });

  test('a success without a receipt is treated as ambiguous, not as success', async () => {
    const request = buildActionRequest(publishInput());
    const fetchImpl = jest.fn(async () => new Response(JSON.stringify({ code: 'OK' }), { status: 200 }));

    const err = await publish(request, {
      accountToken: ACCOUNT_TOKEN,
      capabilityProvider: providerFor(request),
      scope: SCOPE,
      fetchImpl: fetchImpl as unknown as typeof fetch,
    }).catch((e: unknown) => e as FleetbotPublishError);

    expect((err as FleetbotPublishError).code).toBe('RECEIPT_MISSING');
  });

  test('a receipt from a non-App authority fails the publish', async () => {
    const request = buildActionRequest(publishInput());
    const fetchImpl = jest.fn(async () =>
      new Response(
        JSON.stringify({ code: 'OK', receipt: receiptFor({ authority: 'human-pat' as never }) }),
        { status: 201 },
      ));

    await expect(
      publish(request, {
        accountToken: ACCOUNT_TOKEN,
        capabilityProvider: providerFor(request),
        scope: SCOPE,
        fetchImpl: fetchImpl as unknown as typeof fetch,
      }),
    ).rejects.toThrow(/failed verification/);
  });

  test('a network error preserves the work as pending', async () => {
    const request = buildActionRequest(publishInput());
    const fetchImpl = jest.fn(async () => { throw new Error('ECONNRESET'); });

    const err = await publish(request, {
      accountToken: ACCOUNT_TOKEN,
      capabilityProvider: providerFor(request),
      scope: SCOPE,
      fetchImpl: fetchImpl as unknown as typeof fetch,
    }).catch((e: unknown) => e as FleetbotPublishError);

    expect((err as FleetbotPublishError).code).toBe('RELAY_UNREACHABLE');
    expect((err as FleetbotPublishError).pending.sourceBranch).toBe('claude/fleetbot-publish-client');
  });
});
