import {
  chmodSync,
  existsSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  readlinkSync,
  renameSync,
  rmSync,
  symlinkSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { createHash } from 'node:crypto';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import {
  applyJuryRigBootstrap,
  createJuryRigBootstrapAuthority,
  JuryRigBootstrapInterruptedError,
  juryRigBootstrapLayout,
  NATIVE_JURY_RIG_HOOK_SHA256,
  planJuryRigBootstrap,
  readJuryRigBootstrapStatus,
  recoverInterruptedJuryRigBootstrap,
  redactJuryRigBootstrapPlan,
  rollbackJuryRigBootstrap,
  rollbackJuryRigBootstrapReceipt,
  verifyNativeJuryRigRuntime,
} from '../../lib/jury-rig-bootstrap.js';

const SCRATCH_ROOT = join(homedir(), 'coding', 'tmp');
const NOW = new Date('2026-09-01T03:00:00.000Z');
const EXPECTED_HEAD = 'a'.repeat(40);
const MERGE_COMMIT = 'b'.repeat(40);
const RELEASE_COMMIT = 'c'.repeat(40);
const FIXTURE_SECRET = 'fixture-secret-must-never-enter-receipts';
const LEGACY_NAME = ['win', 'dags'].join('');
const TEST_AUTHORITY = createJuryRigBootstrapAuthority(Buffer.alloc(32, 0x5a), 'fixture:jury-rig-authority:v1');

function sha256(value) {
  return createHash('sha256').update(value).digest('hex');
}

function put(path, content, mode = 0o644) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, { mode });
  chmodSync(path, mode);
}

function fixture() {
  mkdirSync(SCRATCH_ROOT, { recursive: true });
  const root = mkdtempSync(join(SCRATCH_ROOT, 'jury-rig-bootstrap-'));
  const home = join(root, 'home');
  const pdHome = join(home, '.port-daddy');
  const keg = join(root, 'Cellar', 'port-daddy', '9.9.9');
  const pdBinary = join(keg, 'bin', 'pd');
  const nativeHookPath = join(keg, 'share', 'port-daddy', 'hooks', 'sessionstart-pilot.mjs');
  const installedHook = join(pdHome, 'hooks', 'sessionstart-pilot.mjs');
  const runtimeSkills = join(home, '.codex', 'skills');
  const legacySkill = join(root, 'legacy', LEGACY_NAME, 'libexec', 'skills', 'demo-skill');

  put(pdBinary, 'fixture installed pd binary\n', 0o755);
  put(nativeHookPath, '// Native Jury-rig Pilot hook\nconst command = "pd jury-rig search";\n', 0o644);
  put(installedHook, `// legacy ${LEGACY_NAME} SessionStart authority\n`, 0o755);
  put(join(home, 'AGENTS.md'), `# AGENTS.md — User-Level Agent Guide

## ${LEGACY_NAME} Skill System

Run the external planner.

This file was generated by a legacy installer.
`);
  put(join(home, '.codex', 'AGENTS.md'), `# AGENTS.md — User-Level Agent Guide

## ${LEGACY_NAME} Skill System

Run the external planner.

This file was generated by a legacy installer.
`);
  put(join(home, '.gemini', 'GEMINI.md'), `# Personal Gemini instructions

<!-- ${LEGACY_NAME}-skills:start -->
Use ${LEGACY_NAME} and its MCP planning pipeline.
<!-- ${LEGACY_NAME}-skills:end -->

Keep this unrelated sentence.
`);
  put(join(home, '.claude', 'CLAUDE.md'), `# Personal Claude instructions

- Embrace ${LEGACY_NAME} and always use its planning runtime.

Historical note: the ${LEGACY_NAME} migration began in 2026.
Keep this unrelated sentence.
`);
  put(join(home, '.codex', 'config.toml'), `model = "fixture-model"

[marketplaces.${LEGACY_NAME}-skills]
source = "legacy"

[mcp_servers.${LEGACY_NAME}]
command = "node"

[mcp_servers.${LEGACY_NAME}.env]
ANTHROPIC_API_KEY = "${FIXTURE_SECRET}"

[mcp_servers.${LEGACY_NAME}.tools.${LEGACY_NAME}_skill_search]
approval_mode = "auto"

[plugins."${LEGACY_NAME}-skills@${LEGACY_NAME}-skills"]
enabled = true

[mcp_servers.port-daddy]
command = "pd"
args = ["mcp"]

[projects."/fixture/project"]
trust_level = "trusted"
`, 0o600);
  put(join(home, '.claude', 'settings.json'), JSON.stringify({
    enabledPlugins: {
      [`${LEGACY_NAME}-skills@${LEGACY_NAME}-skills`]: true,
      'kept-plugin@example': true,
    },
    extraKnownMarketplaces: {
      [`${LEGACY_NAME}-skills`]: { source: { repo: 'legacy/repo' } },
      kept: { source: { repo: 'kept/repo' } },
    },
    permissions: {
      allow: [`mcp__${LEGACY_NAME}__skill_search`, 'mcp__port-daddy__status'],
    },
    unrelated: { nested: 42 },
  }, null, 2) + '\n', 0o600);
  put(join(home, '.gemini', 'settings.json'), JSON.stringify({
    mcpServers: { 'port-daddy': { command: 'pd', args: ['mcp'] } },
    ui: { theme: 'Default' },
  }, null, 2) + '\n', 0o600);

  put(join(legacySkill, 'SKILL.md'), `---
name: demo-skill
description: Fixture skill body.
---

# Demo skill

Useful third-party guidance.
`);
  put(join(legacySkill, 'references', 'guide.md'), '# Preserved reference\n');
  put(join(legacySkill, 'LICENSE'), 'MIT fixture license\n');
  put(join(legacySkill, 'scripts', 'execute.sh'), '#!/bin/sh\necho should-not-copy\n', 0o755);
  put(join(legacySkill, 'agents', 'planner.md'), '# Third-party executable agent authority\n');
  put(join(legacySkill, 'hooks', 'session-start.json'), '{"command":"legacy"}\n');
  put(join(legacySkill, 'mcp', 'server.json'), '{"command":"legacy"}\n');
  mkdirSync(runtimeSkills, { recursive: true });
  symlinkSync(legacySkill, join(runtimeSkills, 'demo-skill'), 'dir');

  const options = {
    home,
    pdHome,
    nativeHookPath,
    runtimeTargets: [{ label: 'Codex fixture', path: runtimeSkills }],
    transactionRoot: join(pdHome, 'jury-rig-cutover', 'transactions'),
    importRoot: join(pdHome, 'catalogs', 'imported', LEGACY_NAME),
    repository: 'curiositech/port-daddy',
    replacementPr: 9965,
    expectedReplacementHead: EXPECTED_HEAD,
    authority: TEST_AUTHORITY,
  };
  return {
    root,
    home,
    pdHome,
    keg,
    pdBinary,
    nativeHookPath,
    installedHook,
    runtimeSkills,
    legacySkill,
    options,
  };
}

function proof(f, overrides = {}) {
  return {
    schemaVersion: 1,
    status: 'verified',
    repository: 'curiositech/port-daddy',
    replacementPr: 9965,
    prUrl: 'https://github.com/curiositech/port-daddy/pull/9965',
    prHead: EXPECTED_HEAD,
    prMergeCommit: MERGE_COMMIT,
    mergedAt: '2026-09-01T02:00:00.000Z',
    releaseTag: 'v9.9.9',
    releaseCommit: RELEASE_COMMIT,
    releaseComparison: 'ahead',
    installedPdPath: f.pdBinary,
    installedPdVersion: '9.9.9',
    installedPdSha256: sha256(readFileSync(f.pdBinary)),
    installedKeg: f.keg,
    nativeHookPath: f.nativeHookPath,
    nativeHookSha256: sha256(readFileSync(f.nativeHookPath)),
    juryRigSearchScannedCount: 1,
    verifiedAt: NOW.toISOString(),
    ...overrides,
  };
}

function attribution(overrides = {}) {
  return {
    agentId: 'agent-jury-rig-fixture',
    sessionId: 'session-jury-rig-fixture',
    remit: 'native Jury-rig machine cutover fixture',
    roadmapAuthority: 'provisional-local:fixture-roadmap',
    sourceHead: EXPECTED_HEAD,
    ...overrides,
  };
}

function applyFixture(options) {
  return applyJuryRigBootstrap({
    ...options,
    authority: TEST_AUTHORITY,
    gitleaksRunner: () => ({ findings: [] }),
    ...(options.proof ? { verifyRuntime: () => options.proof } : {}),
  });
}

function capturePath(path) {
  if (!existsSync(path) && !lstatPresent(path)) return { kind: 'missing' };
  const stat = lstatSync(path);
  if (stat.isSymbolicLink()) {
    return { kind: 'symlink', target: readlinkSync(path), mode: stat.mode & 0o777 };
  }
  if (stat.isFile()) {
    return {
      kind: 'file',
      bytes: readFileSync(path).toString('base64'),
      mode: stat.mode & 0o777,
    };
  }
  return { kind: 'other', mode: stat.mode & 0o777 };
}

function lstatPresent(path) {
  try {
    lstatSync(path);
    return true;
  } catch {
    return false;
  }
}

function surfaceSnapshot(f) {
  const layout = juryRigBootstrapLayout(f.options);
  const paths = [
    ...Object.values(layout.surfaces),
    join(f.runtimeSkills, 'demo-skill'),
  ];
  return Object.fromEntries(paths.map((path) => [path, capturePath(path)]));
}

function transactionTreeText(root) {
  const bodies = [];
  function visit(path) {
    for (const entry of readdirSync(path, { withFileTypes: true })) {
      const child = join(path, entry.name);
      if (entry.isDirectory()) visit(child);
      else if (entry.isFile()) bodies.push(readFileSync(child, 'utf8'));
    }
  }
  visit(root);
  return bodies.join('\n');
}

describe('native Jury-rig machine cutover', () => {
  test('compiled hook identity matches the checked-in packaged hook', () => {
    expect(sha256(readFileSync(join(process.cwd(), 'hooks', 'sessionstart-pilot.mjs'))))
      .toBe(NATIVE_JURY_RIG_HOOK_SHA256);
  });
  const roots = [];

  afterEach(() => {
    while (roots.length) rmSync(roots.pop(), { recursive: true, force: true });
  });

  function make() {
    const f = fixture();
    roots.push(f.root);
    return f;
  }

  test('plan/dry-run enumerates exact preimages, fields, postimages, and native gates with zero writes', () => {
    const f = make();
    const before = surfaceSnapshot(f);
    const plan = planJuryRigBootstrap(f.options);
    const after = surfaceSnapshot(f);

    expect(plan.verdict).toBe('ready');
    expect(after).toEqual(before);
    expect(existsSync(f.options.transactionRoot)).toBe(false);
    expect(existsSync(f.options.importRoot)).toBe(false);
    expect(plan.preconditions).toMatchObject({
      repository: 'curiositech/port-daddy',
      replacementPr: 9965,
      expectedReplacementHead: EXPECTED_HEAD,
      installedDistribution: 'homebrew-keg',
      nativeQueryRequired: true,
      githubMergeAncestryRequired: true,
    });
    expect(plan.inventory).toMatchObject({
      legacyProjectionLinks: 1,
      brokenLegacyProjectionLinks: 0,
      uniqueCatalogImports: 1,
    });

    const codex = plan.actions.find((action) => action.label === 'Codex tool config');
    expect(codex).toMatchObject({
      kind: 'file',
      path: join(f.home, '.codex', 'config.toml'),
    });
    expect(codex.beforeSha256).toMatch(/^[a-f0-9]{64}$/);
    expect(codex.afterSha256).toMatch(/^[a-f0-9]{64}$/);
    expect(codex.removedAuthorities).toEqual(expect.arrayContaining([
      `toml-table:marketplaces.${LEGACY_NAME}-skills`,
      `toml-table:mcp_servers.${LEGACY_NAME}`,
      `toml-table:mcp_servers.${LEGACY_NAME}.env`,
      `toml-table:mcp_servers.${LEGACY_NAME}.tools.${LEGACY_NAME}_skill_search`,
      `toml-table:plugins."${LEGACY_NAME}-skills@${LEGACY_NAME}-skills"`,
    ]));

    const redacted = JSON.stringify(redactJuryRigBootstrapPlan(plan));
    expect(redacted).not.toContain(FIXTURE_SECRET);
    expect(redacted).not.toContain('"content"');
    expect(redacted).toContain('legacy-catalog-projection');
  });

  test('apply preserves unrelated user fields, imports provenance without executables, and emits an attributable redacted receipt', () => {
    const f = make();
    const plan = planJuryRigBootstrap(f.options);
    const receipt = applyFixture({
      plan,
      proof: proof(f),
      attribution: attribution(),
      now: NOW,
    });

    expect(receipt.status).toBe('committed');
    expect(receipt.appliedCount).toBe(plan.actions.length);
    expect(receipt.attribution).toEqual(attribution());
    const receiptText = readFileSync(receipt.receiptPath, 'utf8');
    expect(receiptText).not.toContain(FIXTURE_SECRET);
    expect(transactionTreeText(receipt.transactionDir)).not.toContain(FIXTURE_SECRET);
    expect(receipt.receiptSha256).toMatch(/^[a-f0-9]{64}$/);

    const codex = readFileSync(join(f.home, '.codex', 'config.toml'), 'utf8');
    expect(codex).toContain('[mcp_servers.port-daddy]');
    expect(codex).toContain('[projects."/fixture/project"]');
    expect(codex.toLowerCase()).not.toContain(LEGACY_NAME);

    const claude = JSON.parse(readFileSync(join(f.home, '.claude', 'settings.json'), 'utf8'));
    expect(claude.enabledPlugins).toEqual({ 'kept-plugin@example': true });
    expect(claude.extraKnownMarketplaces).toEqual({ kept: { source: { repo: 'kept/repo' } } });
    expect(claude.permissions.allow).toEqual(['mcp__port-daddy__status']);
    expect(claude.unrelated).toEqual({ nested: 42 });

    expect(readFileSync(join(f.home, 'AGENTS.md'), 'utf8')).toContain('pd jury-rig search');
    expect(readFileSync(join(f.home, 'AGENTS.md'), 'utf8')).toContain('pd jury-rig graft');
    expect(readFileSync(join(f.home, '.gemini', 'GEMINI.md'), 'utf8')).toContain('Keep this unrelated sentence.');
    expect(readFileSync(join(f.home, '.claude', 'CLAUDE.md'), 'utf8')).toContain(`Historical note: the ${LEGACY_NAME} migration`);
    expect(readFileSync(f.installedHook, 'utf8')).toBe(readFileSync(f.nativeHookPath, 'utf8'));

    const projected = readlinkSync(join(f.runtimeSkills, 'demo-skill'));
    expect(projected).toContain(join('.port-daddy', 'catalogs', 'imported', LEGACY_NAME));
    expect(readFileSync(join(projected, 'SKILL.md'), 'utf8')).toContain('Imported catalog input only');
    expect(readFileSync(join(projected, 'references', 'guide.md'), 'utf8')).toContain('Preserved reference');
    expect(readFileSync(join(projected, 'LICENSE'), 'utf8')).toContain('MIT fixture license');
    expect(existsSync(join(projected, 'scripts', 'execute.sh'))).toBe(false);
    expect(existsSync(join(projected, 'agents', 'planner.md'))).toBe(false);
    expect(existsSync(join(projected, 'hooks', 'session-start.json'))).toBe(false);
    expect(existsSync(join(projected, 'mcp', 'server.json'))).toBe(false);
    const catalogManifest = JSON.parse(readFileSync(join(projected, '.port-daddy-catalog.json'), 'utf8'));
    expect(catalogManifest).toMatchObject({
      sourceKind: 'third-party-catalog-input',
      executableAuthority: false,
      sourceSkillSha256: sha256(readFileSync(join(f.legacySkill, 'SKILL.md'))),
    });
    expect(catalogManifest.skippedExecutableEntries).toBeGreaterThan(0);
  });

  test('stale or user-modified preimages refuse before any action applies', () => {
    const f = make();
    const plan = planJuryRigBootstrap(f.options);
    const agentsBefore = readFileSync(join(f.home, 'AGENTS.md'));
    const codexPath = join(f.home, '.codex', 'config.toml');
    put(codexPath, `${readFileSync(codexPath, 'utf8')}\n# user changed after plan\n`, 0o600);

    const receipt = applyFixture({
      plan,
      proof: proof(f),
      attribution: attribution(),
      now: NOW,
    });

    expect(receipt.status).toBe('refused');
    expect(receipt.appliedCount).toBe(0);
    expect(receipt.error).toContain('before-hash changed after planning');
    expect(readFileSync(join(f.home, 'AGENTS.md'))).toEqual(agentsBefore);
    expect(readlinkSync(join(f.runtimeSkills, 'demo-skill'))).toBe(f.legacySkill);
  });

  test('missing native proof, wrong installed bytes, and stale proof all fail closed with receipts', () => {
    const cases = [
      {
        name: 'missing proof',
        mutate: () => null,
        expectedCode: 'NATIVE_PROOF_REQUIRED',
      },
      {
        name: 'wrong installed bytes',
        mutate: (f) => {
          const p = proof(f);
          put(f.pdBinary, 'different installed build\n', 0o755);
          return p;
        },
        expectedCode: 'INSTALLED_BINARY_DRIFT',
      },
      {
        name: 'stale proof',
        mutate: (f) => proof(f, { verifiedAt: '2026-08-31T00:00:00.000Z' }),
        expectedCode: 'NATIVE_PROOF_STALE',
      },
    ];
    for (const entry of cases) {
      const f = make();
      const before = surfaceSnapshot(f);
      const plan = planJuryRigBootstrap(f.options);
      const receipt = applyFixture({
        plan,
        proof: entry.mutate(f),
        attribution: attribution(),
        now: NOW,
      });
      expect(receipt.status).toBe('refused');
      expect(receipt.blockers.map((blocker) => blocker.code)).toContain(entry.expectedCode);
      expect(surfaceSnapshot(f)).toEqual(before);
    }
  });

  test('apply independently re-verifies merged runtime authority before target writes', () => {
    const f = make();
    const before = surfaceSnapshot(f);
    const plan = planJuryRigBootstrap(f.options);
    const receipt = applyJuryRigBootstrap({
      plan,
      proof: proof(f),
      attribution: attribution(),
      now: NOW,
      authority: TEST_AUTHORITY,
      verifyRuntime: () => {
        throw new Error('replacement PR #9965 is not merged');
      },
    });

    expect(receipt.status).toBe('refused');
    expect(receipt.appliedCount).toBe(0);
    expect(receipt.blockers).toEqual(expect.arrayContaining([
      expect.objectContaining({
        code: 'NATIVE_RUNTIME_REVERIFY_FAILED',
        message: 'replacement PR #9965 is not merged',
      }),
    ]));
    expect(surfaceSnapshot(f)).toEqual(before);
  });

  test('partial apply failure rolls every applied surface back to its exact preimage', () => {
    const f = make();
    const before = surfaceSnapshot(f);
    const plan = planJuryRigBootstrap(f.options);
    const catalogTarget = plan.actions.find((action) => action.kind === 'catalog-import').targetPath;

    const receipt = applyFixture({
      plan,
      proof: proof(f),
      attribution: attribution(),
      now: NOW,
      failAfterAction: 4,
    });

    expect(receipt.status).toBe('rolled-back');
    expect(receipt.appliedCount).toBe(4);
    expect(receipt.rolledBackCount).toBe(4);
    expect(surfaceSnapshot(f)).toEqual(before);
    expect(existsSync(catalogTarget)).toBe(false);
  });

  test('an interrupted transaction is recovered from its durable manifest and exact backups', () => {
    const f = make();
    const before = surfaceSnapshot(f);
    const plan = planJuryRigBootstrap(f.options);
    let interruption;
    try {
      applyFixture({
        plan,
        proof: proof(f),
        attribution: attribution(),
        now: NOW,
        interruptAfterAction: 5,
      });
    } catch (error) {
      interruption = error;
    }
    expect(interruption).toBeInstanceOf(JuryRigBootstrapInterruptedError);
    expect(surfaceSnapshot(f)).not.toEqual(before);

    const receipt = recoverInterruptedJuryRigBootstrap(plan, interruption.transactionDir, { authority: TEST_AUTHORITY });
    expect(receipt.status).toBe('rolled-back');
    expect(receipt.rolledBackCount).toBe(5);
    expect(surfaceSnapshot(f)).toEqual(before);
  });

  test('recovery compensates a crash after rename but before the applied checkpoint', () => {
    const f = make();
    const before = surfaceSnapshot(f);
    const plan = planJuryRigBootstrap(f.options);
    let interruption;
    try {
      applyFixture({
        plan,
        proof: proof(f),
        attribution: attribution(),
        now: NOW,
        interruptAfterMutationBeforeCheckpoint: 3,
      });
    } catch (error) {
      interruption = error;
    }
    expect(interruption).toBeInstanceOf(JuryRigBootstrapInterruptedError);
    expect(surfaceSnapshot(f)).not.toEqual(before);

    const receipt = recoverInterruptedJuryRigBootstrap(plan, interruption.transactionDir, { authority: TEST_AUTHORITY });
    expect(receipt.status).toBe('rolled-back');
    expect(surfaceSnapshot(f)).toEqual(before);
  });

  test('recovery takes over an authenticated transaction after a real lock-owner SIGKILL', async () => {
    const f = make();
    const before = surfaceSnapshot(f);
    const plan = planJuryRigBootstrap(f.options);
    let interruption;
    try {
      applyFixture({
        plan,
        proof: proof(f),
        attribution: attribution(),
        now: NOW,
        interruptAfterMutationBeforeCheckpoint: 2,
      });
    } catch (error) {
      interruption = error;
    }
    expect(interruption).toBeInstanceOf(JuryRigBootstrapInterruptedError);

    const lockPath = join(f.pdHome, 'jury-rig-cutover', 'cutover.lock');
    const childScript = `
      const fs = require('node:fs');
      const lock = process.argv[1];
      fs.mkdirSync(lock, { recursive: true, mode: 0o700 });
      fs.writeFileSync(lock + '/owner.json', JSON.stringify({ transactionId: 'killed-owner', pid: process.pid }) + '\\n');
      process.stdout.write('ready\\n');
      setInterval(() => {}, 1000);
    `;
    const child = spawn(process.execPath, ['-e', childScript, lockPath], { stdio: ['ignore', 'pipe', 'pipe'] });
    await once(child.stdout, 'data');
    child.kill('SIGKILL');
    await once(child, 'exit');

    const receipt = recoverInterruptedJuryRigBootstrap(plan, interruption.transactionDir, { authority: TEST_AUTHORITY });
    expect(receipt.status).toBe('rolled-back');
    expect(surfaceSnapshot(f)).toEqual(before);
    expect(existsSync(lockPath)).toBe(false);
  });

  test('rollback verifies the immutable apply receipt, then restores exact preimages', () => {
    const f = make();
    const before = surfaceSnapshot(f);
    const plan = planJuryRigBootstrap(f.options);
    const applyReceipt = applyFixture({
      plan,
      proof: proof(f),
      attribution: attribution(),
      now: NOW,
    });
    const originalReceipt = readFileSync(applyReceipt.receiptPath, 'utf8');
    const tampered = JSON.parse(originalReceipt);
    tampered.appliedCount = 0;
    put(applyReceipt.receiptPath, JSON.stringify(tampered, null, 2) + '\n', 0o600);
    expect(() => rollbackJuryRigBootstrap(plan, applyReceipt.receiptPath, { authority: TEST_AUTHORITY })).toThrow(/keyed receipt authorization/);
    put(applyReceipt.receiptPath, originalReceipt, 0o600);

    const rollbackReceipt = rollbackJuryRigBootstrapReceipt(applyReceipt.receiptPath, { authority: TEST_AUTHORITY });
    expect(rollbackReceipt.status).toBe('rolled-back');
    expect(rollbackReceipt.receiptPath).not.toBe(applyReceipt.receiptPath);
    expect(existsSync(applyReceipt.receiptPath)).toBe(true);
    expect(surfaceSnapshot(f)).toEqual(before);
  });

  test('status returns only bounded authenticated terminal receipts', () => {
    const f = make();
    const plan = planJuryRigBootstrap(f.options);
    const applyReceipt = applyFixture({
      plan,
      proof: proof(f),
      attribution: attribution(),
      now: NOW,
    });
    expect(readJuryRigBootstrapStatus(plan.layout, { authority: TEST_AUTHORITY }))
      .toEqual([expect.objectContaining({ id: applyReceipt.id, status: 'committed' })]);

    const tampered = JSON.parse(readFileSync(applyReceipt.receiptPath, 'utf8'));
    tampered.status = 'refused';
    put(applyReceipt.receiptPath, JSON.stringify(tampered) + '\n', 0o600);
    expect(() => readJuryRigBootstrapStatus(plan.layout, { authority: TEST_AUTHORITY }))
      .toThrow(/keyed receipt authorization/);
  });

  test('rollback fails closed over post-cutover user drift', () => {
    const f = make();
    const plan = planJuryRigBootstrap(f.options);
    const applyReceipt = applyFixture({
      plan,
      proof: proof(f),
      attribution: attribution(),
      now: NOW,
    });
    put(join(f.home, 'AGENTS.md'), '# user changed after cutover\n');
    expect(() => rollbackJuryRigBootstrap(plan, applyReceipt.receiptPath, { authority: TEST_AUTHORITY })).toThrow(/post-cutover drift/);
  });

  test('rollback rejects a foreign transaction root and an unauthorized import-root layout before path use', () => {
    const f = make();
    const plan = planJuryRigBootstrap(f.options);
    const applyReceipt = applyFixture({
      plan,
      proof: proof(f),
      attribution: attribution(),
      now: NOW,
    });
    const other = make();
    const sameLengthWrongPlan = planJuryRigBootstrap(other.options);
    expect(sameLengthWrongPlan.actions).toHaveLength(plan.actions.length);
    expect(() => rollbackJuryRigBootstrap(sameLengthWrongPlan, applyReceipt.receiptPath, { authority: TEST_AUTHORITY }))
      .toThrow(/unsafe transaction path/i);

    const wrongLayout = {
      ...plan,
      layout: { ...plan.layout, importRoot: join(f.root, 'wrong-import-root') },
    };
    expect(() => rollbackJuryRigBootstrap(wrongLayout, applyReceipt.receiptPath, { authority: TEST_AUTHORITY }))
      .toThrow(/plan (authorization|digest)/i);
  });

  test('a recomputed public hash cannot forge rollback authority', () => {
    const f = make();
    const plan = planJuryRigBootstrap(f.options);
    const applyReceipt = applyFixture({
      plan,
      proof: proof(f),
      attribution: attribution(),
      now: NOW,
    });
    const forged = JSON.parse(readFileSync(applyReceipt.receiptPath, 'utf8'));
    forged.attribution.sourceHead = 'd'.repeat(40);
    const { receiptSha256: _old, ...unsigned } = forged;
    forged.receiptSha256 = sha256(JSON.stringify(unsigned));
    put(applyReceipt.receiptPath, JSON.stringify(forged, null, 2) + '\n', 0o600);
    expect(() => rollbackJuryRigBootstrap(plan, applyReceipt.receiptPath, { authority: TEST_AUTHORITY }))
      .toThrow(/keyed receipt|authorization/i);
  });

  test('planning refuses symlinked config parents and a held exclusive cutover lock', () => {
    const f = make();
    const realCodex = join(f.home, '.codex-real');
    renameSync(join(f.home, '.codex'), realCodex);
    symlinkSync(realCodex, join(f.home, '.codex'), 'dir');
    const symlinked = planJuryRigBootstrap(f.options);
    expect(symlinked.blockers.map((blocker) => blocker.code)).toContain('SYMLINKED_SURFACE_PATH');

    rmSync(join(f.home, '.codex'));
    renameSync(realCodex, join(f.home, '.codex'));
    const plan = planJuryRigBootstrap(f.options);
    const lockPath = join(f.pdHome, 'jury-rig-cutover', 'cutover.lock');
    mkdirSync(lockPath, { recursive: true });
    expect(() => applyFixture({
      plan,
      proof: proof(f),
      attribution: attribution(),
      now: NOW,
    })).toThrow(/exclusive cutover lock/i);
  });

  test('apply reclaims a lock whose recorded process no longer exists', () => {
    const f = make();
    const plan = planJuryRigBootstrap(f.options);
    const lockPath = join(f.pdHome, 'jury-rig-cutover', 'cutover.lock');
    mkdirSync(lockPath, { recursive: true });
    put(join(lockPath, 'owner.json'), JSON.stringify({
      transactionId: 'crashed-owner',
      pid: 2_147_483_647,
      acquiredAt: NOW.toISOString(),
    }) + '\n', 0o600);

    const receipt = applyFixture({
      plan,
      proof: proof(f),
      attribution: attribution(),
      now: NOW,
    });
    expect(receipt.status).toBe('committed');
    expect(existsSync(lockPath)).toBe(false);
  });

  test('tampered catalog reuse is blocked instead of trusted from manifest claims', () => {
    const f = make();
    const firstPlan = planJuryRigBootstrap(f.options);
    const firstReceipt = applyFixture({
      plan: firstPlan,
      proof: proof(f),
      attribution: attribution(),
      now: NOW,
    });
    expect(firstReceipt.status).toBe('committed');
    const link = join(f.runtimeSkills, 'demo-skill');
    const imported = readlinkSync(link);
    unlinkSync(link);
    symlinkSync(f.legacySkill, link, 'dir');
    put(join(imported, 'references', 'guide.md'), '# tampered imported reference\n');

    const reusePlan = planJuryRigBootstrap(f.options);
    expect(reusePlan.verdict).toBe('blocked');
    expect(reusePlan.blockers.map((blocker) => blocker.code)).toContain('CATALOG_IMPORT_TAMPERED');
  });

  test('native verifier rejects a missing command and a repository-controlled fake before GitHub proof', () => {
    expect(() => verifyNativeJuryRigRuntime({
      repository: 'curiositech/port-daddy',
      replacementPr: 9965,
      pdCommand: 'definitely-missing-pd-fixture-command',
      now: NOW,
    })).toThrow(/cannot resolve trusted executable/);

    const f = make();
    const fake = join(f.root, 'not-a-keg', 'pd');
    put(fake, '#!/bin/sh\nif [ "$1" = "--version" ]; then echo 9.9.9; exit 0; fi\nexit 1\n', 0o755);
    expect(() => verifyNativeJuryRigRuntime({
      repository: 'curiositech/port-daddy',
      replacementPr: 9965,
      pdCommand: fake,
      now: NOW,
    })).toThrow(/installed Homebrew keg/);
  });
});
