/**
 * HPKE base-mode key wrap (RFC 9180 / ADR-0123 A4-B3) — two independent
 * checks, kept apart deliberately:
 *
 * 1. The low-level HPKE core (LabeledExtract/LabeledExpand, DHKEM
 *    Encap/Decap, KeySchedule, single-shot Seal/Open) against RFC 9180's
 *    own official test-vectors.json entry for DHKEM(X25519,HKDF-SHA256) /
 *    HKDF-SHA256 / AES-256-GCM (mode=0, kem_id=32, kdf_id=1, aead_id=2).
 *    This is bytes this implementation did not generate — the strongest
 *    kind of proof available for a from-scratch primitive.
 *
 * 2. wrapChannelKeyForDevice/unwrapChannelKeyForDevice — port-daddy's own
 *    composition of that core with KeyWrapAad — against a SELF-GENERATED
 *    known-answer vector, same provenance discipline as the Rust crate's
 *    KATs (see core/kernel/pd-vault/src/{keys,seal}.rs test modules): these
 *    bytes came out of THIS implementation and were pasted back in. They
 *    are NOT RFC vectors and not yet cross-checked against the Rust
 *    hpke.rs module — see the file-level report for the values to diff.
 *
 * The RFC9180_OFFICIAL_VECTOR constant below was generated by a script that
 * read https://raw.githubusercontent.com/cfrg/draft-irtf-cfrg-hpke/master/
 * test-vectors.json directly and printed the matching entry's fields as TS
 * source — every hex string here was machine-copied from that JSON, never
 * hand-retyped. That mattered: an earlier hand-transcription of the same
 * vector (an upstream research pass, not this file) turned out to have
 * dropped the trailing hex nibble off nearly every 32-byte field. Re-fetching
 * and diffing byte-for-byte is what caught it — worth remembering before
 * trusting any hand-copied crypto constant, including the ones below.
 */

import { describe, it, expect } from '@jest/globals';
import { createPrivateKey, createPublicKey } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

import {
  X25519_KEY_LEN,
  HPKE_AEAD_KEY_LEN,
  HPKE_AEAD_NONCE_LEN,
  HPKE_AEAD_TAG_LEN,
  KEY_WRAP_AAD_LABEL,
  CHANNEL_KEY_LEN,
  hpkeEncapBase,
  hpkeDecapBase,
  hpkeKeyScheduleBase,
  hpkeSealBase,
  hpkeOpenBase,
  encodeKeyWrapAad,
  wrapChannelKeyForDevice,
  unwrapChannelKeyForDevice,
  VaultTsError,
  type KeyWrapAad,
  type WrappedKey,
} from '../../lib/pd-vault-ts.js';

const hex = (b: Uint8Array): string => Buffer.from(b).toString('hex');
const fromHex = (h: string): Buffer => Buffer.from(h, 'hex');
const seqBytes = (start: number, len: number): Buffer =>
  Buffer.from(Array.from({ length: len }, (_, i) => (start + i) & 0xff));

const HERE = path.dirname(fileURLToPath(import.meta.url));
const wrapVectors = (
  JSON.parse(readFileSync(path.resolve(HERE, '../fixtures/pd-vault-parity-vectors.json'), 'utf8')) as {
    hpke_wrap: {
      labels: { key_wrap_aad_label: string };
      kat: {
        channel_key_hex: string;
        sender_ephemeral_secret_hex: string;
        recipient_secret_hex: string;
        recipient_public_hex: string;
        aad: {
          account_id: string;
          harbor_id: string;
          authority_epoch: number;
          recipient_device_id: string;
          grant: string;
          key_purpose: string;
          key_id: string;
        };
        aad_hex: string;
        enc_hex: string;
        ciphertext_hex: string;
      };
    };
  }
).hpke_wrap;

// ---------------------------------------------------------------------
// RFC 9180 official vector — machine-copied, see the file doc comment.
// mode=0 (base), kem_id=32 (0x0020, DHKEM(X25519,HKDF-SHA256)),
// kdf_id=1 (0x0001, HKDF-SHA256), aead_id=2 (0x0002, AES-256-GCM).
// ---------------------------------------------------------------------
const RFC9180_OFFICIAL_VECTOR = {
  info: '4f6465206f6e2061204772656369616e2055726e',
  skEm: '179d4b53b6365c45b600c4163b61d95cbc2f4d9e36f1695558dce265ab8bab11',
  pkEm: '6c93e09869df3402d7bf231bf540fadd35cd56be14f97178f0954db94b7fc256',
  skRm: '497b4502664cfea5d5af0b39934dac72242a74f8480451e1aee7d6a53320333d',
  pkRm: '430f4b9859665145a6b1ba274024487bd66f03a2dd577d7753c68d7d7d00c00c',
  enc: '6c93e09869df3402d7bf231bf540fadd35cd56be14f97178f0954db94b7fc256',
  shared_secret: '3101c54c3a4f87439eaac080699ed9bbcc726ffe44e860c0424ccb7e3e2ead7b',
  key_schedule_context:
    '004ce5472ecdd5093ba0aecb8f871ff13f1fbc90ee76f0e18ace1a1b7e565bafa306f6ef962c9ee7cea40407b5d60f0f26990472faae3ac44c78366f1cac1ecde1',
  secret: '2058ac9b02c1f52c1aaf08bedbec9198219751a94ef67b7d5f0c8b6e2b54ebfb',
  key: 'f50b0609186798729ed0564b36ef2ef8044f1f9d05636874d1f46c819c7a669f',
  base_nonce: '151d9929e2449747889bc923',
  exporter_secret: '86017151bbff6a1940e8abae2ac9e0e7032e33df1eaaecc02ca6259b130d62df',
  encryptions: [
    {
      aad: '436f756e742d30',
      nonce: '151d9929e2449747889bc923',
      pt: '4265617574792069732074727574682c20747275746820626561757479',
      ct: 'e5d84cd531cfb583096e7cfa9641bd3079cf3a91cda813c52deb5f512be9931980a41de125a925cdad859d5b7a',
    },
    {
      aad: '436f756e742d31',
      nonce: '151d9929e2449747889bc922',
      pt: '4265617574792069732074727574682c20747275746820626561757479',
      ct: '2c43aff25343fdbff864506f0818b9d87df84ea01b1a2144d23b4d40c26bf655fdf197fe40297a8aebeed5cc2d',
    },
  ],
} as const;

describe('HPKE core vs. RFC 9180 official test vector (DHKEM(X25519,HKDF-SHA256)/HKDF-SHA256/AES-256-GCM)', () => {
  const info = fromHex(RFC9180_OFFICIAL_VECTOR.info);
  const skEm = fromHex(RFC9180_OFFICIAL_VECTOR.skEm);
  const pkRm = fromHex(RFC9180_OFFICIAL_VECTOR.pkRm);
  const skRm = fromHex(RFC9180_OFFICIAL_VECTOR.skRm);

  it('KNOWN ANSWER: Encap with the vector\'s fixed ephemeral reproduces enc and shared_secret', () => {
    const { enc, sharedSecret } = hpkeEncapBase(pkRm, skEm);
    expect(hex(enc)).toBe(RFC9180_OFFICIAL_VECTOR.enc);
    expect(hex(sharedSecret)).toBe(RFC9180_OFFICIAL_VECTOR.shared_secret);
  });

  it('KNOWN ANSWER: Decap with the vector\'s recipient secret reproduces the same shared_secret', () => {
    const sharedSecret = hpkeDecapBase(fromHex(RFC9180_OFFICIAL_VECTOR.enc), skRm);
    expect(hex(sharedSecret)).toBe(RFC9180_OFFICIAL_VECTOR.shared_secret);
  });

  it('KNOWN ANSWER: KeySchedule reproduces key_schedule_context, key, base_nonce, exporter_secret', () => {
    const sharedSecret = fromHex(RFC9180_OFFICIAL_VECTOR.shared_secret);
    const ks = hpkeKeyScheduleBase(sharedSecret, info);
    expect(hex(ks.keyScheduleContext)).toBe(RFC9180_OFFICIAL_VECTOR.key_schedule_context);
    expect(hex(ks.key)).toBe(RFC9180_OFFICIAL_VECTOR.key);
    expect(hex(ks.baseNonce)).toBe(RFC9180_OFFICIAL_VECTOR.base_nonce);
    expect(hex(ks.exporterSecret)).toBe(RFC9180_OFFICIAL_VECTOR.exporter_secret);
  });

  it('KNOWN ANSWER: SealBase (fixed ephemeral) reproduces the official AES-256-GCM ciphertext at seq=0', () => {
    // This is the one link the upstream research pass flagged as NOT
    // independently verified in its sandbox (no working AEAD tool). It is
    // exercised here through the real hpkeSealBase/hpkeOpenBase — the exact
    // functions wrapChannelKeyForDevice/unwrapChannelKeyForDevice call —
    // not a parallel reimplementation in the test.
    const first = RFC9180_OFFICIAL_VECTOR.encryptions[0];
    const { enc, ciphertext } = hpkeSealBase(pkRm, info, fromHex(first.aad), fromHex(first.pt), skEm);
    expect(hex(enc)).toBe(RFC9180_OFFICIAL_VECTOR.enc);
    expect(hex(ciphertext)).toBe(first.ct);

    const recovered = hpkeOpenBase(enc, skRm, info, fromHex(first.aad), ciphertext);
    expect(hex(recovered)).toBe(first.pt);
  });

  it('KNOWN ANSWER: OpenBase recovers plaintext directly from the vector\'s own ciphertext (seq=0)', () => {
    const first = RFC9180_OFFICIAL_VECTOR.encryptions[0];
    const recovered = hpkeOpenBase(
      fromHex(RFC9180_OFFICIAL_VECTOR.enc),
      skRm,
      info,
      fromHex(first.aad),
      fromHex(first.ct)
    );
    expect(hex(recovered)).toBe(first.pt);
  });

  it('the vector\'s seq=1 nonce is base_nonce XOR I2OSP(1,12) — ComputeNonce, exercised outside the single-shot API', () => {
    // hpkeSealBase/hpkeOpenBase are single-shot by design (seq is always 0 —
    // see their doc comments), so this file's shipped API never computes a
    // seq!=0 nonce. This test checks the RFC's ComputeNonce formula directly
    // against the vector's seq=1 entry using the derived base_nonce, purely
    // to confirm the module's understanding of the spec is correct — not a
    // code path wrapChannelKeyForDevice/unwrapChannelKeyForDevice exercise.
    const sharedSecret = fromHex(RFC9180_OFFICIAL_VECTOR.shared_secret);
    const { baseNonce } = hpkeKeyScheduleBase(sharedSecret, info);
    const second = RFC9180_OFFICIAL_VECTOR.encryptions[1];
    const computed = Buffer.from(baseNonce);
    computed[computed.length - 1] ^= 0x01; // I2OSP(1, 12) is all zero bytes except the last
    expect(hex(computed)).toBe(second.nonce);
  });

  it('suite ids match RFC 9180 §4.1/§5.1 for this ciphersuite', () => {
    // KEM_SUITE_ID/HPKE_SUITE_ID are module-private; this pins them
    // indirectly by checking that Encap/KeySchedule land on the vector's
    // published outputs, which is only possible if both suite_id
    // constructions are exactly right. Recorded here as a named check
    // rather than leaving it implicit in the tests above.
    const { sharedSecret } = hpkeEncapBase(pkRm, skEm);
    expect(hex(sharedSecret)).toBe(RFC9180_OFFICIAL_VECTOR.shared_secret);
  });
});

describe('HPKE key wrap — structural contracts', () => {
  it('X25519 keys and the AES-256-GCM AEAD sizes match RFC 9180 for this ciphersuite', () => {
    expect(X25519_KEY_LEN).toBe(32);
    expect(HPKE_AEAD_KEY_LEN).toBe(32);
    expect(HPKE_AEAD_NONCE_LEN).toBe(12);
    expect(HPKE_AEAD_TAG_LEN).toBe(16);
  });

  it('KEY_WRAP_AAD_LABEL is distinct from the A3 pipeline\'s labels', () => {
    expect(KEY_WRAP_AAD_LABEL).toBe('pd-vault/keywrap/v1');
  });

  it('rejects a malformed recipient public key length explicitly, not as a decrypt failure', () => {
    expect(() => hpkeEncapBase(Buffer.alloc(31))).toThrow(VaultTsError);
    try {
      hpkeEncapBase(Buffer.alloc(31));
    } catch (e) {
      expect((e as VaultTsError).code).toBe('BAD_KEY');
    }
  });

  it('rejects a low-order (all-zero) recipient public key on the encap/wrap side', () => {
    expect(() => hpkeEncapBase(Buffer.alloc(32, 0))).toThrow(VaultTsError);
    try {
      hpkeEncapBase(Buffer.alloc(32, 0));
    } catch (e) {
      expect((e as VaultTsError).code).toBe('BAD_KEY');
    }
  });
});

describe('encodeKeyWrapAad', () => {
  const aad: KeyWrapAad = {
    accountId: 'acct-1',
    harborId: 'harbor-1',
    authorityEpoch: 4,
    recipientDeviceId: 'device-1',
    grant: 'use',
    keyPurpose: 'channel',
    keyId: 'harbor/alpha',
  };

  it('is injective across field boundaries, same anti-ambiguity property as encodeSealAad', () => {
    // PREMISE: components that would collide under naive concatenation.
    const left = { ...aad, accountId: 'ab', harborId: 'c' };
    const right = { ...aad, accountId: 'a', harborId: 'bc' };
    expect(encodeKeyWrapAad(left).equals(encodeKeyWrapAad(right))).toBe(false);
  });

  it('refuses each empty structural field explicitly', () => {
    for (const field of ['accountId', 'harborId', 'recipientDeviceId', 'grant', 'keyPurpose', 'keyId'] as const) {
      expect(() => encodeKeyWrapAad({ ...aad, [field]: '' })).toThrow(VaultTsError);
      try {
        encodeKeyWrapAad({ ...aad, [field]: '' });
      } catch (e) {
        expect((e as VaultTsError).code).toBe('EMPTY_COMPONENT');
      }
    }
  });

  it('does NOT validate grant or key_purpose against a closed set — matches the Rust crate exactly', () => {
    // ADR-0123 A4/B3: "the ladder position itself is enforced by whatever
    // consults this string, not by this crate" (see KeyWrapAad's Rust doc
    // comment). An unrecognized-but-non-empty value is accepted here, same
    // as the Rust side — only emptiness is a structural error.
    expect(() => encodeKeyWrapAad({ ...aad, grant: 'admin' })).not.toThrow();
    expect(() => encodeKeyWrapAad({ ...aad, keyPurpose: 'invoice' })).not.toThrow();
  });
});

describe('wrapChannelKeyForDevice / unwrapChannelKeyForDevice — self-generated KAT', () => {
  // ---------------------------------------------------------------------
  // Known-answer vector, v1 — SELF-GENERATED.
  //
  // Provenance, stated plainly (same discipline as the Rust crate's own
  // KATs in keys.rs/seal.rs): these bytes came out of THIS implementation
  // and were pasted back in. They are NOT RFC vectors and are not yet
  // cross-checked against the Rust hpke.rs module's own fixture — that
  // cross-check is pending, per the file-level report.
  //
  // wrapChannelKeyForDevice always draws a fresh ephemeral keypair from the
  // CSPRNG (see hpkeEncapBase's doc comment for why that is not overridable
  // on its signature), so a byte-exact ciphertext KAT is only reproducible
  // by fixing the ephemeral at the hpkeSealBase layer — the same technique
  // RFC 9180's own official vectors use. This KAT therefore pins
  // hpkeSealBase/hpkeOpenBase (the exact composition
  // wrapChannelKeyForDevice/unwrapChannelKeyForDevice call, with
  // KeyWrapAad's encoding as both info and aad) with the ephemeral fixed;
  // a separate test below round-trips the real, fresh-ephemeral
  // wrapChannelKeyForDevice/unwrapChannelKeyForDevice for functional
  // correctness rather than a frozen byte value.
  // ---------------------------------------------------------------------

  const KAT_CHANNEL_KEY = seqBytes(0x00, 32);
  const KAT_RECIPIENT_SECRET = seqBytes(0x20, 32);
  const KAT_EPHEMERAL_SECRET = seqBytes(0x40, 32);
  const KAT_RECIPIENT_PUBKEY = fromHex('358072d6365880d1aeea329adf9121383851ed21a28e3b75e965d0d2cd166254');
  const KAT_AAD: KeyWrapAad = {
    accountId: 'acct-kat',
    harborId: 'harbor-kat',
    authorityEpoch: 7,
    recipientDeviceId: 'device-kat-1',
    grant: 'use',
    keyPurpose: 'channel',
    keyId: 'harbor/alpha',
  };
  const KAT_AAD_ENCODED_HEX =
    '000000080000001370642d7661756c742f6b6579777261702f763100000008616363742d6b61740000000a686172626f722d6b61740000000800000000000000070000000c6465766963652d6b61742d3100000003757365000000076368616e6e656c0000000c686172626f722f616c706861';
  const KAT_ENC_HEX = '79a631eede1bf9c98f12032cdeadd0e7a079398fc786b88cc846ec89af85a51a';
  const KAT_CIPHERTEXT_HEX =
    'fd40b8e37131f73fd1bf856179e5765210b3a6200bb5139d06732adc570324d772d8d5c3797d137e633fcefe4e0e03fa';

  it('KAT_RECIPIENT_PUBKEY really is derived from KAT_RECIPIENT_SECRET (premise, not asserted elsewhere)', () => {
    const priv = createPrivateKey({
      key: Buffer.concat([Buffer.from('302e020100300506032b656e04220420', 'hex'), KAT_RECIPIENT_SECRET]),
      format: 'der',
      type: 'pkcs8',
    });
    const derived = createPublicKey(priv).export({ format: 'der', type: 'spki' });
    expect(hex(derived.subarray(derived.length - 32))).toBe(hex(KAT_RECIPIENT_PUBKEY));
  });

  it('KNOWN ANSWER: KeyWrapAad encoding is byte-stable', () => {
    expect(hex(encodeKeyWrapAad(KAT_AAD))).toBe(KAT_AAD_ENCODED_HEX);
  });

  it('KNOWN ANSWER: hpkeSealBase with the fixed ephemeral reproduces enc and ciphertext, and opens back', () => {
    const encoded = encodeKeyWrapAad(KAT_AAD);
    const { enc, ciphertext } = hpkeSealBase(
      KAT_RECIPIENT_PUBKEY,
      encoded,
      encoded,
      KAT_CHANNEL_KEY,
      KAT_EPHEMERAL_SECRET
    );
    expect(hex(enc)).toBe(KAT_ENC_HEX);
    expect(hex(ciphertext)).toBe(KAT_CIPHERTEXT_HEX);

    const recovered = unwrapChannelKeyForDevice({ enc, ciphertext }, KAT_RECIPIENT_SECRET, KAT_AAD);
    expect(recovered.equals(KAT_CHANNEL_KEY)).toBe(true);
  });

  it('wrapChannelKeyForDevice/unwrapChannelKeyForDevice round-trip with a fresh ephemeral each call', () => {
    const first = wrapChannelKeyForDevice(KAT_CHANNEL_KEY, KAT_RECIPIENT_PUBKEY, KAT_AAD);
    const second = wrapChannelKeyForDevice(KAT_CHANNEL_KEY, KAT_RECIPIENT_PUBKEY, KAT_AAD);
    // PREMISE: a fresh ephemeral really is drawn every call — otherwise the
    // adversarial tests below could pass for the wrong reason.
    expect(first.enc.equals(second.enc)).toBe(false);
    expect(first.enc.length).toBe(X25519_KEY_LEN);
    expect(first.ciphertext.length).toBe(CHANNEL_KEY_LEN + HPKE_AEAD_TAG_LEN);

    expect(unwrapChannelKeyForDevice(first, KAT_RECIPIENT_SECRET, KAT_AAD).equals(KAT_CHANNEL_KEY)).toBe(true);
    expect(unwrapChannelKeyForDevice(second, KAT_RECIPIENT_SECRET, KAT_AAD).equals(KAT_CHANNEL_KEY)).toBe(true);
  });

  it('rejects a wrong-length channel key explicitly at wrap time', () => {
    expect(() => wrapChannelKeyForDevice(Buffer.alloc(31), KAT_RECIPIENT_PUBKEY, KAT_AAD)).toThrow(VaultTsError);
  });

  describe('every adversarial input fails closed with the one opaque DECRYPT error', () => {
    // PREMISE for the whole block, asserted once: the untampered wrap opens.
    const wrapped = wrapChannelKeyForDevice(KAT_CHANNEL_KEY, KAT_RECIPIENT_PUBKEY, KAT_AAD);
    it('premise: the untampered wrapped key opens under the sealing context', () => {
      expect(unwrapChannelKeyForDevice(wrapped, KAT_RECIPIENT_SECRET, KAT_AAD).equals(KAT_CHANNEL_KEY)).toBe(true);
    });

    const expectOpaqueFailure = (fn: () => unknown) => {
      try {
        fn();
        throw new Error('expected a decryption failure');
      } catch (e) {
        expect(e).toBeInstanceOf(VaultTsError);
        expect((e as VaultTsError).code).toBe('DECRYPT');
        expect((e as VaultTsError).message).toBe('decryption failed');
      }
    };

    it('wrong recipient key fails to open', () => {
      expectOpaqueFailure(() => unwrapChannelKeyForDevice(wrapped, seqBytes(0x99, 32), KAT_AAD));
    });

    it('a tampered enc fails to open', () => {
      const tampered: WrappedKey = { enc: Buffer.from(wrapped.enc), ciphertext: wrapped.ciphertext };
      tampered.enc[0] ^= 0x01;
      expectOpaqueFailure(() => unwrapChannelKeyForDevice(tampered, KAT_RECIPIENT_SECRET, KAT_AAD));
    });

    it('a wrong-length enc fails to open (not a distinguishing structural error)', () => {
      const tampered: WrappedKey = { enc: wrapped.enc.subarray(0, 31), ciphertext: wrapped.ciphertext };
      expectOpaqueFailure(() => unwrapChannelKeyForDevice(tampered, KAT_RECIPIENT_SECRET, KAT_AAD));
    });

    it('a tampered ciphertext fails to open, at every byte', () => {
      for (const index of [0, wrapped.ciphertext.length - HPKE_AEAD_TAG_LEN, wrapped.ciphertext.length - 1]) {
        const tamperedCiphertext = Buffer.from(wrapped.ciphertext);
        tamperedCiphertext[index] ^= 0x01;
        expectOpaqueFailure(() =>
          unwrapChannelKeyForDevice({ enc: wrapped.enc, ciphertext: tamperedCiphertext }, KAT_RECIPIENT_SECRET, KAT_AAD)
        );
      }
    });

    it('truncated ciphertext fails to open, including below the tag boundary', () => {
      for (const cut of [0, 1, HPKE_AEAD_TAG_LEN - 1, HPKE_AEAD_TAG_LEN, wrapped.ciphertext.length - 1]) {
        expectOpaqueFailure(() =>
          unwrapChannelKeyForDevice(
            { enc: wrapped.enc, ciphertext: wrapped.ciphertext.subarray(0, cut) },
            KAT_RECIPIENT_SECRET,
            KAT_AAD
          )
        );
      }
    });

    it.each(['accountId', 'harborId', 'recipientDeviceId', 'keyId'] as const)(
      'a tampered AAD.%s fails to open',
      (field) => {
        const tamperedAad: KeyWrapAad = { ...KAT_AAD, [field]: `${KAT_AAD[field]}-evil` };
        expectOpaqueFailure(() => unwrapChannelKeyForDevice(wrapped, KAT_RECIPIENT_SECRET, tamperedAad));
      }
    );

    it('a tampered AAD.authorityEpoch fails to open', () => {
      const tamperedAad: KeyWrapAad = { ...KAT_AAD, authorityEpoch: KAT_AAD.authorityEpoch + 1 };
      expectOpaqueFailure(() => unwrapChannelKeyForDevice(wrapped, KAT_RECIPIENT_SECRET, tamperedAad));
    });

    it('a tampered AAD.grant fails to open', () => {
      const tamperedAad: KeyWrapAad = { ...KAT_AAD, grant: 'manage' };
      expectOpaqueFailure(() => unwrapChannelKeyForDevice(wrapped, KAT_RECIPIENT_SECRET, tamperedAad));
    });

    it('a tampered AAD.keyPurpose fails to open', () => {
      const tamperedAad: KeyWrapAad = { ...KAT_AAD, keyPurpose: 'content' };
      expectOpaqueFailure(() => unwrapChannelKeyForDevice(wrapped, KAT_RECIPIENT_SECRET, tamperedAad));
    });

    it('every failure mode above renders the identical message — the no-oracle invariant', () => {
      const wrongKey = seqBytes(0x99, 32);
      const tamperedEnc = Buffer.from(wrapped.enc);
      tamperedEnc[0] ^= 0x01;
      const tamperedCt = Buffer.from(wrapped.ciphertext);
      tamperedCt[0] ^= 0x01;

      const failures = [
        () => unwrapChannelKeyForDevice(wrapped, wrongKey, KAT_AAD),
        () => unwrapChannelKeyForDevice({ enc: tamperedEnc, ciphertext: wrapped.ciphertext }, KAT_RECIPIENT_SECRET, KAT_AAD),
        () => unwrapChannelKeyForDevice({ enc: wrapped.enc, ciphertext: tamperedCt }, KAT_RECIPIENT_SECRET, KAT_AAD),
        () => unwrapChannelKeyForDevice(wrapped, KAT_RECIPIENT_SECRET, { ...KAT_AAD, harborId: 'harbor-evil' }),
        () => unwrapChannelKeyForDevice(wrapped, KAT_RECIPIENT_SECRET, { ...KAT_AAD, authorityEpoch: KAT_AAD.authorityEpoch + 1 }),
      ];

      const messages = failures.map((fn) => {
        try {
          fn();
          return '(did not throw)';
        } catch (e) {
          return (e as VaultTsError).message;
        }
      });
      expect(messages.every((m) => m === 'decryption failed')).toBe(true);
    });
  });
});

describe('pd-vault parity — hpke_wrap KAT (Rust core/kernel/pd-vault/src/hpke.rs)', () => {
  // ADR-0120: a second implementation of kernel crypto exists ONLY under a
  // shared fixture asserted by BOTH suites (see pd-vault-ts-parity.test.ts's
  // header comment — this is the same rule applied to the HPKE wrap path).
  // The vectors here are the canonical Rust crate's own KAT
  // (wrap_channel_key_for_device / wrap_kat_is_stable), copied into
  // tests/fixtures/pd-vault-parity-vectors.json's hpke_wrap section — NOT
  // generated by this file. If either implementation's bytes ever drift,
  // this suite goes red instead of the two forking silently.
  const katChannelKey = fromHex(wrapVectors.kat.channel_key_hex);
  const katEphemeralSecret = fromHex(wrapVectors.kat.sender_ephemeral_secret_hex);
  const katRecipientSecret = fromHex(wrapVectors.kat.recipient_secret_hex);
  const katRecipientPubkey = fromHex(wrapVectors.kat.recipient_public_hex);
  const katAad: KeyWrapAad = {
    accountId: wrapVectors.kat.aad.account_id,
    harborId: wrapVectors.kat.aad.harbor_id,
    authorityEpoch: wrapVectors.kat.aad.authority_epoch,
    recipientDeviceId: wrapVectors.kat.aad.recipient_device_id,
    grant: wrapVectors.kat.aad.grant,
    keyPurpose: wrapVectors.kat.aad.key_purpose,
    keyId: wrapVectors.kat.aad.key_id,
  };

  it('KEY_WRAP_AAD_LABEL matches the Rust crate', () => {
    expect(KEY_WRAP_AAD_LABEL).toBe(wrapVectors.labels.key_wrap_aad_label);
  });

  it('encodeKeyWrapAad reproduces the crate\'s aad_hex byte-for-byte', () => {
    expect(hex(encodeKeyWrapAad(katAad))).toBe(wrapVectors.kat.aad_hex);
  });

  it('recipient_public_hex really is derived from recipient_secret_hex (premise)', () => {
    const priv = createPrivateKey({
      key: Buffer.concat([Buffer.from('302e020100300506032b656e04220420', 'hex'), katRecipientSecret]),
      format: 'der',
      type: 'pkcs8',
    });
    const derived = createPublicKey(priv).export({ format: 'der', type: 'spki' });
    expect(hex(derived.subarray(derived.length - 32))).toBe(hex(katRecipientPubkey));
  });

  it('KNOWN ANSWER: hpkeSealBase with the crate\'s fixed ephemeral reproduces the crate\'s enc and ciphertext', () => {
    const encoded = encodeKeyWrapAad(katAad);
    const { enc, ciphertext } = hpkeSealBase(
      katRecipientPubkey,
      encoded,
      encoded,
      katChannelKey,
      katEphemeralSecret
    );
    expect(hex(enc)).toBe(wrapVectors.kat.enc_hex);
    expect(hex(ciphertext)).toBe(wrapVectors.kat.ciphertext_hex);
  });

  it('KNOWN ANSWER: unwrapChannelKeyForDevice recovers the crate\'s channel key from the crate\'s own wrapped bytes', () => {
    const wrapped: WrappedKey = {
      enc: fromHex(wrapVectors.kat.enc_hex),
      ciphertext: fromHex(wrapVectors.kat.ciphertext_hex),
    };
    const recovered = unwrapChannelKeyForDevice(wrapped, katRecipientSecret, katAad);
    expect(recovered.equals(katChannelKey)).toBe(true);
  });
});
