import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { inflateSync } from 'node:zlib';
import { describe, expect, test } from '@jest/globals';

// Executable, adversarial acceptance contract for the stacked publication artifact.
//
// Chapter III (spawn-to-person) used to publish a standalone PDF of its own;
// that is retired (an A4 render of the same words with no margin column, a
// worse layout of the Book's 7x10in trim), so this contract no longer binds
// a per-chapter PDF — only the chapter's .tex source, its catalog entry, and
// the shared review evidence that still names it.
const paths = {
  catalog: 'website-v2/src/data/whitePapers.ts',
  source: 'website-v2/public/whitepaper/spawn-to-person.tex',
  keystone: 'website-v2/public/whitepaper/figures/tab-keystone-split.tex',
  contact: 'docs/artifacts/whitepaper-figure-semantics/all-volumes/all-seven-volumes-color-contact-sheet.png',
  tour: 'docs/artifacts/whitepaper-figure-semantics/all-volumes/all-seven-volumes-color-tour.gif',
  proof: 'docs/artifacts/whitepaper-figure-semantics/all-volumes/proof-manifest.md',
  digests: 'website-v2/public/whitepaper/publication-digests.json',
};

// The review artifacts (contact sheet, tour) are frozen evidence from the
// semantic-figure review; their digests are pinned here and in the proof
// manifest. The PDFs themselves are regenerated by CI on every source change,
// so their digests live in publication-digests.json (written by
// `npm run fix:whitepaper-metadata` in website-v2) rather than in literals.
const reviewSha256 = {
  contact: 'e74fad8acce50400e536f8a81120643b48ff1589d8d1e3ff3da479a3b45768f6',
  tour: 'fd6021b6dffaf8670550b075bbd81bd1af555070aa353b4c90316393ac61f12f',
};

const publicationPdfs = [
  // One published Book. Which typographic character it carries is set by
  // \pdedition's default in the preamble (Swiss today); the maritime and
  // technical drivers remain switchable, are not built, and publish nothing.
  // The eight chapters no longer publish a standalone PDF of their own.
  'website-v2/public/whitepaper/coordination-papers-mega-volume.pdf',
];

function publicationDigests() {
  return JSON.parse(text(paths.digests)).pdfs;
}

function text(path) {
  return readFileSync(path, 'utf8');
}

function sha256(path) {
  return createHash('sha256').update(readFileSync(path)).digest('hex');
}

function decodedPdfText(pdf) {
  const streamMarker = Buffer.from('stream');
  const endMarker = Buffer.from('endstream');
  const fragments = [pdf.toString('latin1')];
  let cursor = 0;

  while ((cursor = pdf.indexOf(streamMarker, cursor)) !== -1) {
    const dictionaryStart = pdf.lastIndexOf(Buffer.from('<<'), cursor);
    const dictionary = pdf
      .subarray(Math.max(0, dictionaryStart), cursor)
      .toString('latin1');
    let dataStart = cursor + streamMarker.length;
    if (pdf[dataStart] === 13 && pdf[dataStart + 1] === 10) dataStart += 2;
    else if (pdf[dataStart] === 10) dataStart += 1;
    const dataEnd = pdf.indexOf(endMarker, dataStart);
    if (dataEnd === -1) break;

    if (/\/FlateDecode/.test(dictionary)) {
      let data = pdf.subarray(dataStart, dataEnd);
      while (data.length > 0 && (data.at(-1) === 10 || data.at(-1) === 13)) {
        data = data.subarray(0, -1);
      }
      try {
        fragments.push(inflateSync(data).toString('latin1'));
      } catch {
        // A non-object content stream may use predictors; it cannot add page objects.
      }
    }
    cursor = dataEnd + endMarker.length;
  }

  return fragments.join('\n');
}

function pdfPageCount(pdf) {
  // Prefer the page-tree /Count: leaf /Type /Page objects can land inside
  // compressed object streams where a plain text scan undercounts (observed
  // with pdfTeX 1.40.29 output), and dict attribute order varies by producer.
  const text = decodedPdfText(pdf);
  const counts = [...text.matchAll(
    /\/Type\s*\/Pages\b[^>]*?\/Count\s+(\d+)|\/Count\s+(\d+)[^>]*?\/Type\s*\/Pages\b/g,
  )].map((m) => Number(m[1] ?? m[2]));
  if (counts.length) return Math.max(...counts);
  return text.match(/\/Type\s*\/Page\b/g)?.length ?? 0;
}

function pngDimensions(png) {
  expect(png.subarray(0, 8)).toEqual(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]));
  expect(png.subarray(12, 16).toString('ascii')).toBe('IHDR');
  return {
    width: png.readUInt32BE(16),
    height: png.readUInt32BE(20),
  };
}

function skipGifSubBlocks(gif, start) {
  let cursor = start;
  while (cursor < gif.length) {
    const size = gif[cursor];
    cursor += 1;
    if (size === 0) return cursor;
    cursor += size;
  }
  throw new Error('unterminated GIF sub-block stream');
}

function parseGif(gif) {
  expect(gif.subarray(0, 6).toString('ascii')).toMatch(/^GIF8[79]a$/);
  const canvas = { width: gif.readUInt16LE(6), height: gif.readUInt16LE(8) };
  const packed = gif[10];
  let cursor = 13;
  if (packed & 0x80) cursor += 3 * 2 ** ((packed & 0x07) + 1);
  const frames = [];

  while (cursor < gif.length) {
    const block = gif[cursor];
    if (block === 0x3b) break;
    if (block === 0x21) {
      cursor = skipGifSubBlocks(gif, cursor + 2);
      continue;
    }
    if (block !== 0x2c) throw new Error(`unexpected GIF block 0x${block.toString(16)}`);

    const frame = {
      width: gif.readUInt16LE(cursor + 5),
      height: gif.readUInt16LE(cursor + 7),
    };
    const imagePacked = gif[cursor + 9];
    cursor += 10;
    if (imagePacked & 0x80) cursor += 3 * 2 ** ((imagePacked & 0x07) + 1);
    cursor += 1; // LZW minimum code size
    cursor = skipGifSubBlocks(gif, cursor);
    frames.push(frame);
  }

  return { canvas, frames };
}

describe('Spawn-to-Person publication contract', () => {
  test('the maturity plot marks partial only where the runtime has a grounded substrate', () => {
    const source = text(paths.source);
    const keystone = text(paths.keystone);

    // The maturity words are set by macro so no subsystem can round itself up.
    expect(source).toMatch(/\\newcommand\{\\BUILTWEAK\}.*\\textsc\{partial\}/);
    // Checkpoint and outcome ledger are the two subsystems marked partial; memory is built.
    expect(source).toContain('Subsystem 1 --- Memory: the episodic record \\quad\\BUILT}');
    expect(source).toContain('Subsystem 2 --- Checkpoint: restorable state \\quad\\BUILTWEAK}');
    expect(source).toContain('Subsystem 3 --- Outcome ledger: the witnessed record of delivery \\quad\\BUILTWEAK}');
    // The continuity-subsystems table (which replaced the three-subsystems figure) says
    // what each partial subsystem does not carry across a restart.
    expect(source).toContain('\\label{tab:stp-organs}');
    expect(source).toContain('recovery restores notes, not execution');
    expect(source).toContain('an outcome nobody witnessed; a closure no oracle checked');
    // The keystone split (now a table shared with the economy chapter) keeps
    // the one row the market rests on and does not yet have.
    expect(keystone).toContain('no cross-operator binding proof');
    expect(keystone).toContain('a signed, intact history still does not prove who controls the foreign key');

    expect(text('lib/actor-souls.ts')).toContain('daemon-minted, non-forgeable actor identity');
    expect(text('tests/unit/actor-souls.test.js')).toContain('forged / self-asserted rejection');
    expect(text('lib/commitments.ts')).toContain('Durable Commitments');
    expect(text('routes/commitments.ts')).toContain('commitment');
    expect(text('tests/unit/commitments.test.js')).toContain('commitment');
  });

  test('catalog and changelog publish the Chapter III edition transition', () => {
    const catalog = text(paths.catalog);
    // Anchor on the catalog entry itself, not on a crossRef `{ id: 'spawn-to-person', why }`.
    const chapterStart = catalog.indexOf("    id: 'spawn-to-person',\n    slug: 'spawn-to-person',");
    const chapterEnd = catalog.indexOf("    id: 'harbor-economy',\n    slug:", chapterStart);
    expect(chapterStart).toBeGreaterThanOrEqual(0);
    expect(chapterEnd).toBeGreaterThan(chapterStart);
    const chapter = catalog.slice(chapterStart, chapterEnd);

    // The chapter carries no `pages`/`sizeKb`/`pdfPath` — it no longer
    // publishes a standalone PDF for those to describe (retired: an A4
    // render of the same words with no margin column). The version string
    // is the one fact this contract still pins.
    expect(chapter).toMatch(/status: 'Version \d+\.\d+ \(textbook edition\)'/);
    expect(chapter).not.toContain('pdfPath:')
    expect(chapter).not.toContain('pages:')
    expect(chapter).not.toContain('sizeKb:')
    expect(catalog).toContain('Spawn-to-Person diagrams and implementation status align');
    expect(catalog).toContain("chapters: ['spawn-to-person']");
  });

  // Chapter III's own PDF is retired, so the artifact this contract reads
  // back is the Book. The three facts stay the three facts: the page tree the
  // file really carries, the byte length it really has, and its digest — all
  // against the manifest, which is what the site and the catalog quote. The
  // page count is read out of the PDF here rather than from `pdfinfo`, so the
  // check holds on a runner with no poppler (check-whitepaper-metadata.ts
  // degrades when pdfinfo is absent; this does not).
  test('every publication PDF is the artifact the digest manifest declares', () => {
    const digests = publicationDigests();
    expect(Object.keys(digests).sort()).toEqual([...publicationPdfs].sort());
    for (const artifact of publicationPdfs) {
      const pdf = readFileSync(artifact);
      expect(pdfPageCount(pdf)).toBe(digests[artifact].pages);
      expect(pdf.length).toBe(digests[artifact].bytes);
      expect(sha256(artifact)).toBe(digests[artifact].sha256);
    }
  });

  test('the proof manifest still binds the frozen review evidence', () => {
    const proof = text(paths.proof);
    for (const [artifact, expected] of Object.entries(reviewSha256)) {
      expect(sha256(paths[artifact])).toBe(expected);
      expect(proof).toContain(expected);
    }
    // The manifest is a frozen record of the first-edition review (August
    // 2026, seven chapters plus the Book, all still named in its table by
    // their now-retired standalone-PDF paths); it is historical evidence and
    // stays as written. The one publication PDF that still exists today (the
    // Book) must still have a row there, and the manifest must say where the
    // current digests live now that PDFs are regenerated per edition.
    for (const artifact of publicationPdfs) {
      expect(proof).toContain(`\`${artifact}\``);
    }
    expect(proof).toContain('publication-digests.json');
  });

  test('the color contact sheet and seven-frame tour preserve the inspected volume geometry', () => {
    expect(pngDimensions(readFileSync(paths.contact))).toEqual({ width: 3792, height: 3576 });
    const gif = parseGif(readFileSync(paths.tour));
    expect(gif.canvas).toEqual({ width: 900, height: 1740 });
    expect(gif.frames).toHaveLength(7);
    // Optimized GIFs encode later frames as delta rectangles inside the canvas.
    expect(gif.frames.every((frame) => (
      frame.width > 0
      && frame.height > 0
      && frame.width <= gif.canvas.width
      && frame.height <= gif.canvas.height
    ))).toBe(true);
  });

  test('all edited figures remain inside the brand palette', () => {
    const result = spawnSync(process.execPath, ['website-v2/scripts/check-figure-palette.mjs'], {
      cwd: process.cwd(),
      encoding: 'utf8',
    });
    expect(result.status).toBe(0);
    expect(result.stdout).toContain('on the brand palette');
  });
});
